// sarathi-vue-1.0/src/components/Users/BHA/EQ/Analysis/BhaarathaSharesSectorCategoryAnalysisData.vue
<template>
  <div class="bhaaratha-shares-sector-category-analysis-data">
    <div class="services-analysis-sector-category-data">
      <div class="spinner" v-if="loading">
        <MoneyManagerLoading></MoneyManagerLoading>
      </div>
      <div v-if="noRecords" class="no-records">
        ******* NO RECORDS *******
      </div>
      <div v-if="!loading && !noRecords">
        <div class="services-analysis-chart">
          <apexchart height="500" :options="chartOptions" :series="chartSeries"></apexchart>
        </div>
        <div class="services-analysis-content">
          With <b>{{ total.numberOfScripts }}</b> number of script/s, the invested value is <b>{{ total.investedValue }}</b> and the current value is <b>{{ total.currentValue }}</b>. Your portfolio has provided a total return of <span v-highlight-by-numbers="'bold'">{{ total.profitLoss }}</span> (<span v-highlight-by-numbers="'bold'">{{ total.profitLossPercentage }}%</span>)
          </div>
      </div>
    </div>
  </div>
</template>

<script>
import MoneyManagerLoading from '@/components/common/MoneyManagerLoading.vue';

export default {
  components: {
    MoneyManagerLoading
  },

  props: {
    loading: {
      type: Boolean,
      required: true
    },
    noRecords: {
      type: Boolean,
      required: true
    },
    chartSeries: {
      type: Array,
      required: true
    },
    chartOptions: {
      type: Object,
      required: true
    },
    total: {
      type: Object,
      required: true
    }
  }
}
</script>

// sarathi-ang-1.0/src/app/components/users/BHA/EQ/Analysis/bhaaratha-shares-sector-category-analysis-data/bhaaratha-shares-sector-category-analysis-data.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-bhaaratha-shares-sector-category-analysis-data',
  templateUrl: './bhaaratha-shares-sector-category-analysis-data.component.html',
  styleUrls: ['./bhaaratha-shares-sector-category-analysis-data.component.css']
})
export class BhaarathaSharesSectorCategoryAnalysisDataComponent implements OnInit {

  @Input() loading!: boolean;
  @Input() noRecords!: boolean;
  @Input() chartOptions!: any;
  @Input() total!: any;

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="bhaaratha-shares-sector-category-analysis-data">
  <div class="services-analysis-sector-category-data">
    <div class="spinner" *ngIf="loading">
      <app-money-manager-loading></app-money-manager-loading>
    </div>
    <div *ngIf="noRecords" class="no-records">
      ******* NO RECORDS *******
    </div>
    <div *ngIf="!loading && !noRecords">
      <div class="services-analysis-chart">
        <apx-chart
          [series]="chartOptions.series"
          [title]="chartOptions.title"
          [states]="chartOptions.states"
          [chart]="chartOptions.chart" Z
          [dataLabels]="chartOptions.dataLabels"
          [plotOptions]="chartOptions.plotOptions"
          [colors]="chartOptions.colors"
          [legend]="chartOptions.legend"
          [fill]="chartOptions.fill"
          [stroke]="chartOptions.stroke"
          [tooltip]="chartOptions.tooltip"
          [xaxis]="chartOptions.xaxis"
        ></apx-chart>
      </div>
      <div class="services-analysis-content">
        With <b>{{ total.numberOfScripts }}</b> number of script/s, the invested value is <b>{{ total.investedValue }}</b> and the current value is <b>{{ total.currentValue }}</b>. Your portfolio has provided a total return of <span appHighlightByNumbers [value]="total.profitLoss" [fontWeight]="'bold'">{{ total.profitLoss }}</span> (<span appHighlightByNumbers [value]="total.profitLossPercentage" [fontWeight]="'bold'">{{ total.profitLossPercentage }}%</span>)
        </div>
    </div>
  </div>
</div>
