// sarathi-vue-1.0/src/components/common/DatePicker/MoneyManagerDatePickerYearView.vue
<template>
  <div class="date-picker-year-view">
    <div class="date-picker-top-container">
      <span
        class="date-picker-top date-picker-navigate"
        @click="onPreviousYearListClick()"
      ><i class="fas fa-caret-left"></i></span>
      <span class="date-picker-top date-picker-year-combination">{{ displayStartYear + " - " + displayEndYear }}</span>
      <span
        class="date-picker-top date-picker-navigate"
        @click="onNextYearListClick()"
      ><i class="fas fa-caret-right"></i></span>
    </div>
    <div class="date-picker-table">
      <div class="date-picker-year-heading">YEAR</div>
      <table>
        <tr v-for="calendarYear of calendarYearsList" :key="calendarYear.rowId">
          <td
            v-for="yearList of calendarYear.yearList"
            :key="yearList.yearId"
            :id="[displayYear === yearList.year ? 'date-picker-year' : '']"
            class="date-picker-year"
            @click="onYearSelect(yearList.year)"
          >
            {{ yearList.year }}
          </td>
        </tr>
      </table>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    displayYear: {
      type: String,
      required: true
    },
    calendarYearsList: {
      type: Array,
      required: true
    },
    displayStartYear: {
      type: String,
      required: true
    },
    displayEndYear: {
      type: String,
      required: true
    }
  },

  methods: {
    onPreviousYearListClick() {
      this.$emit("onPreviousYearList");
    },

    onNextYearListClick() {
      this.$emit("onNextYearList");
    },

    onYearSelect(year) {
      this.$emit("onYearSelect", year);
    }
  }
}
</script>

// sarathi-ang-1.0/src/app/components/common/DatePicker/money-manager-date-picker-year-view/money-manager-date-picker-year-view.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';

@Component({
  selector: 'app-money-manager-date-picker-year-view',
  templateUrl: './money-manager-date-picker-year-view.component.html',
  styleUrls: ['./money-manager-date-picker-year-view.component.css']
})
export class MoneyManagerDatePickerYearViewComponent implements OnInit {

  @Input() displayYear!: string;
  @Input() calendarYearsList!: Array<any>;
  @Input() displayStartYear!: string;
  @Input() displayEndYear!: string;
  @Output("onPreviousYearList") previousYearListEventEmitter = new EventEmitter<any>();
  @Output("onNextYearList") nextYearListEventEmitter = new EventEmitter<any>();
  @Output("onYearSelect") yearSelectEventEmitter = new EventEmitter<string>();

  constructor() { }

  ngOnInit(): void {
  }

  onPreviousYearListClick() {
    this.previousYearListEventEmitter.emit();
  }

  onNextYearListClick() {
    this.nextYearListEventEmitter.emit();
  }

  onYearSelect(year: string) {
    this.yearSelectEventEmitter.emit(year);
  }

}

<div class="date-picker-year-view">
  <div class="date-picker-top-container">
    <span
      class="date-picker-top date-picker-navigate"
      (click)="onPreviousYearListClick()"
    ><i class="fas fa-caret-left"></i></span>
    <span class="date-picker-top date-picker-year-combination">{{ displayStartYear + " - " + displayEndYear }}</span>
    <span
      class="date-picker-top date-picker-navigate"
      (click)="onNextYearListClick()"
    ><i class="fas fa-caret-right"></i></span>
  </div>
  <div class="date-picker-table">
    <div class="date-picker-year-heading">YEAR</div>
    <table>
      <tr *ngFor="let calendarYear of calendarYearsList">
        <td
          *ngFor="let yearList of calendarYear.yearList"
          [id]="[displayYear === yearList.year ? 'date-picker-year' : '']"
          class="date-picker-year"
          (click)="onYearSelect(yearList.year)"
        >
          {{ yearList.year }}
        </td>
      </tr>
    </table>
  </div>
</div>
