// sarathi-ang-1.0/src/app/components/users/USA/EQ/united-states-of-america-shares-add-sold/united-states-of-america-shares-add-sold.component.ts
import { Component, OnInit } from '@angular/core';
import services from 'src/assets/services/services.json';
import { getDefaultDate } from 'src/app/common/utils/utils';
import { Router } from '@angular/router';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-united-states-of-america-shares-add-sold',
  templateUrl: './united-states-of-america-shares-add-sold.component.html',
  styleUrls: ['./united-states-of-america-shares-add-sold.component.css']
})
export class UnitedStatesOfAmericaSharesAddSoldComponent implements OnInit {

  yahooCode: string = "";
  shareName: string = "";
  shareNameLoading: boolean = false;
  sellDate: string = "";
  resetSellDatePicker: boolean = false;
  sellQuantity: string = "";
  sellPrice: string = "";
  sellCommission: string = "";
  sellTransactionFees: string = "";
  sellOtherFees: string = "";

  // Error field flags
  errorFlagYahooCode: boolean = false;
  errorFlagShareName: boolean = false;
  errorFlagSellDate: boolean = false;
  errorFlagSellQuantity: boolean = false;
  errorFlagSellPrice: boolean = false;
  errorFlagSellCommission: boolean = false;
  errorFlagSellTransactionFees: boolean = false;
  errorFlagSellOtherFees: boolean = false;

  // Error field messages
  errorMessageYahooCode: string = "";
  errorMessageShareName: string = "";
  errorMessageSellDate: string = "";
  errorMessageSellQuantity: string = "";
  errorMessageSellPrice: string = "";
  errorMessageSellCommission: string = "";
  errorMessageSellTransactionFees: string = "";
  errorMessageSellOtherFees: string = "";

  // Error/Success Modal
  showError: boolean = false;
  errorMessage: string = "";
  showSuccess: boolean = false;
  successMessage: string = "";

  constructor(
    private router: Router,
    private http: HttpClient
  ) { }

  ngOnInit(): void {
  }

  onBackButtonClicked() {
    this.router.navigate(["/users/USA/EQ/sold"]);
  }

  onSellDateSelect(selectedSellDate: string) {
    this.resetSellDatePicker = false;
    this.inputOnFocus('sold-united-states-of-america-share-sell-date');
    this.sellDate = selectedSellDate;
  }

  getShareName() {
    this.shareNameLoading = true;

    this.http.get(services.unitedStatesOfAmericaShareNameDetails + "?scriptCode=" + this.yahooCode).subscribe((response: any) => {
      if (response === null) {
        this.shareName = "";
        this.shareNameLoading = false;
      } else {
        this.shareName = response.scriptName;
        this.shareNameLoading = false;
      }
    }, error => {
      error.error.error.map((e: any) => {
        this.errorMessage = e.errorMessage;
        this.showError = true;
      });
    });
  }

  onUnitedStatesOfAmericaSharesAddSharesClear() {

    // In case of error, change input border color
    (document.getElementById("sold-united-states-of-america-share-yahoo-code") as HTMLElement).style.border = "";
    (document.getElementById("sold-united-states-of-america-share-script-name") as HTMLElement).style.border = "";
    (document.getElementById("sold-united-states-of-america-share-sell-quantity") as HTMLElement).style.border = "";
    (document.getElementById("sold-united-states-of-america-share-sell-price") as HTMLElement).style.border = "";
    (document.getElementById("sold-united-states-of-america-share-sell-commission") as HTMLElement).style.border = "";
    (document.getElementById("sold-united-states-of-america-share-sell-transaction-fees") as HTMLElement).style.border = "";
    (document.getElementById("sold-united-states-of-america-share-sell-other-fees") as HTMLElement).style.border = "";

    this.yahooCode = "";
    this.shareName = "";
    this.sellQuantity = "";
    this.sellPrice = "";
    this.sellCommission = "";
    this.sellTransactionFees = "";
    this.sellOtherFees = "";
    this.sellDate = getDefaultDate("");
    this.resetSellDatePicker = true;

    // Error field flags
    this.errorFlagYahooCode = false;
    this.errorFlagShareName = false;
    this.errorFlagSellDate = false;
    this.errorFlagSellQuantity = false;
    this.errorFlagSellPrice = false;
    this.errorFlagSellCommission = false;
    this.errorFlagSellTransactionFees = false;
    this.errorFlagSellOtherFees = false;

    // Error field messages
    this.errorMessageYahooCode = "";
    this.errorMessageShareName = "";
    this.errorMessageSellDate = "";
    this.errorMessageSellQuantity = "";
    this.errorMessageSellPrice = "";
    this.errorMessageSellCommission = "";
    this.errorMessageSellTransactionFees = "";
    this.errorMessageSellOtherFees = "";
  }

  onUnitedStatesOfAmericaSharesAddSharesSubmit() {
    const formData = {
      yahooCode: this.yahooCode,
      scriptName: this.shareName,
      sellDate: this.sellDate,
      sellQuantity: this.sellQuantity,
      sellPrice: this.sellPrice,
      sellCommission: this.sellCommission,
      sellTransactionFees: this.sellTransactionFees,
      sellOtherFees: this.sellOtherFees
    };

    this.http.post(services.unitedStatesOfAmericaSharesShares + "?type=sold", formData).subscribe((response: any) => {

      this.successMessage = response.message;
      this.showSuccess = true;

      this.sellQuantity = "";
      this.sellPrice = "";
      this.sellCommission = "";
      this.sellTransactionFees = "";
      this.sellOtherFees = "";
      this.sellDate = getDefaultDate("");
      this.resetSellDatePicker = true;

    }, error => {
      error.error.error.map((e: any) => {
        if (e.uiField === "sold-united-states-of-america-share-yahoo-code") {
          (document.getElementById(e.uiField) as HTMLElement).style.border = "0.1rem solid red";
          this.errorFlagYahooCode = true;
          this.errorMessageYahooCode = e.errorMessage;
        } else if (e.uiField === "sold-united-states-of-america-share-script-name") {
          (document.getElementById(e.uiField) as HTMLElement).style.border = "0.1rem solid red";
          this.errorFlagShareName = true;
          this.errorMessageShareName = e.errorMessage;
        } else if (e.uiField === "sold-united-states-of-america-share-sell-date") {
          this.errorFlagSellDate = true;
          this.errorMessageSellDate = e.errorMessage;
        } else if (e.uiField === "sold-united-states-of-america-share-sell-quantity") {
          (document.getElementById(e.uiField) as HTMLElement).style.border = "0.1rem solid red";
          this.errorFlagSellQuantity = true;
          this.errorMessageSellQuantity = e.errorMessage;
        } else if (e.uiField === "sold-united-states-of-america-share-sell-price") {
          (document.getElementById(e.uiField) as HTMLElement).style.border = "0.1rem solid red";
          this.errorFlagSellPrice = true;
          this.errorMessageSellPrice = e.errorMessage;
        } else if (e.uiField === "sold-united-states-of-america-share-sell-commission") {
          (document.getElementById(e.uiField) as HTMLElement).style.border = "0.1rem solid red";
          this.errorFlagSellCommission = true;
          this.errorMessageSellCommission = e.errorMessage;
        } else if (e.uiField === "sold-united-states-of-america-share-sell-transaction-fees") {
          (document.getElementById(e.uiField) as HTMLElement).style.border = "0.1rem solid red";
          this.errorFlagSellTransactionFees = true;
          this.errorMessageSellTransactionFees = e.errorMessage;
        } else if (e.uiField === "sold-united-states-of-america-share-sell-other-fees") {
          (document.getElementById(e.uiField) as HTMLElement).style.border = "0.1rem solid red";
          this.errorFlagSellOtherFees = true;
          this.errorMessageSellOtherFees = e.errorMessage;
        } else {
          this.showError = true;
          this.errorMessage = e.errorMessage;
        }
      });
    });
  }

  // Incase of the error, change the border from red to original
  inputOnFocus(id: string) {
    (document.getElementById(id) as HTMLElement).style.border = "";

    // Resetting error flags and error messages
    if (id === "sold-united-states-of-america-share-yahoo-code") {
      this.errorFlagYahooCode = false;
      this.errorMessageYahooCode = "";

      (document.getElementById("sold-united-states-of-america-share-script-name") as HTMLElement).style.border = "";
      this.errorFlagShareName = false;
      this.errorMessageShareName = "";
    } else if (id === "sold-united-states-of-america-share-sell-date") {
      this.errorFlagSellDate = false;
      this.errorMessageSellDate = "";
    } else if (id === "sold-united-states-of-america-share-sell-quantity") {
      this.errorFlagSellQuantity = false;
      this.errorMessageSellQuantity = "";
    }
    else if (id === "sold-united-states-of-america-share-sell-price") {
      this.errorFlagSellPrice = false;
      this.errorMessageSellPrice = "";
    }
    else if (id === "sold-united-states-of-america-share-sell-commission") {
      this.errorFlagSellCommission = false;
      this.errorMessageSellCommission = "";
    }
    else if (id === "sold-united-states-of-america-share-sell-transaction-fees") {
      this.errorFlagSellTransactionFees = false;
      this.errorMessageSellTransactionFees = "";
    }
    else if (id === "sold-united-states-of-america-share-sell-other-fees") {
      this.errorFlagSellOtherFees = false;
      this.errorMessageSellOtherFees = "";
    }
  }

  closeError() {
    this.showError = false;
    this.errorMessage = "";
  }

  closeSuccess() {
    this.showSuccess = false;
    this.successMessage = "";
    this.router.navigate(["/users/USA/EQ/sold"]);
  }
}

<div class="united-states-of-america-shares-add-sold">
  <div class="services-add-scripts-sold">
    <app-united-states-of-america-shares-add-shares-header
      (onBackButtonClicked)="onBackButtonClicked()"
    ></app-united-states-of-america-shares-add-shares-header>
    <div class="services-add-scipts-box">
      <h3 class="services-add-scipts-heading">
        Fill the details below
      </h3>
      <div class="services-add-scipts-form-container">
        <div class="services-add-scipts-form">
          <div class="key">Yahoo Code</div>
          <div class="value">
            <input
              type="text"
              id="sold-united-states-of-america-share-yahoo-code"
              placeholder="Yahoo Code"
              (focus)="inputOnFocus('sold-united-states-of-america-share-yahoo-code')"
              [(ngModel)]="yahooCode"
              (change)="getShareName()"
            />
            <app-input-field-error
              *ngIf="errorFlagYahooCode"
              [errorMessage]="errorMessageYahooCode"
            ></app-input-field-error>
          </div>
        </div>
        <div class="services-add-scipts-form">
          <div class="key">Share Name</div>
          <div class="value">
            <div id="sold-united-states-of-america-share-script-name" class="services-add-scipts-script-name">
              <label *ngIf="shareNameLoading;else shareNameTemplate">
                <app-money-manager-loading></app-money-manager-loading>
              </label>
              <ng-template #shareNameTemplate>
                <label>
                  {{ shareName }}
                </label>
              </ng-template>
            </div>
            <app-input-field-error
              *ngIf="errorFlagShareName"
              [errorMessage]="errorMessageShareName"
            ></app-input-field-error>
          </div>
        </div>
        <div class="services-add-scipts-form">
          <div class="key">Sell Date</div>
          <div class="value">
            <span id="sold-united-states-of-america-share-sell-date"></span>
            <app-money-manager-date-picker
              [resetDatePicker]="resetSellDatePicker"
              (onSelectedFullDate)="onSellDateSelect($event)"
            ></app-money-manager-date-picker>
            <app-input-field-error
              *ngIf="errorFlagSellDate"
              [errorMessage]="errorMessageSellDate"
            ></app-input-field-error>
          </div>
        </div>
        <div class="services-add-scipts-form">
          <div class="key">Sell Quantity</div>
          <div class="value">
            <input
              type="text"
              id="sold-united-states-of-america-share-sell-quantity"
              placeholder="Sell Quantity"
              (focus)="inputOnFocus('sold-united-states-of-america-share-sell-quantity')"
              [(ngModel)]="sellQuantity"
            />
            <app-input-field-error
              *ngIf="errorFlagSellQuantity"
              [errorMessage]="errorMessageSellQuantity"
            ></app-input-field-error>
          </div>
        </div>
        <div class="services-add-scipts-form">
          <div class="key">Sell Price</div>
          <div class="value">
            <input
              type="text"
              id="sold-united-states-of-america-share-sell-price"
              placeholder="Sell Price"
              (focus)="inputOnFocus('sold-united-states-of-america-share-sell-price')"
              [(ngModel)]="sellPrice"
            />
            <app-input-field-error
              *ngIf="errorFlagSellPrice"
              [errorMessage]="errorMessageSellPrice"
            ></app-input-field-error>
          </div>
        </div>
        <div class="services-add-scipts-form">
          <div class="key">Sell Commission</div>
          <div class="value">
            <input
              type="text"
              id="sold-united-states-of-america-share-sell-commission"
              placeholder="Sell Commission"
              (focus)="inputOnFocus('sold-united-states-of-america-share-sell-commission')"
              [(ngModel)]="sellCommission"
            />
            <app-input-field-error
              *ngIf="errorFlagSellCommission"
              [errorMessage]="errorMessageSellCommission"
            ></app-input-field-error>
          </div>
        </div>
        <div class="services-add-scipts-form">
          <div class="key">Sell Transaction Fees</div>
          <div class="value">
            <input
              type="text"
              id="sold-united-states-of-america-share-sell-transaction-fees"
              placeholder="Sell Transaction Fees"
              (focus)="inputOnFocus('sold-united-states-of-america-share-sell-transaction-fees')"
              [(ngModel)]="sellTransactionFees"
            />
            <app-input-field-error
              *ngIf="errorFlagSellTransactionFees"
              [errorMessage]="errorMessageSellTransactionFees"
            ></app-input-field-error>
          </div>
        </div>
        <div class="services-add-scipts-form">
          <div class="key">Sell Other Fees</div>
          <div class="value">
            <input
              type="text"
              id="sold-united-states-of-america-share-sell-other-fees"
              placeholder="Sell Other Fees"
              (focus)="inputOnFocus('sold-united-states-of-america-share-sell-other-fees')"
              [(ngModel)]="sellOtherFees"
            />
            <app-input-field-error
              *ngIf="errorFlagSellOtherFees"
              [errorMessage]="errorMessageSellOtherFees"
            ></app-input-field-error>
          </div>
        </div>
        <div class="services-add-scipts-form"></div>
        <div class="services-add-scipts-clear">
          <span>
            <app-money-manager-button
              [buttonTitle]="'Clear'"
              [buttonClass]="'btn-secondary'"
              (onButtonClick)="onUnitedStatesOfAmericaSharesAddSharesClear()"
            ></app-money-manager-button>
          </span>
          <div class="services-add-scipts-submit">
            <app-money-manager-button
              [buttonTitle]="'Submit'"
              [buttonClass]="'btn-primary'"
              (onButtonClick)="onUnitedStatesOfAmericaSharesAddSharesSubmit()"
            ></app-money-manager-button>
          </div>
        </div>
      </div>
    </div>
    <app-error-modal
      *ngIf="showError"
      (closeError)="closeError()"
    >
      <span body>
        {{ errorMessage }}
      </span>
    </app-error-modal>
  
    <app-success-modal
      *ngIf="showSuccess"
      (closeSuccess)="closeSuccess()"
    >
      <span body>
        {{ successMessage }}
      </span>
    </app-success-modal>
  </div>
</div>

// sarathi-vue-1.0/src/components/Users/USA/EQ/UnitedStatesOfAmericaSharesAddSold.vue
<template>
  <div class="united-states-of-america-shares-add-sold">
    <div class="services-add-scripts-sold">
      <UnitedStatesOfAmericaSharesAddSharesHeader
        @onBackButtonClicked="onBackButtonClicked()"
      ></UnitedStatesOfAmericaSharesAddSharesHeader>
      <div class="services-add-scipts-box">
        <h3 class="services-add-scipts-heading">
          Fill the details below
        </h3>
        <div class="services-add-scipts-form-container">
          <div class="services-add-scipts-form">
            <div class="key">Yahoo Code</div>
            <div class="value">
              <input
                type="text"
                id="sold-united-states-of-america-share-yahoo-code"
                placeholder="Yahoo Code"
                @focus="inputOnFocus('sold-united-states-of-america-share-yahoo-code')"
                v-model="yahooCode"
                @change="getShareName()"
              />
              <InputFieldError
                v-if="errorFlagYahooCode"
                :errorMessage="errorMessageYahooCode"
              ></InputFieldError>
            </div>
          </div>
          <div class="services-add-scipts-form">
            <div class="key">Share Name</div>
            <div class="value">
              <div id="sold-united-states-of-america-share-script-name" class="services-add-scipts-script-name">
                <template v-if="shareNameLoading">
                  <label>
                    <MoneyManagerLoading></MoneyManagerLoading>
                  </label>
                </template>
                <template v-else>
                  <label>
                    {{ shareName }}
                  </label>
                </template>
              </div>
              <InputFieldError
                v-if="errorFlagShareName"
                :errorMessage="errorMessageShareName"
              ></InputFieldError>
            </div>
          </div>
          <div class="services-add-scipts-form">
            <div class="key">Sell Date</div>
            <div class="value">
              <span id="sold-united-states-of-america-share-sell-date"></span>
              <MoneyManagerDatePicker
                :resetDatePicker="resetSellDatePicker"
                @onSelectedFullDate="onSellDateSelect($event)"
              ></MoneyManagerDatePicker>
              <InputFieldError
                v-if="errorFlagSellDate"
                :errorMessage="errorMessageSellDate"
              ></InputFieldError>
            </div>
          </div>
          <div class="services-add-scipts-form">
            <div class="key">Sell Quantity</div>
            <div class="value">
              <input
                type="text"
                id="sold-united-states-of-america-share-sell-quantity"
                placeholder="Sell Quantity"
                @focus="inputOnFocus('sold-united-states-of-america-share-sell-quantity')"
                v-model="sellQuantity"
              />
              <InputFieldError
                v-if="errorFlagSellQuantity"
                :errorMessage="errorMessageSellQuantity"
              ></InputFieldError>
            </div>
          </div>
          <div class="services-add-scipts-form">
            <div class="key">Sell Price</div>
            <div class="value">
              <input
                type="text"
                id="sold-united-states-of-america-share-sell-price"
                placeholder="Sell Price"
                @focus="inputOnFocus('sold-united-states-of-america-share-sell-price')"
                v-model="sellPrice"
              />
              <InputFieldError
                v-if="errorFlagSellPrice"
                :errorMessage="errorMessageSellPrice"
              ></InputFieldError>
            </div>
          </div>
          <div class="services-add-scipts-form">
            <div class="key">Sell Commission</div>
            <div class="value">
              <input
                type="text"
                id="sold-united-states-of-america-share-sell-commission"
                placeholder="Sell Commission"
                @focus="inputOnFocus('sold-united-states-of-america-share-sell-commission')"
                v-model="sellCommission"
              />
              <InputFieldError
                v-if="errorFlagSellCommission"
                :errorMessage="errorMessageSellCommission"
              ></InputFieldError>
            </div>
          </div>
          <div class="services-add-scipts-form">
            <div class="key">Sell Transaction Fees</div>
            <div class="value">
              <input
                type="text"
                id="sold-united-states-of-america-share-sell-transaction-fees"
                placeholder="Sell Transaction Fees"
                @focus="inputOnFocus('sold-united-states-of-america-share-sell-transaction-fees')"
                v-model="sellTransactionFees"
              />
              <InputFieldError
                v-if="errorFlagSellTransactionFees"
                :errorMessage="errorMessageSellTransactionFees"
              ></InputFieldError>
            </div>
          </div>
          <div class="services-add-scipts-form">
            <div class="key">Sell Other Fees</div>
            <div class="value">
              <input
                type="text"
                id="sold-united-states-of-america-share-sell-other-fees"
                placeholder="Sell Other Fees"
                @focus="inputOnFocus('sold-united-states-of-america-share-sell-other-fees')"
                v-model="sellOtherFees"
              />
              <InputFieldError
                v-if="errorFlagSellOtherFees"
                :errorMessage="errorMessageSellOtherFees"
              ></InputFieldError>
            </div>
          </div>
          <div class="services-add-scipts-form"></div>
          <div class="services-add-scipts-clear">
            <span>
              <MoneyManagerButton
                :buttonTitle="'Clear'"
                :buttonClass="'btn-secondary'"
                @onButtonClick="onUnitedStatesOfAmericaSharesAddSharesClear()"
              ></MoneyManagerButton>
            </span>
            <div class="services-add-scipts-submit">
              <MoneyManagerButton
                :buttonTitle="'Submit'"
                :buttonClass="'btn-primary'"
                @onButtonClick="onUnitedStatesOfAmericaSharesAddSharesSubmit()"
              ></MoneyManagerButton>
            </div>
          </div>
        </div>
      </div>
      <ErrorModal
        v-if="showError"
        :errorMessage="errorMessage"
      >
        <template v-slot:header>
          <h3 class="mm-error-modal-title">Error!!</h3>
          <span>
            <MoneyManagerButton
              :buttonClass="'btn-close'"
              @onButtonClick="closeError()"
            >
            </MoneyManagerButton>
          </span>
        </template>
      </ErrorModal>

      <SuccessModal v-if="showSuccess" :successMessage="successMessage">
        <template v-slot:header>
          <h3 class="mm-success-modal-title">Success!!</h3>
          <span>
            <MoneyManagerButton
              :buttonClass="'btn-close'"
              @onButtonClick="closeSuccess()"
            >
            </MoneyManagerButton>
          </span>
        </template>
      </SuccessModal>
    </div>
  </div>
</template>

<script>
import UnitedStatesOfAmericaSharesAddSharesHeader from "@/components/Users/USA/EQ/BoughtSold/UnitedStatesOfAmericaSharesAddSharesHeader.vue";
import MoneyManagerButton from "@/components/common/MoneyManagerButton.vue";
import InputFieldError from "@/components/common/InputFieldError";
import MoneyManagerDatePicker from "@/components/common/MoneyManagerDatePicker.vue";
import MoneyManagerLoading from "@/components/common/MoneyManagerLoading.vue";
import ErrorModal from "@/components/common/ErrorModal.vue";
import SuccessModal from "@/components/common/SuccessModal.vue";
import services from "@/assets/services/services.json";
import axios from 'axios';
import { getDefaultDate } from "@/common/utils/utils.js";

export default {
  components: {
    UnitedStatesOfAmericaSharesAddSharesHeader,
    MoneyManagerButton,
    InputFieldError,
    MoneyManagerDatePicker,
    MoneyManagerLoading,
    ErrorModal,
    SuccessModal
  },

  data() {
    return {
      yahooCode: "",
      shareName: "",
      shareNameLoading: false,
      sellDate: "",
      resetSellDatePicker: false,
      sellQuantity: "",
      sellPrice: "",
      sellCommission: "",
      sellTransactionFees: "",
      sellOtherFees: "",

      // Error field flags
      errorFlagYahooCode: false,
      errorFlagShareName: false,
      errorFlagSellDate: false,
      errorFlagSellQuantity: false,
      errorFlagSellPrice: false,
      errorFlagSellCommission: false,
      errorFlagSellTransactionFees: false,
      errorFlagSellOtherFees: false,

      // Error field messages
      errorMessageYahooCode: "",
      errorMessageShareName: "",
      errorMessageSellDate: "",
      errorMessageSellQuantity: "",
      errorMessageSellPrice: "",
      errorMessageSellCommission: "",
      errorMessageSellTransactionFees: "",
      errorMessageSellOtherFees: "",

      // Error/Success Modal
      showError: false,
      errorMessage: "",
      showSuccess: false,
      successMessage: ""
    }
  },

  methods: {
    onBackButtonClicked() {
      this.$router.push("/users/USA/EQ/sold");
    },

    onSellDateSelect(selectedSellDate) {
      this.resetSellDatePicker = false;
      this.inputOnFocus('sold-united-states-of-america-share-sell-date');
      this.sellDate = selectedSellDate;
    },

    getShareName() {
      this.shareNameLoading = true;

      axios.get(services.unitedStatesOfAmericaShareNameDetails + "?scriptCode=" + this.yahooCode).then(response => {
        if (response.status === 204) {
          this.shareName = "";
          this.shareNameLoading = false;
        } else {
          this.shareName = response.data.scriptName;
          this.shareNameLoading = false;
        }
      }).catch(error => {
        error.response.data.error.map((e) => {
          this.errorMessage = e.errorMessage;
          this.showError = true;
        });
      });
    },

    onUnitedStatesOfAmericaSharesAddSharesClear() {

      // In case of error, change input border color
      document.getElementById("sold-united-states-of-america-share-yahoo-code").style.border = "";
      document.getElementById("sold-united-states-of-america-share-script-name").style.border = "0.1rem solid black";
      document.getElementById("sold-united-states-of-america-share-sell-quantity").style.border = "";
      document.getElementById("sold-united-states-of-america-share-sell-price").style.border = "";
      document.getElementById("sold-united-states-of-america-share-sell-commission").style.border = "";
      document.getElementById("sold-united-states-of-america-share-sell-transaction-fees").style.border = "";
      document.getElementById("sold-united-states-of-america-share-sell-other-fees").style.border = "";

      this.yahooCode = "";
      this.shareName = "";
      this.sellQuantity = "";
      this.sellPrice = "";
      this.sellCommission = "";
      this.sellTransactionFees = "";
      this.sellOtherFees = "";
      this.sellDate = getDefaultDate("");
      this.resetSellDatePicker = true;

      // Error field flags
      this.errorFlagYahooCode = false;
      this.errorFlagShareName = false;
      this.errorFlagSellDate = false;
      this.errorFlagSellQuantity = false;
      this.errorFlagSellPrice = false;
      this.errorFlagSellCommission = false;
      this.errorFlagSellTransactionFees = false;
      this.errorFlagSellOtherFees = false;

      // Error field messages
      this.errorMessageYahooCode = "";
      this.errorMessageShareName = "";
      this.errorMessageSellDate = "";
      this.errorMessageSellQuantity = "";
      this.errorMessageSellPrice = "";
      this.errorMessageSellCommission = "";
      this.errorMessageSellTransactionFees = "";
      this.errorMessageSellOtherFees = "";
    },

    onUnitedStatesOfAmericaSharesAddSharesSubmit() {
      const formData = {
        yahooCode: this.yahooCode,
        scriptName: this.shareName,
        sellDate: this.sellDate,
        sellQuantity: this.sellQuantity,
        sellPrice: this.sellPrice,
        sellCommission: this.sellCommission,
        sellTransactionFees: this.sellTransactionFees,
        sellOtherFees: this.sellOtherFees
      };

      axios.post(services.unitedStatesOfAmericaSharesShares + "?type=sold", formData).then(response => {

        this.successMessage = response.data.message;
        this.showSuccess = true;

        this.sellQuantity = "";
        this.sellPrice = "";
        this.sellCommission = "";
        this.sellTransactionFees = "";
        this.sellOtherFees = "";
        this.sellDate = getDefaultDate("");
        this.resetSellDatePicker = true;

      }).catch(error => {

        // For displaying errors
        error.response.data.error.map(e => {
          if (e.uiField === "sold-united-states-of-america-share-yahoo-code") {
            document.getElementById(e.uiField).style.border = "0.1rem solid red";
            this.errorFlagYahooCode = true;
            this.errorMessageYahooCode = e.errorMessage;
          } else if (e.uiField === "sold-united-states-of-america-share-script-name") {
            document.getElementById(e.uiField).style.border = "0.1rem solid red";
            this.errorFlagShareName = true;
            this.errorMessageShareName = e.errorMessage;
          } else if (e.uiField === "sold-united-states-of-america-share-sell-date") {
            this.errorFlagSellDate = true;
            this.errorMessageSellDate = e.errorMessage;
          } else if (e.uiField === "sold-united-states-of-america-share-sell-quantity") {
            document.getElementById(e.uiField).style.border = "0.1rem solid red";
            this.errorFlagSellQuantity = true;
            this.errorMessageSellQuantity = e.errorMessage;
          } else if (e.uiField === "sold-united-states-of-america-share-sell-price") {
            document.getElementById(e.uiField).style.border = "0.1rem solid red";
            this.errorFlagSellPrice = true;
            this.errorMessageSellPrice = e.errorMessage;
          } else if (e.uiField === "sold-united-states-of-america-share-sell-commission") {
            document.getElementById(e.uiField).style.border = "0.1rem solid red";
            this.errorFlagSellCommission = true;
            this.errorMessageSellCommission = e.errorMessage;
          } else if (e.uiField === "sold-united-states-of-america-share-sell-transaction-fees") {
            document.getElementById(e.uiField).style.border = "0.1rem solid red";
            this.errorFlagSellTransactionFees = true;
            this.errorMessageSellTransactionFees = e.errorMessage;
          } else if (e.uiField === "sold-united-states-of-america-share-sell-other-fees") {
            document.getElementById(e.uiField).style.border = "0.1rem solid red";
            this.errorFlagSellOtherFees = true;
            this.errorMessageSellOtherFees = e.errorMessage;
          } else {
            this.showError = true;
            this.errorMessage = e.errorMessage;
          }
        });
      });
    },

    // Incase of the error, change the border from red to original
    inputOnFocus(id) {
      document.getElementById(id).style.border = "";

      // Resetting error flags and error messages
      if (id === "sold-united-states-of-america-share-yahoo-code") {
        this.errorFlagYahooCode = false;
        this.errorMessageYahooCode = "";

        document.getElementById("sold-united-states-of-america-share-script-name").style = "0.1rem solid black";
        this.errorFlagShareName = false;
        this.errorMessageShareName = "";
      } else if (id === "sold-united-states-of-america-share-sell-date") {
        this.errorFlagSellDate = false;
        this.errorMessageSellDate = "";
      } else if (id === "sold-united-states-of-america-share-sell-quantity") {
        this.errorFlagSellQuantity = false;
        this.errorMessageSellQuantity = "";
      }
      else if (id === "sold-united-states-of-america-share-sell-price") {
        this.errorFlagSellPrice = false;
        this.errorMessageSellPrice = "";
      }
      else if (id === "sold-united-states-of-america-share-sell-commission") {
        this.errorFlagSellCommission = false;
        this.errorMessageSellCommission = "";
      }
      else if (id === "sold-united-states-of-america-share-sell-transaction-fees") {
        this.errorFlagSellTransactionFees = false;
        this.errorMessageSellTransactionFees = "";
      }
      else if (id === "sold-united-states-of-america-share-sell-other-fees") {
        this.errorFlagSellOtherFees = false;
        this.errorMessageSellOtherFees = "";
      }
    },

    closeError() {
      this.showError = false;
      this.errorMessage = "";
    },

    closeSuccess() {
      this.showSuccess = false;
      this.successMessage = "";
      this.$router.push("/users/USA/EQ/sold");
    }
  }
}
</script>
