// sarathi-ang-1.0/src/app/components/users/users/users.component.ts
import { Component, OnInit } from '@angular/core';
import { UserDetailsStoreService } from 'src/app/common/store/user-details/user-details-store.service';
import { LocalStorageService } from 'src/app/common/services/local-storage/local-storage.service';

@Component({
  selector: 'app-users',
  templateUrl: './users.component.html',
  styleUrls: ['./users.component.css']
})
export class UsersComponent implements OnInit {

  constructor(
    private userDetailsStoreService: UserDetailsStoreService,
    private localStorageService: LocalStorageService
  ) { }

  timer: any = null;
  tokenGeneratedTime: number = 0;
  accessTokenExpiresIn: number = 0;
  refreshTokenExpiresIn: number = 0;
  accessTokenTimer: number = 0;
  refreshTokenTimer: number = 0;
  refreshPopUpDisplayed: boolean = true;
  showRefreshToken: boolean = false;

  ngOnInit(): void {
    this.tokenTimer();
  }

  tokenTimer() {
    this.refreshPopUpDisplayed = true;

    this.tokenGeneratedTime = parseInt(this.userDetailsStoreService.getTokenDetails().tokenGeneratedTime);
    this.accessTokenExpiresIn = parseInt(this.userDetailsStoreService.getTokenDetails().accessTokenExpiresIn);
    this.refreshTokenExpiresIn = parseInt(this.userDetailsStoreService.getTokenDetails().refreshTokenExpiresIn);

    this.accessTokenTimer = parseInt(this.userDetailsStoreService.getTokenDetails().accessTokenExpiresIn);
      this.refreshTokenTimer = parseInt(this.userDetailsStoreService.getTokenDetails().refreshTokenExpiresIn);

    this.localStorageService.timer = setInterval(() => {
      // Token timer
      if (new Date().getTime() >= (this.tokenGeneratedTime + (this.accessTokenExpiresIn * 1000))) {
        clearInterval(this.timer);
        localStorage.removeItem("refreshTokenTimer");
        localStorage.removeItem("accessTokenTimer");
      } else {
        this.accessTokenTimer--;
        localStorage.removeItem("accessTokenTimer");
        localStorage.setItem("accessTokenTimer", this.accessTokenTimer.toString());
        // Check refresh token timer
        if (new Date().getTime() >= (this.tokenGeneratedTime + (this.refreshTokenExpiresIn * 1000)) && this.refreshPopUpDisplayed) {
          this.refreshPopUpDisplayed = false;
          this.showRefreshToken = true;
          localStorage.removeItem("refreshTokenTimer");
        } else if (this.refreshPopUpDisplayed) {
          this.refreshTokenTimer--;
          localStorage.removeItem("refreshTokenTimer");
          localStorage.setItem("refreshTokenTimer", this.refreshTokenTimer.toString());
        }
      }
    }, 1000);
  }

  onCloseRefreshToken() {
    this.showRefreshToken = false;
  }

  onContinueRefreshToken() {
    this.showRefreshToken = false;
    localStorage.removeItem("refreshTokenTimer");
    localStorage.removeItem("accessTokenTimer");
    this.tokenTimer();
  }
}

<div>
  <app-users-header></app-users-header>
  <app-refresh-token
    *ngIf="showRefreshToken"
    (onCloseRefreshToken)="onCloseRefreshToken()"
    (onContinueRefreshToken)="onContinueRefreshToken()"
  ></app-refresh-token>
  <router-outlet></router-outlet>
</div>

// sarathi-vue-1.0/src/components/Users/Users.vue
<template>
  <UsersHeader></UsersHeader>
  <RefreshToken
    v-if="showRefreshToken"
    @onCloseRefreshToken="onCloseRefreshToken()"
    @onContinueRefreshToken="onContinueRefreshToken()"
  ></RefreshToken>
  <router-view></router-view>
</template>

<script>
import UsersHeader from "@/components/Users/UsersHeader.vue";
import RefreshToken from "@/components/Users/RefreshToken/RefreshToken.vue";
import localStorageObj from "@/common/utils/local-storage";

export default {
  name: "Users",
  components: {
    UsersHeader,
    RefreshToken
  },
  data() {
    return {
      timer: null,
      tokenGeneratedTime: 0,
      accessTokenExpiresIn: 0,
      refreshTokenExpiresIn: 0,
      accessTokenTimer: 0,
      refreshTokenTimer: 0,
      refreshPopUpDisplayed: true,
      showRefreshToken: false
    };
  },

  created() {
    this.tokenTimer()
  },

  methods: {
    tokenTimer() {
      this.refreshPopUpDisplayed = true;

      this.tokenGeneratedTime = parseInt(
        this.$store.getters["userDetails/GET_TOKEN_DETAILS"].tokenGeneratedTime
      );
      this.accessTokenExpiresIn = parseInt(
        this.$store.getters["userDetails/GET_TOKEN_DETAILS"].accessTokenExpiresIn
      );
      this.refreshTokenExpiresIn = parseInt(
        this.$store.getters["userDetails/GET_TOKEN_DETAILS"].refreshTokenExpiresIn
      );

      this.accessTokenTimer = parseInt(
        this.$store.getters["userDetails/GET_TOKEN_DETAILS"].accessTokenExpiresIn
      );
      this.refreshTokenTimer = parseInt(
        this.$store.getters["userDetails/GET_TOKEN_DETAILS"].refreshTokenExpiresIn
      );

      // this.timer = setInterval(() => {
      localStorageObj.localStorageTimer = setInterval(() => {
        // Token timer
        if (
          new Date().getTime() >=
          this.tokenGeneratedTime + this.accessTokenExpiresIn * 1000
        ) {
          clearInterval(localStorageObj.localStorageTimer);
          localStorage.removeItem("refreshTokenTimer");
          localStorage.removeItem("accessTokenTimer");

        } else {
          this.accessTokenTimer--;
          localStorage.removeItem("accessTokenTimer");
          localStorage.setItem("accessTokenTimer", this.accessTokenTimer);
          // Check refresh token timer
          if (
            new Date().getTime() >=
              this.tokenGeneratedTime + this.refreshTokenExpiresIn * 1000 &&
            this.refreshPopUpDisplayed
          ) {
            this.refreshPopUpDisplayed = false;
            this.showRefreshToken = true;
            localStorage.removeItem("refreshTokenTimer");
          } else if (this.refreshPopUpDisplayed) {
            this.refreshTokenTimer--;
            localStorage.removeItem("refreshTokenTimer");
            localStorage.setItem("refreshTokenTimer", this.refreshTokenTimer);
          }
        }
      }, 1000);
    },

    onCloseRefreshToken() {
      this.showRefreshToken = false;
    },

    onContinueRefreshToken() {
      this.showRefreshToken = false;
      clearInterval(localStorageObj.localStorageTimer);
      localStorage.removeItem("refreshTokenTimer");
      localStorage.removeItem("accessTokenTimer");
      this.tokenTimer();
    }
  }
};
</script>
