// sarathi-ang-1.0/src/app/components/users/users-header/users-header.component.ts
import { KeyValue } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { LogoutStoreService } from 'src/app/common/store/logout/logout-store.service';
import { PreDataStoreService } from 'src/app/common/store/pre-data/pre-data-store.service';
import { UserDetailsStoreService } from 'src/app/common/store/user-details/user-details-store.service';
import services from 'src/assets/services/services.json';

@Component({
  selector: 'app-users-header',
  templateUrl: './users-header.component.html',
  styleUrls: ['./users-header.component.css']
})
export class UsersHeaderComponent implements OnInit {

  homeRouterActive: boolean = false;
  servicesRouterActiveMap: Map<string, boolean> = new Map();
  showUserServicesMap: Map<string, boolean> = new Map();
  showUserSubServicesMap: Map<string, boolean> = new Map();
  showUserDropdownInfo: boolean = false;
  userName: string = "";
  userSubServicesList: Array<any> = [];
  userOptedCountryIdsList: Array<any> = [];
  userOptedServiceIdsByCountryMap: Map<string, any> = new Map();
  countryDetailsMap: Map<string, any> = new Map();
  servicesOfferedDetailsMap: Map<string, any> = new Map();
  userSubServicesObject: any = {};
  showUserSubServices: boolean = false;

  constructor(
    private userDetailsStoreService: UserDetailsStoreService,
    private preDataStoreService: PreDataStoreService,
    private logoutStoreService: LogoutStoreService,
    private router: Router,
    private http: HttpClient
  ) { }

  ngOnInit(): void {
    this.userName = this.userDetailsStoreService.getUserDetails().preferredName ? this.userDetailsStoreService.getUserDetails().preferredName : this.userDetailsStoreService.getUserDetails().firstName + " " + this.userDetailsStoreService.getUserDetails().lastName;

    for (let userOptedService of this.userDetailsStoreService.getUserDetails().userOptedServicesList) {
      this.userOptedServiceIdsByCountryMap.set(userOptedService.countryId, userOptedService);
    }

    this.userOptedCountryIdsList = this.userDetailsStoreService.getUserDetails().userOptedCountryIdsList;
    this.countryDetailsMap = this.preDataStoreService.getCountryDetailsMap();
    this.servicesOfferedDetailsMap = this.preDataStoreService.getServicesOfferedDetailsMap();

    for (let [key] of this.countryDetailsMap) {
      this.servicesRouterActiveMap.set(key, false);
      this.showUserServicesMap.set(key, false);
    }

    this.homeRouterActive = true;
    this.router.navigate(["/users/home"]);
  }

  // Preserve original property order
  originalOrder = (a: KeyValue<string, any>, b: KeyValue<string, any>): number => {
    return 0;
  }

  onUsersHomeClick() {
    this.activeRouter("homeRouter");
    this.router.navigate(["/users/home"]);
  }

  onUsersServicesClick(country: any) {
    this.showUserSubServices = false;
    this.showUserSubServicesMap = new Map();
    for (let [key, value] of this.showUserServicesMap) {
      if (key === country.countryId) {
        this.showUserServicesMap.set(key, !value);
        if (!this.showUserServicesMap.get(key)) {
          this.userSubServicesObject = {};
        }
      } else {
        this.showUserServicesMap.set(key, false);
      }
    }
  }

  activeRouter(selectedRouter: string) {
    if (selectedRouter === "homeRouter") {
      for (let [key] of this.servicesRouterActiveMap) {
        this.servicesRouterActiveMap.set(key, false);;
      }
      for (let [key] of this.showUserServicesMap) {
        this.showUserServicesMap.set(key, false);
      }
      this.userSubServicesObject = {};
      this.showUserSubServices = false;
      this.homeRouterActive = true;
    } else {
      this.homeRouterActive = false;
      for (let [key] of this.servicesRouterActiveMap) {
        if (key === selectedRouter) {
          this.servicesRouterActiveMap.set(key, true);
        } else {
          this.servicesRouterActiveMap.set(key, false);
        }
      }
    }
  }

  onUserDropdownInfoBlur() {
    this.showUserDropdownInfo = false;
  }

  onUserDropdownInfoClick() {
    this.showUserDropdownInfo = !this.showUserDropdownInfo;
    for (let [key] of this.showUserServicesMap) {
      this.showUserServicesMap.set(key, false);
    }
    this.userSubServicesObject = {};
    this.showUserSubServices = false;
    this.showUserSubServicesMap = new Map();
  }

  onUserProfileClick() {
    this.showUserDropdownInfo = false;
    this.homeRouterActive = false;
    this.router.navigate(["/users/profile"]);
  }

  onUserLogoutClick() {
    this.showUserDropdownInfo = false;
    this.http.get<any>(services.logout, {}).subscribe(response => {}, error => {});
    this.logoutStoreService.clearStoreAndLogout();
  }

  onServiceSelectClick(countryId: string, serviceCode: string) {
    this.showUserSubServicesMap = new Map();

    if ("home" === serviceCode) {
      let countryCode: string = this.preDataStoreService.getCountryDetailsMap().get(countryId).countryCode;
      this.router.navigate(["/users/" + countryCode + "/" + serviceCode.toLowerCase()]);
      this.activeRouter(this.countryDetailsMap.get(countryId).countryId);

      for (let [key, value] of this.showUserServicesMap) {
        if (value === true) {
          this.showUserServicesMap.set(key, false);
        }
      }

      this.userSubServicesObject = {};
      this.showUserSubServices = false;
      this.showUserSubServicesMap = new Map();
      return;
    }

    let userSubServicesList: Array<any> = [];
    this.preDataStoreService.getSubServicesByServiceCodeDetailsMap().get(serviceCode).subServicesDetailsList.forEach((subServicesDetail: string) => {
      userSubServicesList.push(this.preDataStoreService.getSubServicesDetailsMap().get(subServicesDetail));
    });

    if (this.userSubServicesObject.countryId === this.preDataStoreService.getCountryDetailsMap().get(countryId).countryId && this.userSubServicesObject.serviceCode === serviceCode) {
      this.userSubServicesObject = {};
      this.showUserSubServices = false;
      this.showUserSubServicesMap = new Map();
      return;
    }

    this.userSubServicesObject = {
      countryId: this.preDataStoreService.getCountryDetailsMap().get(countryId).countryId,
      countryCode: this.preDataStoreService.getCountryDetailsMap().get(countryId).countryCode,
      serviceCode: serviceCode,
      userSubServicesList: userSubServicesList
    };

    this.showUserSubServicesMap.set(serviceCode, true);
    this.showUserSubServices = true;
  }

  onSubServiceSelectClick(countryId: string, countryCode: string, serviceCode: string, subServiceName: string) { 

    this.userSubServicesObject = {};
    this.showUserSubServices = false;
    this.showUserSubServicesMap = new Map();
    for (let [key] of this.countryDetailsMap) {
      this.servicesRouterActiveMap.set(key, false);
      this.showUserServicesMap.set(key, false);
    }
    this.activeRouter(countryId);
    this.router.navigate(["/users/" + countryCode + "/" + serviceCode + "/" + subServiceName.toLowerCase()]);
  }
}

<div class="mm-users-header">
  <div class="mm-users-header-container">
    <div class="users-nav">
      <div
        (click)="onUsersHomeClick()"
      >
        <div
          *ngIf="homeRouterActive; else elseHomeRouterActiveDesktop"
          class="router active"
        >
          Home
        </div>
        <div>
          <ng-template #elseHomeRouterActiveDesktop>
            <div class="router">
              Home
            </div>
          </ng-template>
        </div>
      </div>

      <div
        *ngFor="let countryDetails of countryDetailsMap | keyvalue: originalOrder"
        (click)="onUsersServicesClick(countryDetails.value)"
      >
        <div
          *ngIf="servicesRouterActiveMap.get(countryDetails.value.countryId); else elseServicesRouterActiveDesktop"
          class="router active"
        >
          {{ countryDetails.value.countryCode }}
          <span class="arrow">
            <span *ngIf="showUserServicesMap.get(countryDetails.value.countryId)" class="arrow-up"></span>
            <span *ngIf="!showUserServicesMap.get(countryDetails.value.countryId)" class="arrow-down"></span>
          </span>
        </div>
        <div>
          <ng-template #elseServicesRouterActiveDesktop>
            <div class="router">
              {{ countryDetails.value.countryCode }}
              <span class="arrow">
                <span *ngIf="showUserServicesMap.get(countryDetails.value.countryId)" class="arrow-up"></span>
                <span *ngIf="!showUserServicesMap.get(countryDetails.value.countryId)" class="arrow-down"></span>
              </span>
            </div>
          </ng-template>
        </div>
      </div>

      <div
        class="user-nav-right"
        [tabindex]="0"
        (blur)="onUserDropdownInfoBlur()"
      >
        <div>
          <span
            class="user-dropdown"
            (click)="onUserDropdownInfoClick()"
          >
            {{ userName }}
            <span class="arrow">
              <span *ngIf="showUserDropdownInfo" class="arrow-up"></span>
              <span *ngIf="!showUserDropdownInfo" class="arrow-down"></span>
            </span>
          </span>
        </div>
        <div *ngIf="showUserDropdownInfo" class="user-services-dropdown-info">
          <div
            class="user-dropdown-router"
            (click)="onUserProfileClick()"
          >
            Profile
          </div>
          <div
            class="user-dropdown-router"
            (click)="onUserLogoutClick()"
          >
            Logout
          </div>
        </div>
      </div>
    </div>

    <div
      *ngFor="let showUserServices of showUserServicesMap | keyvalue: originalOrder" :key="key"
      class="user-services-nav"
    >
      <div *ngIf="showUserServices.value">
        <div
          *ngIf="showUserServicesMap.get(showUserServices.key)"
        >
          <div
            (click)="onServiceSelectClick(countryDetailsMap.get(showUserServices.key).countryId, 'home')"
            class="router"
          >
            Home
          </div>
          <div
            *ngFor="let userOptedServiceIdByCountry of userOptedServiceIdsByCountryMap.get(showUserServices.key).userOptedServiceIdsList"
            (click)="onServiceSelectClick(countryDetailsMap.get(showUserServices.key).countryId, servicesOfferedDetailsMap.get(userOptedServiceIdByCountry).serviceCode)"
          >
            <div
              class="router"
            >
              {{ servicesOfferedDetailsMap.get(userOptedServiceIdByCountry).serviceName }}
              <span class="arrow">
                <span *ngIf="showUserSubServicesMap.get(servicesOfferedDetailsMap.get(userOptedServiceIdByCountry).serviceCode)" class="arrow-up"></span>
                <span *ngIf="!showUserSubServicesMap.get(servicesOfferedDetailsMap.get(userOptedServiceIdByCountry).serviceCode)" class="arrow-down"></span>
            </span>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div
      *ngIf="showUserSubServices"
      class="user-services-nav"
    >
      <div
        *ngFor="let userSubServices of userSubServicesObject.userSubServicesList"
      >
        <div
          (click)="onSubServiceSelectClick(userSubServicesObject.countryId, userSubServicesObject.countryCode, userSubServicesObject.serviceCode, userSubServices.subServiceName)"
          class="router"
        >
          {{ userSubServices.subServiceName }}
        </div>
      </div>
    </div>
  </div>
</div>

// sarathi-vue-1.0/src/components/Users/UsersHeader.vue
<template>
  <div class="mm-users-header">
    <div class="mm-users-header-container">
      <div class="users-nav">
        <div
          @click="onUsersHomeClick()"
        >
          <div
            v-if="homeRouterActive"
            class="router active"
          >
            Home
          </div>
          <div
            v-else
            class="router"
          >
            Home
          </div>
        </div>

        <div
          v-for="[key, value] of countryDetailsMap" :key="key"
          @click="onUsersServicesClick(value)"
        >
          <div
            v-if="servicesRouterActiveMap.get(value.countryId)"
            class="router active"
          >
            {{ value.countryCode }}
            <span class="arrow">
              <span v-if="showUserServicesMap.get(value.countryId)" class="arrow-up"></span>
              <span v-if="!showUserServicesMap.get(value.countryId)" class="arrow-down"></span>
            </span>
          </div>
          <div
            v-else
            class="router"
          >
            {{ value.countryCode }}
            <span class="arrow">
              <span v-if="showUserServicesMap.get(value.countryId)" class="arrow-up"></span>
              <span v-if="!showUserServicesMap.get(value.countryId)" class="arrow-down"></span>
            </span>
          </div>
        </div>

        <div
          class="user-nav-right"
          :tabindex="0"
          @blur="onUserDropdownInfoBlur()"
        >
          <div>
            <span
              class="user-dropdown"
              @click="onUserDropdownInfoClick()"
            >
              {{ userName }}
              <span class="arrow">
                <span v-if="showUserDropdownInfo" class="arrow-up"></span>
                <span v-if="!showUserDropdownInfo" class="arrow-down"></span>
              </span>
            </span>
          </div>
          <div v-if="showUserDropdownInfo" class="user-services-dropdown-info">
            <div
              class="user-dropdown-router"
              @click="onUserProfileClick()"
            >
              Profile
            </div>
            <div
              class="user-dropdown-router"
              @click="onUserLogoutClick()"
            >
              Logout
            </div>
          </div>
        </div>
      </div>

      <div
        v-for="[key, value] of showUserServicesMap" :key="key"
        class="user-services-nav"
      >
        <div v-if="value">
          <div
            v-if="showUserServicesMap.get(key)"
          >
            <div
              @click="onServiceSelectClick(countryDetailsMap.get(key).countryId, 'home')"
              class="router"
            >
              Home
            </div>
            <div
              v-for="userOptedServiceIdByCountry of userOptedServiceIdsByCountryMap.get(key).userOptedServiceIdsList"
              :key="userOptedServiceIdByCountry"
              @click="onServiceSelectClick(countryDetailsMap.get(key).countryId, servicesOfferedDetailsMap.get(userOptedServiceIdByCountry).serviceCode)"
            >
              <div
                class="router"
              >
                {{ servicesOfferedDetailsMap.get(userOptedServiceIdByCountry).serviceName }}
                <span class="arrow">
                  <span v-if="showUserSubServicesMap.get(servicesOfferedDetailsMap.get(userOptedServiceIdByCountry).serviceCode)" class="arrow-up"></span>
                  <span v-if="!showUserSubServicesMap.get(servicesOfferedDetailsMap.get(userOptedServiceIdByCountry).serviceCode)" class="arrow-down"></span>
              </span>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div
        v-if="showUserSubServices"
        class="user-services-nav"
      >
        <div
          v-for="userSubServices of userSubServicesObject.userSubServicesList"
          :key="userSubServices.subServiceId"
        >
          <div
            @click="onSubServiceSelectClick(userSubServicesObject.countryId, userSubServicesObject.countryCode, userSubServicesObject.serviceCode, userSubServices.subServiceName)"
            class="router"
          >
            {{ userSubServices.subServiceName }}
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import axios from "axios";
import services from "@/assets/services/services.json";

export default {
  name: "UsersHeader",

  data() {
    return {
      homeRouterActive: false,
      servicesRouterActiveMap: new Map(),
      showUserServicesMap: new Map(),
      showUserSubServicesMap: new Map(),
      showUserDropdownInfo: false,
      userName: "",
      userSubServicesList: [],
      userOptedCountryIdsList: [],
      userOptedServiceIdsByCountryMap: new Map(),
      countryDetailsMap: new Map(),
      servicesOfferedDetailsMap: new Map(),
      userSubServicesObject: {},
      showUserSubServices: false
    }
  },

  created() {
    this.userName = this.$store.getters["userDetails/GET_USER_DETAILS"].preferredName
      ? this.$store.getters["userDetails/GET_USER_DETAILS"].preferredName
      : this.$store.getters["userDetails/GET_USER_DETAILS"].firstName +
        " " +
        this.$store.getters["userDetails/GET_USER_DETAILS"].lastName;

    for (let userOptedService of this.$store.getters["userDetails/GET_USER_DETAILS"].userOptedServicesList) {
      this.userOptedServiceIdsByCountryMap.set(userOptedService.countryId, userOptedService);
    }

    this.userOptedCountryIdsList = this.$store.getters["userDetails/GET_USER_DETAILS"].userOptedCountryIdsList;
    this.countryDetailsMap = this.$store.getters["preData/GET_COUNTRY_DETAILS_MAP"];
    this.servicesOfferedDetailsMap = this.$store.getters["preData/GET_SERVICES_OFFERED_DETAILS_MAP"];

    for (let [key] of this.countryDetailsMap) {
      this.servicesRouterActiveMap.set(key, false);
      this.showUserServicesMap.set(key, false);
    }

    this.homeRouterActive = true;
    this.$router.push("/users/home");
  },

  methods: {
    onUsersHomeClick() {
      this.activeRouter("homeRouter");
      this.$router.push("/users/home");
    },

    onUsersServicesClick(country) {
      this.showUserSubServices = false;
      this.showUserSubServicesMap = new Map();
      for (let [key, value] of this.showUserServicesMap) {
        if (key === country.countryId) {
          this.showUserServicesMap.set(key, !value);
          if (!this.showUserServicesMap.get(key)) {
            this.userSubServicesObject = {};
          }
        } else {
          this.showUserServicesMap.set(key, false);
        }
      }
    },

    activeRouter(selectedRouter) {
      if (selectedRouter === "homeRouter") {
        for (let [key] of this.servicesRouterActiveMap) {
          this.servicesRouterActiveMap.set(key, false);
        }
        for (let [key] of this.showUserServicesMap) {
          this.showUserServicesMap.set(key, false);
        }
        this.userSubServicesObject = {};
        this.showUserSubServices = false;
        this.homeRouterActive = true;
      } else {
        this.homeRouterActive = false;
        for (let [key] of this.servicesRouterActiveMap) {
          if (key === selectedRouter) {
            this.servicesRouterActiveMap.set(key, true);
          } else {
            this.servicesRouterActiveMap.set(key, false);
          }
        }
      }
    },

    onUserDropdownInfoBlur() {
      this.showUserDropdownInfo = false;
    },

    onUserDropdownInfoClick() {
      this.showUserDropdownInfo = !this.showUserDropdownInfo;
      for (let [key] of this.showUserServicesMap) {
        this.showUserServicesMap.set(key, false);
      }
      this.userSubServicesObject = {};
      this.showUserSubServices = false;
      this.showUserSubServicesMap = new Map();
    },

    onUserProfileClick() {
      this.showUserDropdownInfo = false;
      this.homeRouterActive = false;
      this.$router.push("/users/profile");
    },

    onUserLogoutClick() {
      this.showUserDropdownInfo = false;
      axios.get(services.logout, {});
      this.$store.dispatch("logout/clearStoreAndLogout");
    },

    onServiceSelectClick(countryId, serviceCode) {
      this.showUserSubServicesMap = new Map();

      if ("home" === serviceCode) {
        let countryCode = this.$store.getters["preData/GET_COUNTRY_DETAILS_MAP"].get(countryId).countryCode;
        this.$router.push("/users/" + countryCode + "/" + serviceCode.toLowerCase());
        this.activeRouter(this.countryDetailsMap.get(countryId).countryId);

        for (let [key, value] of this.showUserServicesMap) {
          if (value === true) {
            this.showUserServicesMap.set(key, false);
          }
        }

        this.userSubServicesObject = {};
        this.showUserSubServices = false;
        this.showUserSubServicesMap = new Map();
        return;
      }

      let userSubServicesList = [];
      this.$store.getters["preData/GET_SUB_SERVICES_BY_SERVICE_CODE_DETAILS_MAP"].get(serviceCode).subServicesDetailsList.forEach(subServicesDetail => {
        userSubServicesList.push(this.$store.getters["preData/GET_SUB_SERVICES_DETAILS_MAP"].get(subServicesDetail));
      });

      if (this.userSubServicesObject.countryId === this.$store.getters["preData/GET_COUNTRY_DETAILS_MAP"].get(countryId).countryId && this.userSubServicesObject.serviceCode === serviceCode) {
        this.userSubServicesObject = {};
        this.showUserSubServices = false;
        this.showUserSubServicesMap = new Map();
        return;
      }

      this.userSubServicesObject = {
        countryId: this.$store.getters["preData/GET_COUNTRY_DETAILS_MAP"].get(countryId).countryId,
        countryCode: this.$store.getters["preData/GET_COUNTRY_DETAILS_MAP"].get(countryId).countryCode,
        serviceCode: serviceCode,
        userSubServicesList: userSubServicesList
      };

      this.showUserSubServicesMap.set(serviceCode, true);
      this.showUserSubServices = true;
    },

    onSubServiceSelectClick(countryId, countryCode, serviceCode, subServiceName) { 

      this.userSubServicesObject = {};
      this.showUserSubServices = false;
      this.showUserSubServicesMap = new Map();
      for (let [key] of this.countryDetailsMap) {
        this.servicesRouterActiveMap.set(key, false);
        this.showUserServicesMap.set(key, false);
      }
      this.activeRouter(countryId);
      this.$router.push("/users/" + countryCode + "/" + serviceCode + "/" + subServiceName.toLowerCase());
    }
  }
}
</script>
