// sarathi-ang-1.0/src/app/components/users/BHA/EQ/bhaaratha-shares-sold/bhaaratha-shares-sold.component.ts
import { HttpClient } from '@angular/common/http';
import { Component, OnInit } from '@angular/core';
import services from 'src/assets/services/services.json';

@Component({
  selector: 'app-bhaaratha-shares-sold',
  templateUrl: './bhaaratha-shares-sold.component.html',
  styleUrls: ['./bhaaratha-shares-sold.component.css']
})
export class BhaarathaSharesSoldComponent implements OnInit {

  type: string = "sold";
  isSearchFieldDisabled: boolean = false;
  isSearchButtonDisabled: boolean = false;
  isRefreshButtonDisabled: boolean = false;
  isHeaderDropdownDisabled: boolean = false;
  headerDropdownList: Array<any> = 
  [
    {
      id: "1",
      value: "Consolidated"
    },
    {
      id: "2",
      value: "Non-Consolidated"
    }
  ];
  headerDropdownPlaceholder: string = "Consolidated";
  isNonConsolidated: boolean = false;
  searchText: string = "";
  loading: boolean = true;
  noRecords: boolean = false;
  bhaarathaSharesList: Array<any> = [];
  bhaarathaSharesTotal: Object = {};
  // Error/Success Modal
  showError: boolean  = false;
  errorMessage: string = "";

  constructor(
    private http: HttpClient
  ) { }

  ngOnInit(): void {
    this.getSoldShares();
  }

  getSoldShares() {
    this.loading = true;
    this.isSearchFieldDisabled = true;
    this.isRefreshButtonDisabled = true;
    this.noRecords = false;

    this.http.get(services.bhaarathaSharesShares + "?type=sold&searchTerm=" + this.searchText + "&isNonConsolidated=" + this.isNonConsolidated).subscribe((response: any) => {
      if (response === null) {
        this.noRecords = true;
        this.loading = false;
        //
        this.isSearchFieldDisabled = false;
        this.isRefreshButtonDisabled = false;
      } else {
        this.bhaarathaSharesList = response.bhaarathaSharesList;
        this.bhaarathaSharesTotal = response.bhaarathaSharesTotal
        this.loading = false;
        //
        this.isSearchFieldDisabled = false;
        this.isRefreshButtonDisabled = false;
        this.loading = false;
      }
    }, error => {
      error.error.error.map((e: any) => {
        this.errorMessage = e.errorMessage;
        this.showError = true;
      });
    });
  }

  onSearchClick(bhaarathaShares: any) {
    this.searchText = bhaarathaShares.searchText;
    this.isNonConsolidated = bhaarathaShares.isNonConsolidated;
    this.getSoldShares();
  }

  onRefreshClick(bhaarathaShares: any) {
    this.searchText = bhaarathaShares.searchText;
    this.isNonConsolidated = bhaarathaShares.isNonConsolidated;
    this.getSoldShares();
  }

  onConsolidatedSelect(bhaarathaShares: any) {
    this.searchText = bhaarathaShares.searchText;
    this.isNonConsolidated = bhaarathaShares.isNonConsolidated;
    this.getSoldShares();
  }

  onNonConsolidatedSelect(bhaarathaShares: any) {
    this.searchText = bhaarathaShares.searchText;
    this.isNonConsolidated = bhaarathaShares.isNonConsolidated;
    this.getSoldShares();
  }

  closeError() {
    this.showError = false;
    this.errorMessage = "";
  }
}

<div class="bhaaratha-shares-sold">
  <app-bhaaratha-shares-bought-sold-header
    [type]="type"
    [isSearchFieldDisabled]="isSearchFieldDisabled"
    [isSearchButtonDisabled]="isSearchButtonDisabled"
    [isRefreshButtonDisabled]="isRefreshButtonDisabled"
    [isHeaderDropdownDisabled]="isHeaderDropdownDisabled"
    [headerDropdownList]="headerDropdownList"
    [headerDropdownPlaceholder]="headerDropdownPlaceholder"
    (onSearchClick)="onSearchClick($event)"
    (onRefreshClick)="onRefreshClick($event)"
    (onConsolidatedSelect)="onConsolidatedSelect($event)"
    (onNonConsolidatedSelect)="onNonConsolidatedSelect($event)"
  ></app-bhaaratha-shares-bought-sold-header>
  <app-bhaaratha-shares-bought-and-sold-data
    [type]="'sold'"
    [loading]="loading"
    [noRecords]="noRecords"
    [bhaarathaSharesList]="bhaarathaSharesList"
    [bhaarathaSharesTotal]="bhaarathaSharesTotal"
  ></app-bhaaratha-shares-bought-and-sold-data>

  <app-error-modal
    *ngIf="showError"
    (closeError)="closeError()"
  >
    <span body>
      {{ errorMessage }}
    </span>
  </app-error-modal>
</div>

// sarathi-vue-1.0/src/components/Users/BHA/EQ/BhaarathaSharesSold.vue
<template>
  <div class="bhaaratha-shares-sold">
    <BhaarathaSharesBoughtSoldHeader
      :type="type"
      :isSearchFieldDisabled="isSearchFieldDisabled"
      :isSearchButtonDisabled="isSearchButtonDisabled"
      :isRefreshButtonDisabled="isRefreshButtonDisabled"
      :isHeaderDropdownDisabled="isHeaderDropdownDisabled"
      :headerDropdownList="headerDropdownList"
      :headerDropdownPlaceholder="headerDropdownPlaceholder"
      @onSearchClick="onSearchClick($event)"
      @onRefreshClick="onRefreshClick($event)"
      @onConsolidatedSelect="onConsolidatedSelect($event)"
      @onNonConsolidatedSelect="onNonConsolidatedSelect($event)"
    ></BhaarathaSharesBoughtSoldHeader>
    <BhaarathaSharesBoughtAndSoldData
      :type="'sold'"
      :loading="loading"
      :noRecords="noRecords"
      :bhaarathaSharesList="bhaarathaSharesList"
      :bhaarathaSharesTotal="bhaarathaSharesTotal"
    ></BhaarathaSharesBoughtAndSoldData>

    <ErrorModal
      v-if="showError"
      :errorMessage="errorMessage"
    >
      <template v-slot:header>
        <h3 class="mm-error-modal-title">Error!!</h3>
        <span>
          <MoneyManagerButton
            :buttonClass="'btn-close'"
            @onButtonClick="closeError()"
          >
          </MoneyManagerButton>
        </span>
      </template>
    </ErrorModal>

  </div>
</template>

<script>
import ErrorModal from "@/components/common/ErrorModal.vue";
import MoneyManagerButton from "@/components/common/MoneyManagerButton.vue";
import BhaarathaSharesBoughtSoldHeader from '@/components/Users/BHA/EQ/BoughtSold/BhaarathaSharesBoughtSoldHeader.vue';
import BhaarathaSharesBoughtAndSoldData from '@/components/Users/BHA/EQ/BoughtSold/BhaarathaSharesBoughtAndSoldData.vue';
import services from "@/assets/services/services.json";
import axios from "axios";


export default {
  components: {
    ErrorModal,
    MoneyManagerButton,
    BhaarathaSharesBoughtSoldHeader,
    BhaarathaSharesBoughtAndSoldData
},

  data() {
    return {
      type: "sold",
      isSearchFieldDisabled: false,
      isSearchButtonDisabled: false,
      isRefreshButtonDisabled: false,
      isHeaderDropdownDisabled: false,
      headerDropdownList: [
        {
          id: "1",
          value: "Consolidated"
        },
        {
          id: "2",
          value: "Non-Consolidated"
        }
      ],
      headerDropdownPlaceholder: "Consolidated",
      isNonConsolidated: false,
      searchText: "",
      loading: true,
      noRecords: false,
      bhaarathaSharesList: [],
      bhaarathaSharesTotal: {},
      // Error/Success Modal
      showError: false,
      errorMessage: ""
    }
  },

  created() {
    this.getSoldShares();
  },

  methods: {
    getSoldShares() {
      this.loading = true;
      this.isSearchFieldDisabled = true;
      this.isRefreshButtonDisabled = true;
      this.noRecords = false;

      axios.get(services.bhaarathaSharesShares + "?type=sold&searchTerm=" + this.searchText + "&isNonConsolidated=" + this.isNonConsolidated).then(response => {
        if (response.status === 204) {
          this.noRecords = true;
          this.loading = false;
          //
          this.isSearchFieldDisabled = false;
          this.isRefreshButtonDisabled = false;
        } else {
          this.bhaarathaSharesList = response.data.bhaarathaSharesList;
          this.bhaarathaSharesTotal = response.data.bhaarathaSharesTotal
          this.loading = false;
          //
          this.isSearchFieldDisabled = false;
          this.isRefreshButtonDisabled = false;
          this.loading = false;
        }
      }).catch(error => {
        error.response.data.error.map((e) => {
          this.errorMessage = e.errorMessage;
          this.showError = true;
        });
      });
    },

    onSearchClick(bhaarathaShares) {
      this.searchText = bhaarathaShares.searchText;
      this.isNonConsolidated = bhaarathaShares.isNonConsolidated;
      this.getSoldShares();
    },

    onRefreshClick(bhaarathaShares) {
      this.searchText = bhaarathaShares.searchText;
      this.isNonConsolidated = bhaarathaShares.isNonConsolidated;
      this.getSoldShares();
    },

    onConsolidatedSelect(bhaarathaShares) {
      this.searchText = bhaarathaShares.searchText;
      this.isNonConsolidated = bhaarathaShares.isNonConsolidated;
      this.getSoldShares();
    },

    onNonConsolidatedSelect(bhaarathaShares) {
      this.searchText = bhaarathaShares.searchText;
      this.isNonConsolidated = bhaarathaShares.isNonConsolidated;
      this.getSoldShares();
    },

    closeError() {
      this.showError = false;
      this.errorMessage = "";
    }
  }
}
</script>
