// sarathi-ang-1.0/src/app/components/users/BHA/EQ/bhaaratha-shares-home/bhaaratha-shares-home.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-bhaaratha-shares-home',
  templateUrl: './bhaaratha-shares-home.component.html',
  styleUrls: ['./bhaaratha-shares-home.component.css']
})
export class BhaarathaSharesHomeComponent implements OnInit {

  otherServicesDropdownResetDropdown: boolean = false;
  otherServicesDropdownList: Array<any> = [];

  constructor(
    private router: Router
  ) { }

  ngOnInit(): void {
    this.otherServicesDropdownList = [
      {
        id: "short-term-investment",
        value: "Short Term Investment"
      },
      {
        id: "bulk-upload",
        value: "Bulk Upload"
      }
    ];
  }

  onOtherServicesDropdownSelect(otherServicesDropdownSelected: any) {
    this.otherServicesDropdownResetDropdown = false;
    this.router.navigate(["/users/BHA/EQ/" + otherServicesDropdownSelected.id]);
  }
}

// sarathi-vue-1.0/src/components/Users/BHA/EQ/BhaarathaSharesHome.vue
<template>
  <div class="bhaaratha-shares-home">
    <BhaarathaSharesHomeHeader
      :otherServicesDropdownResetDropdown="otherServicesDropdownResetDropdown"
      :otherServicesDropdownList="otherServicesDropdownList"
      @onOtherServicesDropdownSelect="onOtherServicesDropdownSelect($event)"
    ></BhaarathaSharesHomeHeader>
  </div>
</template>

<script>
import BhaarathaSharesHomeHeader from "@/components/Users/BHA/EQ/Home/BhaarathaSharesHomeHeader.vue";

export default {
  name: "BhaarathaSharesHome",
  components: {
    BhaarathaSharesHomeHeader
  },

  data() {
    return {
      otherServicesDropdownResetDropdown: false,
      otherServicesDropdownList: []
    }
  },

  created() {
    this.otherServicesDropdownList = [
      {
        id: "short-term-investment",
        value: "Short Term Investment"
      },
      {
        id: "bulk-upload",
        value: "Bulk Upload"
      }
    ];
  },

  methods: {
    onOtherServicesDropdownSelect(otherServicesDropdownSelected) {
      this.otherServicesDropdownResetDropdown = false;
      this.$router.push("/users/BHA/EQ/" + otherServicesDropdownSelected.id);
    }
  }
}
</script>
