// sarathi-vue-1.0/src/components/Users/USA/EQ/InvestmentResearch/UnitedStatesOfAmericaSharesInvestmentResearchHeader.vue
<template>
  <div class="united-states-of-america-shares-investment-research-header">
    <div class="services-investment-research-header">
      <div class="header">
        <span class="left-items">
          <MoneyManagerButton
            :buttonClass="'navigation-button btn-sm'"
            @onButtonClick="onBackButtonClick()"
          >
            <template v-slot:title>
              <i class="fas fa-long-arrow-alt-left"></i> Back
            </template>
          </MoneyManagerButton>
        </span>

        <span class="left-items">
          <MoneyManagerButton
            :buttonClass="isRefreshButtonDisabled ? 'btn-sm' : 'btn-primary btn-sm'"
            :buttonDisabled="isRefreshButtonDisabled"
            @onButtonClick="onRefreshClick()"
          >
            <template v-slot:title>
              Refresh <i class="fa fa-refresh"></i>
            </template>
          </MoneyManagerButton>
        </span>
      </div>
    </div>
  </div>
</template>

<script>
import MoneyManagerButton from "@/components/common/MoneyManagerButton.vue";

export default {
  components: {
    MoneyManagerButton
  },

  props: {
    isRefreshButtonDisabled: {
      type: Boolean,
      required: true
    }
  },

  methods: {
    onRefreshClick() {
      this.$emit("onRefreshClick");
    },

    onBackButtonClick() {
      this.$emit("onBackButtonClick");
    }
  }
}
</script>

// sarathi-ang-1.0/src/app/components/users/USA/EQ/InvestmentResearch/united-states-of-america-shares-investment-research-header/united-states-of-america-shares-investment-research-header.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';

@Component({
  selector: 'app-united-states-of-america-shares-investment-research-header',
  templateUrl: './united-states-of-america-shares-investment-research-header.component.html',
  styleUrls: ['./united-states-of-america-shares-investment-research-header.component.css']
})
export class UnitedStatesOfAmericaSharesInvestmentResearchHeaderComponent implements OnInit {

  @Input() isRefreshButtonDisabled!: boolean;
  @Output("onRefreshClick") onRefreshClickEventEmitter = new EventEmitter();
  @Output("onBackButtonClick") onBackButtonClickEventEmitter = new EventEmitter();

  constructor() { }

  ngOnInit(): void {
  }

  onRefreshClick() {
    this.onRefreshClickEventEmitter.emit();
  }

  onBackButtonClick() {
    this.onBackButtonClickEventEmitter.emit("onBackButtonClick");
  }
}

<div class="united-states-of-america-shares-investment-research-header">
  <div class="services-investment-research-header">
    <div class="header">
      <span class="left-items">
        <app-money-manager-button
          [buttonClass]="'navigation-button btn-sm'"
          (onButtonClick)="onBackButtonClick()"
        >
          <span title>
            <i class="fas fa-long-arrow-alt-left"></i> Back
          </span>
        </app-money-manager-button>
      </span>

      <span class="left-items">
        <app-money-manager-button
          [buttonClass]="isRefreshButtonDisabled ? 'btn-sm' : 'btn-primary btn-sm'"
          [buttonDisabled]="isRefreshButtonDisabled"
          (onButtonClick)="onRefreshClick()"
        >
          <span title>
            Refresh <i class="fa fa-refresh"></i>
          </span>
        </app-money-manager-button>
      </span>
    </div>
  </div>
</div>
