// sarathi-ang-1.0/src/app/components/common/confirmation-modal/confirmation-modal.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';

@Component({
  selector: 'app-confirmation-modal',
  templateUrl: './confirmation-modal.component.html',
  styleUrls: ['./confirmation-modal.component.css']
})
export class ConfirmationModalComponent implements OnInit {

  @Input() confirmationMessage!: string;
  @Output("onCloseConfirmation") closeConfirmationEventEmitter = new EventEmitter<any>();
  @Output("onConfirmationContinue") continueConfirmationEventEmitter = new EventEmitter<any>();

  constructor() { }

  ngOnInit(): void {
  }

  onCloseClick() {
    this.closeConfirmationEventEmitter.emit();
  }

  onContinueClick() {
    this.continueConfirmationEventEmitter.emit();
  }

}

<div class="mm-confirmation">
  <div class="mm-confirmation-modal">
    <div class="mm-confirmation-modal-backdrop">
      <div class="mm-confirmation-modal-dialog">
        <div class="mm-confirmation-modal-content">
          <div class="mm-confirmation-modal-header">
            <h3 class="mm-confirmation-modal-title">
              Do you want to continue?
            </h3>
          </div>
          <div
            class="mm-confirmation-modal-body"
          >
            <div class="mm-confirmation-modal-body-content">
              <ng-content select="[body]"></ng-content>
            </div>
          </div>
          <div class="mm-confirmation-modal-footer">
            <div class="mm-confirmation-close">
              <span>
                <app-money-manager-button
                  [buttonTitle]="'Close'"
                  [buttonClass]="'btn btn-danger'"
                  (onButtonClick)="onCloseClick()"
                ></app-money-manager-button>
              </span>
              <div class="mm-confirmation-continue">
                <app-money-manager-button
                  [buttonTitle]="'Continue'"
                  [buttonClass]="'btn btn-primary'"
                  (onButtonClick)="onContinueClick()"
                ></app-money-manager-button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

// sarathi-vue-1.0/src/components/common/ConfirmationModal.vue
<template>
  <div class="mm-confirmation">
    <div class="mm-confirmation-modal">
      <div class="mm-confirmation-modal-backdrop">
        <div class="mm-confirmation-modal-dialog">
          <div class="mm-confirmation-modal-content">
            <div class="mm-confirmation-modal-header">
              <h3 class="mm-confirmation-modal-title">
                Do you want to continue?
              </h3>
            </div>
            <div
              class="mm-confirmation-modal-body"
            >
              <div class="mm-confirmation-modal-body-content">
                <slot name="body">
                  {{ confirmationMessage }}
                </slot>
              </div>
            </div>
            <div class="mm-confirmation-modal-footer">
              <div class="mm-confirmation-close">
                <span>
                  <MoneyManagerButton
                    :buttonTitle="'Close'"
                    :buttonClass="'btn btn-danger'"
                    @onButtonClick="onCloseClick()"
                  ></MoneyManagerButton>
                </span>
                <div class="mm-confirmation-continue">
                  <MoneyManagerButton
                    :buttonTitle="'Continue'"
                    :buttonClass="'btn btn-primary'"
                    @onButtonClick="onContinueClick()"
                  ></MoneyManagerButton>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import MoneyManagerButton from "@/components/common/MoneyManagerButton.vue";

export default {
  name: "ConfirmationModal",
  
  components: {
    MoneyManagerButton
  },

  props: {
    confirmationMessage: {
      type: String,
      required: false
    }
  },

  methods: {
    onCloseClick() {
      this.$emit("onCloseConfirmation")
    },

    onContinueClick() {
      this.$emit("onConfirmationContinue")
    }
  }
}
</script>
