// sarathi-ang-1.0/src/app/components/common/money-manager-check-box/money-manager-check-box.component.ts
import { Component, EventEmitter, Input, OnChanges, OnInit, Output } from '@angular/core';

@Component({
  selector: 'app-money-manager-check-box',
  templateUrl: './money-manager-check-box.component.html',
  styleUrls: ['./money-manager-check-box.component.css']
})
export class MoneyManagerCheckBoxComponent implements OnInit, OnChanges {

  @Input() resetCheckBox!: boolean;
  @Input() checkBoxList!: Array<any>;
  @Input() checkBoxName!: string;
  @Output("onCheckBoxSelect") checkBoxSelectEventEmitter = new EventEmitter<Array<any>>();

  selectedCheckBoxList: Array<any> = [];

  constructor() { }

  ngOnInit(): void {
    this.selectedCheckBoxList = [];
    this.checkBoxList.forEach(checkBox => {
      if (checkBox.isChecked) {
        this.selectedCheckBoxList.push(checkBox);
      }
    });
  }

  ngOnChanges() {
    if (this.resetCheckBox) {
      this.selectedCheckBoxList = [];
      this.checkBoxList.forEach(checkBox => {
        if (checkBox.isChecked) {
          this.selectedCheckBoxList.push(checkBox);
        }
      });
    }
  }

  onCheckBoxSelect(checkBox: any, pushFlag: boolean) {
    if (pushFlag) {
      checkBox.isChecked = pushFlag;
      this.selectedCheckBoxList.push(checkBox);
    } else {
      for(let i=0; i < this.selectedCheckBoxList.length; i++) {
        if (this.selectedCheckBoxList[i].id === checkBox.id) {
          this.selectedCheckBoxList.splice(i, 1);
          break;
        }
      }
    }

    this.checkBoxSelectEventEmitter.emit(this.selectedCheckBoxList);
  }

}

<span
  class="mm-checkbox"
  *ngFor="let checkBox of checkBoxList"
>
  <span class="mm-checkbox-custom">
    <label class="mm-checkbox-label" [ngClass]="[checkBox.isDisabled ? 'mm-checkbox-label-disabled' : '']">
      <input
        type="checkbox"
        [name]="checkBoxName"
        [disabled]="checkBox.isDisabled"
        [(ngModel)]="checkBox.isChecked"
        (change)="onCheckBoxSelect(checkBox, checkBox.isChecked)"
      />
      <span>{{ " " + checkBox.value }}</span>
    </label>
  </span>
</span>

// sarathi-vue-1.0/src/components/common/MoneyManagerCheckBox.vue
<template>
  <span
    class="mm-checkbox"
    v-for="checkBox of checkBoxList"
    :key="checkBox.id"
  >
    <span class="mm-checkbox-custom">
      <label class="mm-checkbox-label" :class="[checkBox.isDisabled ? 'mm-checkbox-label-disabled' : '']">
        <input
          type="checkbox"
          :value="checkBox"
          :disabled="checkBox.isDisabled"
          v-model="selectedCheckBoxList"
          @change="onCheckBoxSelect(selectedCheckBoxList)"
        />
        <span>{{ " " + checkBox.value }}</span>
      </label>
    </span>
  </span>
</template>

<script>
export default {
  name: "MoneyManagerCheckBox",
  emits: ["onCheckBoxSelect"],
  data() {
    return {
      selectedCheckBoxList: []
    }
  },
  props: {
    resetCheckBox: {
      type: Boolean,
      required: true
    },
    checkBoxList: {
      type: Array,
      required: true
    },
    defaultCheckBoxList: {
      type: Array,
      default: () => []
    }
  },

  watch: {
    resetCheckBox(newValue) {
      if (newValue) {
        this.selectedCheckBoxList = this.defaultCheckBoxList;
      }
    }
  },

  created() {
    for (let checkBox of this.defaultCheckBoxList) {
      this.selectedCheckBoxList.push(checkBox);
    }
  },
  methods: {
    onCheckBoxSelect(selectedCheckBoxList) {
      this.$emit("onCheckBoxSelect", selectedCheckBoxList);
    }
  }
}
</script>
