// sarathi-ang-1.0/src/app/components/common/money-manager-min-max-bar/money-manager-min-max-bar.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-money-manager-min-max-bar',
  templateUrl: './money-manager-min-max-bar.component.html',
  styleUrls: ['./money-manager-min-max-bar.component.css']
})
export class MoneyManagerMinMaxBarComponent implements OnInit {

  @Input() lowValue!: string;
  @Input() highValue!: string;
  @Input() highLowValue!: string;

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="mm-min-max-bar">
  <div class="min-max-band">
    <div class="min">
      {{ lowValue }}
    </div>

    <div class="max">
      {{ highValue }}
    </div>

    <div class="min-max">
      <div
        class="min-max-range"
        [ngStyle]="{'margin-left': 'calc(' + highLowValue + '%' + ' - 0.50rem)' }"
      >
        <div class="min-max-pointer"></div>
      </div>
    </div>
  </div>
</div>

// sarathi-vue-1.0/src/components/common/MoneyManagerMinMaxBar.vue
<template>
  <div class="mm-min-max-bar">
    <div class="min-max-band">
      <div class="min">
        {{ lowValue }}
      </div>

      <div class="max">
        {{ highValue }}
      </div>

      <div class="min-max">
        <div
          class="min-max-range"
          :style="{'margin-left': 'calc(' + highLowValue + '%' + ' - 0.50rem)' }"
        >
          <div class="min-max-pointer"></div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    lowValue: {
      type: String,
      required: true
    },
    highValue: {
      type: String,
      required: true
    },
    highLowValue: {
      type: String,
      required: true
    }
  }
}
</script>
