// sarathi-ang-1.0/src/app/components/common/money-manager-radio/money-manager-radio.component.ts
import { Component, EventEmitter, Input, OnChanges, OnInit, Output } from '@angular/core';

@Component({
  selector: 'app-money-manager-radio',
  templateUrl: './money-manager-radio.component.html',
  styleUrls: ['./money-manager-radio.component.css']
})
export class MoneyManagerRadioComponent implements OnInit, OnChanges {

  @Input() resetRadio!: boolean;
  @Input() radioList!: Array<any>;
  @Input() radioDefault: any;
  @Input() radioName!: string;
  @Output("onRadioSelect") radioSelectEventEmitter = new EventEmitter<string>();

  radioSelected: any = {};

  constructor() { }

  ngOnInit(): void {
    if (this.radioDefault) {
      this.radioSelected = this.radioDefault;
    } else if (!this.radioDefault) {
      this.radioSelected = {};
    }
  }

  ngOnChanges() {
    if (this.resetRadio) {
      if (this.radioDefault) {
        this.radioSelected = this.radioDefault;
      } else if (!this.radioDefault) {
        this.radioSelected = {};
      }
    }
  }

  onRadioSelect() {
    this.radioSelectEventEmitter.emit(this.radioSelected);
  }
}

<span class="mm-radio" *ngFor="let radioData of radioList">
  <span class="mm-radio-custom">
    <label class="mm-radio-label">
      <input
        type="radio"
        [value]="radioData"
        [name]="radioName"
        (change)="onRadioSelect()"
        [(ngModel)]="radioSelected"
      />
        <span>{{ " " + radioData.value }}</span>
    </label>
  </span>
</span>

// sarathi-vue-1.0/src/components/common/MoneyManagerRadio.vue
<template>
  <span class="mm-radio" v-for="radio of radioList" :key="radio.id">
    <span class="mm-radio-custom">
      <label class="mm-radio-label">
        <input
          type="radio"
          :value="radio"
          @change="onRadioSelect"
          v-model="radioSelected"
        />
        <span>{{ " " + radio.value }}</span>
      </label>
    </span>
  </span>
</template>

<script>
export default {
  name: "MoneyManagerRadio",
  emits: ["onRadioSelect"],

  created() {
    if (this.radioDefault) {
      this.radioSelected = this.radioDefault;
    } else if (!this.radioDefault) {
      this.radioSelected = {};
    }
  },

  data() {
    return {
      radioSelected: {},
    };
  },
  props: {
    resetRadio: {
      type: Boolean,
      required: true
    },
    radioList: {
      type: Array,
      required: true,
    },
    radioDefault: {
      type: Object,
      required: false
    }
  },
  watch: {
    resetRadio(newValue) {
      if(newValue) {
        if (this.radioDefault) {
          this.radioSelected = this.radioDefault;
        } else {
          this.radioSelected = {};
        }
      }
    }
  },
  methods: {
    onRadioSelect() {
      this.$emit("onRadioSelect", this.radioSelected);
    },
  },
};
</script>
