// sarathi-vue-1.0/src/components/common/MoneyManagerDropdown.vue
<template>
  <div
    class="mm-dropdown"
    :tabindex="tabindex"
    @blur="onDropdownBlur()"
  >
    <span class="dropdown-class" @click="onDropdownClick()">
      <label
        class="dropdown-label"
        :class="[disableDropdown ? 'dropdown-disabled' : '']"
      >
        {{ valueSelected }}
        <span class="arrow">
          <span v-if="showDropdown" class="arrow-up"></span>
          <span v-if="!showDropdown" class="arrow-down"></span>
        </span>
      </label>
    </span>
    <div class="dropdown-value-position" v-if="showDropdown">
      <div v-for="dropdown of dropdownList" :key="dropdown.id">
        <div class="dropdown-value" @click="onDropdownValueClick(dropdown)">{{ dropdown.value }}</div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "MoneyManagerDropdown",
  data() {
    return {
      showDropdown: false,
      selectedValue: ""
    }
  },
  props: {
    disableDropdown: {
      type: Boolean,
      default: false
    },
    resetDropdown: {
      type: Boolean,
      required: true
    },
    placeholder: {
      type: String,
      default: "Select here..."
    },
    dropdownList: {
      type: Array,
      required: true
    },
    tabindex:{
      type: Number,
      required: false,
      default: 0
    }
  },
  computed: {
    valueSelected() {
      if (this.selectedValue.length > 15) {
        return this.selectedValue.substring(0, 15) + "...";
      }
      return this.selectedValue;
    }
  },
  watch: {
    resetDropdown(newValue) {
      if (newValue) {
        this.selectedValue = this.placeholder;
      }
    }
  },
  created() {
    this.selectedValue = this.placeholder;
  },
  methods: {
    onDropdownClick() {
      if (!this.disableDropdown) {
        this.showDropdown = !this.showDropdown;
      }
    },
    onDropdownValueClick(dropdown) {
      this.selectedValue = dropdown.value;
      this.showDropdown = false;
      this.$emit('onDropdownSelect', dropdown);
    },
    onDropdownBlur() {
      this.showDropdown = false;
    }
  }
}
</script>

// sarathi-ang-1.0/src/app/components/common/money-manager-dropdown/money-manager-dropdown.component.ts
import { Component, EventEmitter, Input, OnChanges, OnInit, Output } from '@angular/core';

@Component({
  selector: 'app-money-manager-dropdown',
  templateUrl: './money-manager-dropdown.component.html',
  styleUrls: ['./money-manager-dropdown.component.css']
})
export class MoneyManagerDropdownComponent implements OnInit, OnChanges {

  @Input() disableDropdown!: boolean;
  @Input() resetDropdown!: boolean;
  @Input() placeholder: string = "Select here...";
  @Input() dropdownList!: Array<any>;
  @Input() tabindex: Number = 0;
  @Output("onDropdownSelect") dropdownSelectEventEmitter = new EventEmitter<any>();

  showDropdown: boolean = false;
  selectedValue: string = "";

  constructor() { }

  ngOnInit(): void {
    this.selectedValue = this.placeholder;
  }

  ngOnChanges(): void {
    if (this.resetDropdown) {
      this.selectedValue = this.placeholder;
    }
  }

  onDropdownClick() {
    if (!this.disableDropdown) {
      this.showDropdown = !this.showDropdown;
    }
  }

  onDropdownValueClick(dropdown: any) {
    this.selectedValue = dropdown.value;
    this.showDropdown = false;
    this.dropdownSelectEventEmitter.emit(dropdown);
  }

  onDropdownBlur() {
    this.showDropdown = false;
  }
}

<div
  class="mm-dropdown"
  [tabindex]="tabindex"
  (blur)="onDropdownBlur()"
>
  <span
    class="dropdown-class"
    (click)="onDropdownClick()"
  >
    <label
      class="dropdown-label"
      [ngClass]="[disableDropdown ? 'dropdown-disabled' : '']"
    >
      {{ selectedValue | max15Chars }}
      <span class="arrow">
        <span *ngIf="showDropdown" class="arrow-up"></span>
        <span *ngIf="!showDropdown" class="arrow-down"></span>
      </span>
    </label>
  </span>
  <div class="dropdown-value-position" *ngIf="showDropdown">
    <div *ngFor="let dropdown of dropdownList">
      <div
        class="dropdown-value"
        (click)="onDropdownValueClick(dropdown)"
      >
        {{ dropdown.value }}
      </div>
    </div>
  </div>
</div>
