// sarathi-ang-1.0/src/app/components/users/BHA/EQ/BoughtSold/bhaaratha-shares-bought-and-sold-data/bhaaratha-shares-bought-and-sold-data.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-bhaaratha-shares-bought-and-sold-data',
  templateUrl: './bhaaratha-shares-bought-and-sold-data.component.html',
  styleUrls: ['./bhaaratha-shares-bought-and-sold-data.component.css']
})
export class BhaarathaSharesBoughtAndSoldDataComponent implements OnInit {

  @Input() type!: string;
  @Input() loading!: boolean;
  @Input() noRecords!: boolean;
  @Input() bhaarathaSharesList!: Array<any>;
  @Input() bhaarathaSharesTotal!: any;

  constructor(
    private router: Router
  ) { }

  ngOnInit(): void {
  }

  onBhaarathaSharesScriptClick(event: any, bseCode: string, nseCode: string, moneycontrolCode: string, yahooBseCode: string, yahooNseCode: string) {
    this.router.navigate(["/users/BHA/EQ/one-share"], { queryParams: { type: this.type,  bseCode: bseCode, nseCode: encodeURIComponent(nseCode), moneycontrolCode: moneycontrolCode, yahooBseCode: encodeURIComponent(yahooBseCode), yahooNseCode: encodeURIComponent(yahooNseCode) } });
  }

}

<div class="bhaaratha-shares-bought-and-sold-data">
  <div class="services-bought-sold-data">
    <div class="spinner" *ngIf="loading">
      <app-money-manager-loading></app-money-manager-loading>
    </div>
    <div *ngIf="noRecords" class="no-records">
      ******* NO RECORDS *******
    </div>
    <div *ngIf="!loading && !noRecords">
      <div class="services-bought-sold-table">
        <div class="mm-table">
          <table class="mm-table-data">
            <thead>
              <tr>
                <th>SCRIPT NAME</th>
                <th>PURCHASE PRICE</th>
                <th>PURCHASE TOTAL</th>
                <th>PURCHASE NET</th>
                <th>SELL PRICE</th>
                <th>SELL TOTAL</th>
                <th>SELL NET</th>
                <th>P/L</th>
                <th>P/L (%)</th>
                <th>NET P/L</th>
              </tr>
            </thead>
            <tbody>
              <tr *ngFor="let bhaarathaShares of bhaarathaSharesList" :key="bhaarathaShares.id">
                <td>
                  <span class="link" (click)="onBhaarathaSharesScriptClick($event, bhaarathaShares.bseScriptCode, bhaarathaShares.nseScriptCode, bhaarathaShares.moneycontrolCode, bhaarathaShares.yahooBseScriptCode, bhaarathaShares.yahooNseScriptCode)">
                    {{ bhaarathaShares.scriptName }}
                  </span>
                </td>
                <td>{{ bhaarathaShares.purchasePrice }}</td>
                <td>{{ bhaarathaShares.purchaseTotal }}</td>
                <td>{{ bhaarathaShares.purchaseNetPricePerUnit }}</td>
                <td>{{ bhaarathaShares.sellPrice }}</td>
                <td>{{ bhaarathaShares.sellTotal }}</td>
                <td>{{ bhaarathaShares.sellNetPricePerUnit }}</td>
                <td appHighlightByNumbers [value]="bhaarathaShares.totalProfitLoss">{{ bhaarathaShares.totalProfitLoss }}</td>
                <td appHighlightByNumbers [value]="bhaarathaShares.totalProfitLossPercentage">{{ bhaarathaShares.totalProfitLossPercentage }}%</td>
                <td appHighlightByNumbers [value]="bhaarathaShares.netProfitLossPerUnit">{{ bhaarathaShares.netProfitLossPerUnit }}</td>
              </tr>
            </tbody>
            <tfoot>
              <tr>
                <td>TOTAL</td>
                <td>{{ bhaarathaSharesTotal.purchasePrice }}</td>
                <td>{{ bhaarathaSharesTotal.purchaseTotal }}</td>
                <td>{{ bhaarathaSharesTotal.purchaseNetPricePerUnit }}</td>
                <td>{{ bhaarathaSharesTotal.sellPrice }}</td>
                <td>{{ bhaarathaSharesTotal.sellTotal }}</td>
                <td>{{ bhaarathaSharesTotal.sellNetPricePerUnit }}</td>
                <td appHighlightByNumbers [value]="bhaarathaSharesTotal.totalProfitLoss">{{ bhaarathaSharesTotal.totalProfitLoss }}</td>
                <td appHighlightByNumbers [value]="bhaarathaSharesTotal.totalProfitLossPercentage">{{ bhaarathaSharesTotal.totalProfitLossPercentage }}%</td>
                <td appHighlightByNumbers [value]="bhaarathaSharesTotal.netProfitLossPerUnit">{{ bhaarathaSharesTotal.netProfitLossPerUnit }}</td>
              </tr>
            </tfoot>
          </table>
        </div>
        <div class="services-bought-sold-content">
          Your portfolio has provided a total return of <span appHighlightByNumbers [value]="bhaarathaSharesTotal.totalProfitLoss" [fontWeight]="'bold'">{{ bhaarathaSharesTotal.totalProfitLoss }}</span> (<span appHighlightByNumbers [value]="bhaarathaSharesTotal.totalProfitLossPercentage" [fontWeight]="'bold'">{{ bhaarathaSharesTotal.totalProfitLossPercentage }}%</span>) and per unit net return of <span appHighlightByNumbers [value]="bhaarathaSharesTotal.netProfitLossPerUnit" [fontWeight]="'bold'">{{ bhaarathaSharesTotal.netProfitLossPerUnit }}</span>
        </div>
      </div>
    </div>
  </div>
</div>

// sarathi-vue-1.0/src/components/Users/BHA/EQ/BoughtSold/BhaarathaSharesBoughtAndSoldData.vue
<template>
  <div class="bhaaratha-shares-bought-and-sold-data">
    <div class="services-bought-sold-data">
      <div class="spinner" v-if="loading">
        <MoneyManagerLoading></MoneyManagerLoading>
      </div>
      <div v-if="noRecords" class="no-records">
        ******* NO RECORDS *******
      </div>
      <div v-if="!loading && !noRecords">
        <div class="services-bought-sold-table">
          <div class="mm-table">
            <table class="mm-table-data">
              <thead>
                <tr>
                  <th>SCRIPT NAME</th>
                  <th>PURCHASE PRICE</th>
                  <th>PURCHASE TOTAL</th>
                  <th>PURCHASE NET</th>
                  <th>SELL PRICE</th>
                  <th>SELL TOTAL</th>
                  <th>SELL NET</th>
                  <th>P/L</th>
                  <th>P/L (%)</th>
                  <th>NET P/L</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="bhaarathaShares of bhaarathaSharesList" :key="bhaarathaShares.id">
                  <td>
                    <span class="link" @click="onBhaarathaSharesScriptClick($event, bhaarathaShares.bseScriptCode, bhaarathaShares.nseScriptCode, bhaarathaShares.moneycontrolCode, bhaarathaShares.yahooBseScriptCode, bhaarathaShares.yahooNseScriptCode)">
                      {{ bhaarathaShares.scriptName }}
                    </span>
                  </td>
                  <td>{{ bhaarathaShares.purchasePrice }}</td>
                  <td>{{ bhaarathaShares.purchaseTotal }}</td>
                  <td>{{ bhaarathaShares.purchaseNetPricePerUnit }}</td>
                  <td>{{ bhaarathaShares.sellPrice }}</td>
                  <td>{{ bhaarathaShares.sellTotal }}</td>
                  <td>{{ bhaarathaShares.sellNetPricePerUnit }}</td>
                  <td v-highlight-by-numbers>{{ bhaarathaShares.totalProfitLoss }}</td>
                  <td v-highlight-by-numbers>{{ bhaarathaShares.totalProfitLossPercentage }}%</td>
                  <td v-highlight-by-numbers>{{ bhaarathaShares.netProfitLossPerUnit }}</td>
                </tr>
              </tbody>
              <tfoot>
                <tr>
                  <td>TOTAL</td>
                  <td>{{ bhaarathaSharesTotal.purchasePrice }}</td>
                  <td>{{ bhaarathaSharesTotal.purchaseTotal }}</td>
                  <td>{{ bhaarathaSharesTotal.purchaseNetPricePerUnit }}</td>
                  <td>{{ bhaarathaSharesTotal.sellPrice }}</td>
                  <td>{{ bhaarathaSharesTotal.sellTotal }}</td>
                  <td>{{ bhaarathaSharesTotal.sellNetPricePerUnit }}</td>
                  <td v-highlight-by-numbers>{{ bhaarathaSharesTotal.totalProfitLoss }}</td>
                  <td v-highlight-by-numbers>{{ bhaarathaSharesTotal.totalProfitLossPercentage }}%</td>
                  <td v-highlight-by-numbers>{{ bhaarathaSharesTotal.netProfitLossPerUnit }}</td>
                </tr>
              </tfoot>
            </table>
          </div>
          <div class="services-bought-sold-content">
            Your portfolio has provided a total return of <span v-highlight-by-numbers="'bold'">{{ bhaarathaSharesTotal.totalProfitLoss }}</span> (<span v-highlight-by-numbers="'bold'">{{ bhaarathaSharesTotal.totalProfitLossPercentage }}%</span>) and per unit net return of <span v-highlight-by-numbers="'bold'">{{ bhaarathaSharesTotal.netProfitLossPerUnit }}</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import MoneyManagerLoading from '@/components/common/MoneyManagerLoading.vue';

export default {
  components: {
    MoneyManagerLoading
  },

  props: {
    type: {
      type: String,
      required: true
    },
    loading: {
      type: Boolean,
      required: true
    },
    noRecords: {
      type: Boolean,
      required: true
    },
    bhaarathaSharesList: {
      type: Array,
      required: true
    },
    bhaarathaSharesTotal: {
      type: Object,
      required: true
    }
  },

  methods: {
    onBhaarathaSharesScriptClick(event, bseCode, nseCode, moneycontrolCode, yahooBseCode, yahooNseCode) {
      this.$router.push({ path: "/users/BHA/EQ/one-share", query: { type: this.type, bseCode: bseCode, nseCode: encodeURIComponent(nseCode), moneycontrolCode: moneycontrolCode,  yahooBseCode: encodeURIComponent(yahooBseCode), yahooNseCode: encodeURIComponent(yahooNseCode) } });
    }
  }
}
</script>
