// sarathi-vue-1.0/src/components/Users/BHA/EQ/BhaarathaSharesInvestmentResearch.vue
<template>
  <div class="bhaaratha-shares-investment-research">
    <BhaarathaSharesInvestmentResearchHeader
      :isRefreshButtonDisabled="isRefreshButtonDisabled"
      @onRefreshClick="onRefreshClick()"
      @onBackButtonClick="onBackButtonClick()"
    ></BhaarathaSharesInvestmentResearchHeader>
    <BhaarathaSharesInvestmentResearchData
      :loading="loading"
      :noRecords="noRecords"
      :investmentResearchList="investmentResearchList"
      :sortingColumn="sortingColumn"
      :sortingType="sortingType"
      @sortInvestmentResearch="sortInvestmentResearch($event)"
    ></BhaarathaSharesInvestmentResearchData>
  </div>
</template>

<script>
import BhaarathaSharesInvestmentResearchHeader from "@/components/Users/BHA/EQ/InvestmentResearch/BhaarathaSharesInvestmentResearchHeader.vue";
import BhaarathaSharesInvestmentResearchData from "@/components/Users/BHA/EQ/InvestmentResearch/BhaarathaSharesInvestmentResearchData.vue";
import services from "@/assets/services/services.json";
import axios from "axios";

export default {
  components: {
    BhaarathaSharesInvestmentResearchHeader,
    BhaarathaSharesInvestmentResearchData
  },

  data() {
    return {
      loading: false,
      isRefreshButtonDisabled: false,
      noRecords: false,
      defaultInvestmentResearchList: [],
      investmentResearchList: [],
      sortInvestmentResearchMap: new Map(),
      sortingColumn: "",
      sortingType: ""
    }
  },

  created() {
    this.defaultSortInvestmentResearchMap()
    this.getInvestmentResearch();
  },

  methods: {
    defaultSortInvestmentResearchMap() {
      this.sortInvestmentResearchMap.set("scriptName", "");
      this.sortInvestmentResearchMap.set("dailyRange", "");
      this.sortInvestmentResearchMap.set("52WRange", "");
      this.sortInvestmentResearchMap.set("ttmDividendYield", "");
    },

    getInvestmentResearch() {
      this.loading = true;
      this.isRefreshButtonDisabled = true;
      this.noRecords = false;

      if (this.$store.getters["bhaarathaSharesInvestmentResearch/GET_BHAARATHA_SHARES_INVESTMENT_RESEARCH_LIST"].length === 0) {
        axios.get(services.bhaarathaSharesInvestmentResearch).then(response => {
          if (response.status === 204) {
            this.noRecords = true;
            this.loading = false;
            this.isRefreshButtonDisabled = false;
          } else {
            this.$store.commit("bhaarathaSharesInvestmentResearch/SET_BHAARATHA_SHARES_INVESTMENT_RESEARCH_LIST", response.data.bhaarathaSharesInvestmentResearchList);
            this.noRecords = false;
            this.loading = false;
            this.isRefreshButtonDisabled = false;
          }

          this.defaultInvestmentResearchList = this.$store.getters["bhaarathaSharesInvestmentResearch/GET_BHAARATHA_SHARES_INVESTMENT_RESEARCH_LIST"];
          this.buildInvestmentResearchList();
        }).catch(error => {
          console.log(error);
        });
      } else {
        this.defaultInvestmentResearchList = this.$store.getters["bhaarathaSharesInvestmentResearch/GET_BHAARATHA_SHARES_INVESTMENT_RESEARCH_LIST"];
        this.buildInvestmentResearchList();

        this.noRecords = false;
        this.loading = false;
        this.isRefreshButtonDisabled = false;
      }
    },

    buildInvestmentResearchList() {
      this.investmentResearchList = [];
      this.defaultInvestmentResearchList.forEach(defaultInvestmentResearch => {
        this.investmentResearchList.push(defaultInvestmentResearch);
      });
    },

    sortInvestmentResearch(column) {
      this.loading = true;
      this.isRefreshButtonDisabled = true;
      
      this.sortingColumn = column;
      this.sortingType = this.sortInvestmentResearchMap.get(column);

      this.defaultSortInvestmentResearchMap();

      if (this.sortingType === "") {
        this.sortingType = "ASC";
      } else if (this.sortingType === "ASC") {
        this.sortingType = "DESC";
      } else if (this.sortingType === "DESC") {
        this.sortingType = "ASC";
      }

      this.sortInvestmentResearchMap.set(this.sortingColumn, this.sortingType);

      if (this.sortingColumn === "scriptName") {
        if (this.sortingType === "ASC") {
          this.investmentResearchList.sort((a, b) => {
            return a.scriptName.localeCompare(b.scriptName);
          });
        } else if (this.sortingType === "DESC") {
          this.investmentResearchList.sort((a, b) => {
            return b.scriptName.localeCompare(a.scriptName);
          });
        }
      } else if (this.sortingColumn === "dailyRange") {
        if (this.sortingType === "ASC") {
          this.investmentResearchList.sort((a, b) => {
            return a.dailyRange - b.dailyRange;
          });
        } else if (this.sortingType === "DESC") {
          this.investmentResearchList.sort((a, b) => {
            return b.dailyRange - a.dailyRange;
          });
        }
      } else if (this.sortingColumn === "52WRange") {
        if (this.sortingType === "ASC") {
          this.investmentResearchList.sort((a, b) => {
            return a.fiftyTwoWeekRange - b.fiftyTwoWeekRange;
          });
        } else if (this.sortingType === "DESC") {
          this.investmentResearchList.sort((a, b) => {
            return b.fiftyTwoWeekRange - a.fiftyTwoWeekRange;
          });
        }
      } else if (this.sortingColumn === "ttmDividendYield") {
        if (this.sortingType === "ASC") {
          this.investmentResearchList.sort((a, b) => {
            return a.ttmDividendYield - b.ttmDividendYield;
          });
        } else if (this.sortingType === "DESC") {
          this.investmentResearchList.sort((a, b) => {
            return b.ttmDividendYield - a.ttmDividendYield;
          });
        }
      }

      this.loading = false;
      this.isRefreshButtonDisabled = false;
    },

    onRefreshClick() {
      this.defaultSortInvestmentResearchMap();
      this.sortingColumn = "";
      this.sortingType = "";
      this.$store.commit("bhaarathaSharesInvestmentResearch/SET_BHAARATHA_SHARES_INVESTMENT_RESEARCH_LIST", []);
      this.getInvestmentResearch();
    },

    onBackButtonClick() {
      this.$router.push("/users/BHA/EQ/analysis");
    }
  }
}
</script>

// sarathi-ang-1.0/src/app/components/users/BHA/EQ/bhaaratha-shares-investment-research/bhaaratha-shares-investment-research.component.ts
import { HttpClient } from '@angular/common/http';
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { BhaarathaSharesInvestmentResearchStoreService } from 'src/app/common/store/bhaaratha-shares-investment-research/bhaaratha-shares-investment-research-store.service';
import services from 'src/assets/services/services.json';

@Component({
  selector: 'app-bhaaratha-shares-investment-research',
  templateUrl: './bhaaratha-shares-investment-research.component.html',
  styleUrls: ['./bhaaratha-shares-investment-research.component.css']
})
export class BhaarathaSharesInvestmentResearchComponent implements OnInit {

  loading: boolean = false;
  isRefreshButtonDisabled: boolean = false;
  noRecords: boolean = false;
  defaultInvestmentResearchList: Array<any> = [];
  investmentResearchList: Array<any> = [];
  sortInvestmentResearchMap: Map<string, any> = new Map();
  sortingColumn: string = "";
  sortingType: string = "";

  constructor(
    private bhaarathaSharesInvestmentResearchStoreService: BhaarathaSharesInvestmentResearchStoreService,
    private http: HttpClient,
    private router: Router
  ) { }

  ngOnInit(): void {
    this.defaultSortInvestmentResearchMap()
    this.getInvestmentResearch();
  }

  defaultSortInvestmentResearchMap() {
    this.sortInvestmentResearchMap.set("scriptName", "");
    this.sortInvestmentResearchMap.set("dailyRange", "");
    this.sortInvestmentResearchMap.set("52WRange", "");
    this.sortInvestmentResearchMap.set("ttmDividendYield", "");
  }

  getInvestmentResearch() {
    this.loading = true;
    this.isRefreshButtonDisabled = true;
    this.noRecords = false;

    if (this.bhaarathaSharesInvestmentResearchStoreService.getBhaarathaSharesInvestmentResearchList().length === 0) {
      this.http.get(services.bhaarathaSharesInvestmentResearch).subscribe((response:any) => {
        if (response.status === 204) {
          this.noRecords = true;
          this.loading = false;
          this.isRefreshButtonDisabled = false;
        } else {
          this.bhaarathaSharesInvestmentResearchStoreService.setBhaarathaSharesInvestmentResearchList(response.bhaarathaSharesInvestmentResearchList);
          this.noRecords = false;
          this.loading = false;
          this.isRefreshButtonDisabled = false;
        }

        this.defaultInvestmentResearchList = this.bhaarathaSharesInvestmentResearchStoreService.getBhaarathaSharesInvestmentResearchList();
        this.buildInvestmentResearchList();
      }, error => {
        console.log(error);
      });
    } else {
      this.defaultInvestmentResearchList = this.bhaarathaSharesInvestmentResearchStoreService.getBhaarathaSharesInvestmentResearchList();
      this.buildInvestmentResearchList();

      this.noRecords = false;
      this.loading = false;
      this.isRefreshButtonDisabled = false;
    }
  }

  buildInvestmentResearchList() {
    this.investmentResearchList = [];
    this.defaultInvestmentResearchList.forEach(defaultInvestmentResearch => {
      this.investmentResearchList.push(defaultInvestmentResearch);
    });
  }

  sortInvestmentResearch(column: string) {
    this.loading = true;
    this.isRefreshButtonDisabled = true;
    
    this.sortingColumn = column;
    this.sortingType = this.sortInvestmentResearchMap.get(column);

    this.defaultSortInvestmentResearchMap();

    if (this.sortingType === "") {
      this.sortingType = "ASC";
    } else if (this.sortingType === "ASC") {
      this.sortingType = "DESC";
    } else if (this.sortingType === "DESC") {
      this.sortingType = "ASC";
    }

    this.sortInvestmentResearchMap.set(this.sortingColumn, this.sortingType);

    if (this.sortingColumn === "scriptName") {
      if (this.sortingType === "ASC") {
        this.investmentResearchList.sort((a, b) => {
          return a.scriptName.localeCompare(b.scriptName);
        });
      } else if (this.sortingType === "DESC") {
        this.investmentResearchList.sort((a, b) => {
          return b.scriptName.localeCompare(a.scriptName);
        });
      }
    } else if (this.sortingColumn === "dailyRange") {
      if (this.sortingType === "ASC") {
        this.investmentResearchList.sort((a, b) => {
          return a.dailyRange - b.dailyRange;
        });
      } else if (this.sortingType === "DESC") {
        this.investmentResearchList.sort((a, b) => {
          return b.dailyRange - a.dailyRange;
        });
      }
    } else if (this.sortingColumn === "52WRange") {
      if (this.sortingType === "ASC") {
        this.investmentResearchList.sort((a, b) => {
          return a.fiftyTwoWeekRange - b.fiftyTwoWeekRange;
        });
      } else if (this.sortingType === "DESC") {
        this.investmentResearchList.sort((a, b) => {
          return b.fiftyTwoWeekRange - a.fiftyTwoWeekRange;
        });
      }
    } else if (this.sortingColumn === "ttmDividendYield") {
      if (this.sortingType === "ASC") {
        this.investmentResearchList.sort((a, b) => {
          return a.ttmDividendYield - b.ttmDividendYield;
        });
      } else if (this.sortingType === "DESC") {
        this.investmentResearchList.sort((a, b) => {
          return b.ttmDividendYield - a.ttmDividendYield;
        });
      }
    }

    this.loading = false;
    this.isRefreshButtonDisabled = false;
  }

  onRefreshClick() {
    this.defaultSortInvestmentResearchMap();
    this.sortingColumn = "";
    this.sortingType = "";
    this.bhaarathaSharesInvestmentResearchStoreService.clearBhaarathaSharesInvestmentResearchList();
    this.getInvestmentResearch();
  }

  onBackButtonClick() {
    this.router.navigate(["/users/BHA/EQ/analysis"]);
  }
}

<div class="bhaaratha-shares-investment-research">
  <app-bhaaratha-shares-investment-research-header
    [isRefreshButtonDisabled]="isRefreshButtonDisabled"
    (onRefreshClick)="onRefreshClick()"
    (onBackButtonClick)="onBackButtonClick()"
  ></app-bhaaratha-shares-investment-research-header>
  <app-bhaaratha-shares-investment-research-data
    [loading]="loading"
    [noRecords]="noRecords"
    [investmentResearchList]="investmentResearchList"
    [sortingColumn]="sortingColumn"
    [sortingType]="sortingType"
    (sortInvestmentResearch)="sortInvestmentResearch($event)"
  ></app-bhaaratha-shares-investment-research-data>
</div>
