// sarathi-vue-1.0/src/components/Users/BHA/EQ/BhaarathaSharesAnalysis.vue
<template>
  <div class="bhaaratha-shares-analysis">
    <BhaarathaSharesAnalysisServicesHeader
      :resetAnalysisServicesDropdown="resetAnalysisServicesDropdown"
      :analysisServicesDropdownList="analysisServicesDropdownList"
      @onAnalysisServicesDropdownSelect="onAnalysisServicesDropdownSelect($event)"
    ></BhaarathaSharesAnalysisServicesHeader>
  </div>
</template>

<script>
import BhaarathaSharesAnalysisServicesHeader from "@/components/Users/BHA/EQ/Analysis/BhaarathaSharesAnalysisServicesHeader.vue";

export default {
  components: {
    BhaarathaSharesAnalysisServicesHeader
  },

  data() {
    return {
      resetAnalysisServicesDropdown: false,
      analysisServicesDropdownList: [
        {
          id: "complete-analysis",
          value: "Complete Analysis"
        },
        {
          id: "dividend-yield-analysis",
          value: "Dividend Yield Analysis"
        },
        {
          id: "investment-research",
          value: "Investment Research"
        }
      ]
    }
  },

  methods: {
    onAnalysisServicesDropdownSelect(selectedAnalysisService) {
      this.$router.push("/users/BHA/EQ/" + selectedAnalysisService.id);
    }
  }
}
</script>

// sarathi-ang-1.0/src/app/components/users/BHA/EQ/bhaaratha-shares-analysis/bhaaratha-shares-analysis.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-bhaaratha-shares-analysis',
  templateUrl: './bhaaratha-shares-analysis.component.html',
  styleUrls: ['./bhaaratha-shares-analysis.component.css']
})
export class BhaarathaSharesAnalysisComponent implements OnInit {

  resetAnalysisServicesDropdown: boolean = false;
  analysisServicesDropdownList: Array<any> = [
    {
      id: "complete-analysis",
      value: "Complete Analysis"
    },
    {
      id: "dividend-yield-analysis",
      value: "Dividend Yield Analysis"
    },
    {
      id: "investment-research",
      value: "Investment Research"
    }
  ];

  constructor(
    private router: Router
  ) { }

  ngOnInit(): void {
  }

  onAnalysisServicesDropdownSelect(selectedAnalysisService: any) {
    this.router.navigate(["/users/BHA/EQ/" + selectedAnalysisService.id]);
  }
}

<div class="bhaaratha-shares-analysis">
  <app-bhaaratha-shares-analysis-services-header
    [resetAnalysisServicesDropdown]="resetAnalysisServicesDropdown"
    [analysisServicesDropdownList]="analysisServicesDropdownList"
    (onAnalysisServicesDropdownSelect)="onAnalysisServicesDropdownSelect($event)"
  ></app-bhaaratha-shares-analysis-services-header>
</div>
