// sarathi-ang-1.0/src/app/components/users/USA/EQ/Home/united-states-of-america-shares-home-header/united-states-of-america-shares-home-header.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';

@Component({
  selector: 'app-united-states-of-america-shares-home-header',
  templateUrl: './united-states-of-america-shares-home-header.component.html',
  styleUrls: ['./united-states-of-america-shares-home-header.component.css']
})
export class UnitedStatesOfAmericaSharesHomeHeaderComponent implements OnInit {

  @Input() otherServicesDropdownResetDropdown!: boolean;
  @Input() otherServicesDropdownList!: Array<any>;
  @Output("onOtherServicesDropdownSelect") onOtherServicesDropdownSelectEventEmitter = new EventEmitter<any>();

  constructor() { }

  ngOnInit(): void {
  }

  onOtherServicesDropdownSelect(dropdownServicesSelected: any) {
    this.onOtherServicesDropdownSelectEventEmitter.emit(dropdownServicesSelected);
  }

}

<div class="bhaaratha-shares-home-header">
  <div class="services-home-header">
    <app-money-manager-dropdown
      [resetDropdown]="otherServicesDropdownResetDropdown"
      [dropdownList]="otherServicesDropdownList"
      [placeholder]="'Other Services'"
      (onDropdownSelect)="onOtherServicesDropdownSelect($event)"
    ></app-money-manager-dropdown>
  </div>
</div>

// sarathi-vue-1.0/src/components/Users/USA/EQ/Home/UnitedStatesOfAmericaSharesHomeHeader.vue
<template>
  <div class="united-states-of-america-shares-home-header">
    <div class="services-home-header">
      <MoneyManagerDropdown
        :resetDropdown="otherServicesDropdownResetDropdown"
        :dropdownList="otherServicesDropdownList"
        :placeholder="'Other Services'"
        @onDropdownSelect="onOtherServicesDropdownSelect($event)"
      ></MoneyManagerDropdown>
    </div>
  </div>
</template>

<script>
import MoneyManagerDropdown from "@/components/common/MoneyManagerDropdown.vue";

export default {
  components: {
    MoneyManagerDropdown
  },

  props: {
    otherServicesDropdownResetDropdown: {
      type: Boolean,
      required: true
    },
    otherServicesDropdownList: {
      type: Array,
      required: true
    }
  },

  methods: {
    onOtherServicesDropdownSelect(dropdownServicesSelected) {
      this.$emit('onOtherServicesDropdownSelect', dropdownServicesSelected);
    }
  }
}
</script>
