// sarathi-vue-1.0/src/components/Users/BHA/EQ/BhaarathaSharesOneShare.vue
<template>
  <div class="bhaaratha-shares-one-share">
    <BhaarathaSharesOneShareDetailsHeader
      :type="type"
      :isRefreshButtonDisabled="isRefreshButtonDisabled"
      @onRefreshClick="onRefreshClick()"
    ></BhaarathaSharesOneShareDetailsHeader>

    <BhaarathaSharesOneShareDetailsData
      :loading="loading"
      :noRecords="noRecords"
      :pageRefreshed="pageRefreshed"
      :bhaarathaSharesList="bhaarathaSharesList"
      :bhaarathaSharesTotal="bhaarathaSharesTotal"
      :bseOneShareDetails="bseOneShareDetails"
      :nseOneShareDetails="nseOneShareDetails"
    ></BhaarathaSharesOneShareDetailsData>

    <ErrorModal
      v-if="showError"
    >
      <template v-slot:header>
        <h3 class="mm-error-modal-title">Error!!</h3>
        <span>
          <MoneyManagerButton
            :buttonClass="'btn-close'"
            @onButtonClick="closeError()"
          >
          </MoneyManagerButton>
        </span>
      </template>
      <template v-slot:body>
        <span v-html="errorMessage"></span>
      </template>
    </ErrorModal>
  </div>
</template>

<script>
import BhaarathaSharesOneShareDetailsHeader from "@/components/Users/BHA/EQ/OneShareDetails/BhaarathaSharesOneShareDetailsHeader.vue";
import BhaarathaSharesOneShareDetailsData from "@/components/Users/BHA/EQ/OneShareDetails/BhaarathaSharesOneShareDetailsData.vue";
import ErrorModal from "@/components/common/ErrorModal.vue";
import MoneyManagerButton from "@/components/common/MoneyManagerButton.vue";
import services from "@/assets/services/services.json";
import axios from "axios";

export default {
  components: {
    BhaarathaSharesOneShareDetailsHeader,
    BhaarathaSharesOneShareDetailsData,
    MoneyManagerButton,
    ErrorModal
  },

  data() {
    return {
      type: "",
      bseCode: "",
      nseCode: "",
      moneycontrolCode: "",
      yahooBseCode: "",
      yahooNseCode: "",
      loading: false,
      noRecords: false,
      isRefreshButtonDisabled: false,
      pageRefreshed: false,
      bhaarathaSharesList: [],
      bhaarathaSharesTotal: {},
      bseOneShareDetails: {},
      nseOneShareDetails: {},
      // Error/Success Modal
      showError: false,
      errorMessage: "",
    }
  },

  created() {
    this.type = this.$route.query.type;
    this.bseCode = this.$route.query.bseCode;
    this.nseCode = this.$route.query.nseCode;
    this.moneycontrolCode = this.$route.query.moneycontrolCode;
    this.yahooBseCode = this.$route.query.yahooBseCode;
    this.yahooNseCode = this.$route.query.yahooNseCode;
    this.getOneShareDetails();
  },

  methods: {
    getOneShareDetails() {
      this.loading = true;
      this.noRecords = false;
      this.isRefreshButtonDisabled = true;

      axios.get(services.bhaarathaSharesOneShareDetails + "?type=" + this.type + "&bseCode=" + this.bseCode + "&nseCode=" + this.nseCode + "&moneycontrolCode=" + this.moneycontrolCode + "&yahooBseCode=" + this.yahooBseCode + "&yahooNseCode=" + this.yahooNseCode).then(response => {
        if (response.status === 204) {
          this.noRecords = true;
          this.loading = false;
        } else {
          this.bhaarathaSharesList = response.data.bhaarathaSharesResponse.bhaarathaSharesList;
          this.bhaarathaSharesTotal = response.data.bhaarathaSharesResponse.bhaarathaSharesTotal;
          this.bseOneShareDetails = response.data.bseOneShareDetails;
          this.nseOneShareDetails = response.data.nseOneShareDetails;
          this.isRefreshButtonDisabled = false;
          this.loading = false;
          this.pageRefreshed = false;
        }
      }).catch(error => {
        this.errorMessage = "";
        error.response.data.error.map((e) => {
          this.errorMessage = this.errorMessage + e.errorMessage +"<br>";
          this.showError = true;
        });
      });
    },

    onRefreshClick() {
      this.pageRefreshed = true;
      this.getOneShareDetails();
    },

    closeError() {
      this.showError = false;
      this.errorMessage = "";
    }
  }
}
</script>

// sarathi-ang-1.0/src/app/components/users/BHA/EQ/bhaaratha-shares-one-share/bhaaratha-shares-one-share.component.ts
import { HttpClient } from '@angular/common/http';
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import services from 'src/assets/services/services.json';

@Component({
  selector: 'app-bhaaratha-shares-one-share',
  templateUrl: './bhaaratha-shares-one-share.component.html',
  styleUrls: ['./bhaaratha-shares-one-share.component.css']
})
export class BhaarathaSharesOneShareComponent implements OnInit {

  type: string = "";
  bseCode: string = "";
  nseCode: string = "";
  moneycontrolCode: string = "";
  yahooBseCode: string = "";
  yahooNseCode: string ="";
  loading: boolean = false;
  noRecords: boolean = false;
  isRefreshButtonDisabled: boolean = false;
  pageRefreshed: boolean = false;
  bhaarathaSharesList: Array<any> = [];
  bhaarathaSharesTotal: any = {};
  bseOneShareDetails: any = {};
  nseOneShareDetails: any = {};
  // Error/Success Modal
  showError: boolean = false;
  errorMessage: string = "";

  constructor(
    private activatedRoute: ActivatedRoute,
    private http: HttpClient,
    private router: Router
  ) { }

  ngOnInit(): void {
    this.activatedRoute.queryParams.subscribe(params => {
      this.type = params["type"];
      this.bseCode = params["bseCode"];
      this.nseCode = params["nseCode"];
      this.moneycontrolCode = params["moneycontrolCode"];
      this.yahooBseCode = params["yahooBseCode"];
      this.yahooNseCode = params["yahooNseCode"];
    });

    this.getOneShareDetails();
  }

  getOneShareDetails() {
    this.loading = true;
    this.noRecords = false;
    this.isRefreshButtonDisabled = true;

    this.http.get(services.bhaarathaSharesOneShareDetails + "?type=" + this.type + "&bseCode=" + this.bseCode + "&nseCode=" + this.nseCode + "&moneycontrolCode=" + this.moneycontrolCode + "&yahooBseCode=" + this.yahooBseCode + "&yahooNseCode=" + this.yahooNseCode).subscribe((response: any) => {
      if (response === null) {
        this.noRecords = true;
        this.loading = false;
      } else {
        this.bhaarathaSharesList = response.bhaarathaSharesResponse.bhaarathaSharesList;
        this.bhaarathaSharesTotal = response.bhaarathaSharesResponse.bhaarathaSharesTotal;
        this.bseOneShareDetails = response.bseOneShareDetails;
        this.nseOneShareDetails = response.nseOneShareDetails;
        this.isRefreshButtonDisabled = false;
        this.loading = false;
        this.pageRefreshed = false;
      }
    }, error => {
      this.errorMessage = "";
      error.error.error.map((e: any) => {
        this.errorMessage = this.errorMessage + e.errorMessage +"<br>";
        this.showError = true;
      });
    });
  }

  onRefreshClick() {
    this.pageRefreshed = true;
    this.getOneShareDetails();
  }

  closeError() {
    this.showError = false;
    this.errorMessage = "";
  }

}

<div class="bhaaratha-shares-one-share-details">
  <app-bhaaratha-shares-one-share-details-header
    [type]="type"
    [isRefreshButtonDisabled]="isRefreshButtonDisabled"
    (onRefreshClick)="onRefreshClick()"
  ></app-bhaaratha-shares-one-share-details-header>

  <app-bhaaratha-shares-one-share-details-data
    [loading]="loading"
    [noRecords]="noRecords"
    [pageRefreshed]="pageRefreshed"
    [bhaarathaSharesList]="bhaarathaSharesList"
    [bhaarathaSharesTotal]="bhaarathaSharesTotal"
    [bseOneShareDetails]="bseOneShareDetails"
    [nseOneShareDetails]="nseOneShareDetails"
  ></app-bhaaratha-shares-one-share-details-data>

  <app-error-modal
    *ngIf="showError"
    (closeError)="closeError()"
  >
    <span body>
      <span [innerHtml]="errorMessage"></span>
    </span>
  </app-error-modal>
</div>
