// sarathi-vue-1.0/src/components/Demo.vue
<template>
  <div>
    <hr>
    <router-link :to="'/'">Home</router-link>
    <hr>
    <MoneyManagerButton
      :buttonTitle="'Button Title'"
      :buttonClass="'btn-primary'"
      @onButtonClick="onButtonClick()"
    >
      <template v-slot:title> Title from Parent </template>
    </MoneyManagerButton>
    <hr />
    <MoneyManagerRadio
      :resetRadio="resetRadio"
      :radioList="radioList"
      :radioDefault="radioDefault"
      @onRadioSelect="onRadioSelect"
    ></MoneyManagerRadio>
    <hr />
    <MoneyManagerDropdown
      :resetDropdown="resetDropdown"
      :dropdownList="dropdownList"
      @onDropdownSelect="onDropdownSelect($event)"
    ></MoneyManagerDropdown>
    <hr />
    <MoneyManagerCheckBox
      :resetCheckBox="resetCheckBox"
      :checkBoxList="checkBoxList"
      :defaultCheckBoxList="defaultCheckBoxList"
      @onCheckBoxSelect="onCheckBoxSelect($event)"
    ></MoneyManagerCheckBox>
    <hr />
    <MoneyManagerDatePicker
      :resetDatePicker="resetDatePicker"
      :defaultDate="defaultDate"
      @onSelectedFullDate="onDateSelected($event)"
    ></MoneyManagerDatePicker>
    <hr />
    <MoneyManagerButton
      :buttonTitle="'Loading Modal'"
      :buttonClass="'btn-primary btn-sm'"
      @onButtonClick="onLoadingModalClick()"
    ></MoneyManagerButton>
    <hr />
    <MoneyManagerButton
      :buttonTitle="'Reset'"
      :buttonClass="'btn-primary btn-sm'"
      @onButtonClick="resetData()"
    ></MoneyManagerButton>
    <MoneyManagerButton
      :buttonTitle="'Submit'"
      :buttonClass="'btn-primary btn-sm'"
      @onButtonClick="submitData()"
    ></MoneyManagerButton>
    <hr />
    <MoneyManagerLoadingModal
      v-if="loadingModal"
    ></MoneyManagerLoadingModal>
  </div>
</template>

<script>
import MoneyManagerButton from "@/components/common/MoneyManagerButton.vue";
import MoneyManagerRadio from "@/components/common/MoneyManagerRadio.vue";
import MoneyManagerDropdown from "@/components/common/MoneyManagerDropdown.vue";
import MoneyManagerCheckBox from "@/components/common/MoneyManagerCheckBox.vue";
import MoneyManagerDatePicker from "@/components/common/MoneyManagerDatePicker.vue";
import MoneyManagerLoadingModal from "@/components/common/MoneyManagerLoadingModal.vue";

export default {
  name: "Demo",
  components: {
    MoneyManagerButton,
    MoneyManagerRadio,
    MoneyManagerDropdown,
    MoneyManagerCheckBox,
    MoneyManagerDatePicker,
    MoneyManagerLoadingModal
  },
  data() {
    return {
      resetRadio: false,
      radioList: [
        {
          id: "1",
          value: "Male",
        },
        {
          id: "2",
          value: "Female",
        },
      ],
      radioDefault: {},
      resetDropdown: false,
      dropdownList: [
        {
          id: "1",
          value: "Dropdown 1"
        },
        {
          id: "2",
          value: "Dropdown 2"
        },
        {
          id: "3",
          value: "Dropdown 3"
        }
      ],
      resetCheckBox: false,
      checkBoxList: [
        {
          id: "1",
          value: "Check Box 1"
        },
        {
          id: "2",
          value: "Check Box 2"
        }
      ],
      defaultCheckBoxList: [
        {
          id: "1",
          value: "Check Box 1"
        }
      ],
      resetDatePicker: false,
      defaultDate: "",
      loadingModal: false
    };
  },
  created() {
    this.radioDefault = this.radioList[0];
  },
  methods: {
    onButtonClick() {
      console.log("Button clicked");
    },
    onRadioSelect(radioSelected) {
      this.resetRadio = false;
      console.log("Radio selected: " + radioSelected.value);
    },
    onDropdownSelect(dropdownSelected) {
      this.resetDropdown = false;
      console.log("Dropdown Selected: " + dropdownSelected.value);
    },
    onCheckBoxSelect(checkBoxSelected) {
      this.resetCheckBox = false;
      console.log("******* CheckBox Selected *******")
      for (let checkBox of checkBoxSelected) {
        console.log(checkBox.id + " - " + checkBox.value);
      }
      console.log("******* CheckBox Selected *******");
    },
    onDateSelected(selectedDate) {
      this.resetDatePicker = false;
      console.log("Date Selected: " + selectedDate);
    },
    resetData() {
      console.log("Reset");
      this.resetRadio = true;
      this.resetDropdown = true;
      this.resetCheckBox = true;
      this.resetDatePicker = true;
    },
    onLoadingModalClick() {
      this.loadingModal = true;
      setTimeout(() => {
        this.loadingModal = false;
      }, 5000);
    }
  },
};
</script>

// sarathi-ang-1.0/src/app/components/demo/demo.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-demo',
  templateUrl: './demo.component.html',
  styleUrls: ['./demo.component.css']
})
export class DemoComponent implements OnInit {

  resetRadio: boolean = false;
  radioList: Array<any> = [
    {
      id: "1",
      value: "Male"
    },
    {
      id: "2",
      value: "Female"
    }
  ];
  radioDefault: any = this.radioList[0];

  resetDropdown: boolean = false;
  dropdownList: Array<any> = [
    {
      id: "1",
      value: "Dropdown 1",
      isChecked: false
    },
    {
      id: "2",
      value: "Dropdown 2",
      isChecked: false
    },
    {
      id: "3",
      value: "Dropdown 3",
      isChecked: false
    }
  ];

  resetCheckBox: boolean = false;
  checkBoxList: Array<any> = [
    {
      id: "1",
      value: "Check Box 1",
      isChecked: true
    },
    {
      id: "2",
      value: "Check Box 2",
      isChecked: false
    }
  ];

  resetDatePicker: boolean = false;
  defaultDate: string = "12-APR-1989";

  isError: boolean = false;
  errorMessage: string = "";
  isSuccess: boolean = false;
  successMessage: string = "";
  loadingModal: boolean = false;

  constructor() { }

  ngOnInit(): void {
  }

  onButtonClick() {
    console.log("Button Clicked");
  }

  onRadioSelect(radioSelected: string) {
    this.resetRadio = false;
    console.log("Radio selected: " + radioSelected);
  }

  onDropdownSelect(dropdown: any) {
    this.resetDropdown = false;
    console.log("Dropdown selected: " + dropdown.value);
  }

  onCheckBoxSelect(checkBoxSelected: any) {
    this.resetCheckBox = false;
    console.log("******* CheckBox Selected *******");
    for (let checkBox of checkBoxSelected) {
      console.log(checkBox.id + " - " + checkBox.value);
    }
    console.log("******* CheckBox Selected *******");
  }

  onDateSelected(selectedDate: string) {
    this.resetDatePicker = false;
    console.log("Date Selected: " + selectedDate);
  }

  resetData() {
    console.log("Reset");

    // Resetting checkbox
    this.checkBoxList = [
      {
        id: "1",
        value: "Check Box 1",
        isChecked: true
      },
      {
        id: "2",
        value: "Check Box 2",
        isChecked: false
      }
    ];

    this.resetRadio = true;
    this.resetDropdown = true;
    this.resetCheckBox = true;
    this.resetDatePicker = true;
  }

  showError() {
    this.errorMessage = "Error Message"
    this.isError = true;
  }

  closeError(isError: boolean) {
    this.isError = isError;
    this.errorMessage = "";
  }

  showSuccess() {
    this.successMessage = "Success Message"
    this.isSuccess = true;
  }

  closeSuccess(isSuccess: boolean) {
    this.successMessage = "";
    this.isSuccess = isSuccess;
  }

  onLoadingModalClick() {
    this.loadingModal = true;
    setTimeout(() => {
      this.loadingModal = false;
    }, 5000);
  }
}

<hr>
<a [routerLink]="'/'">Home</a>
<hr>
<app-money-manager-button
  [buttonTitle]="'Button Title'"
  [buttonClass]="'btn-primary'"
  (onButtonClick)="onButtonClick()"
>
</app-money-manager-button>
<hr>
<app-money-manager-radio
  [resetRadio]="resetRadio"
  [radioList]="radioList"
  [radioDefault]="radioDefault"
  [radioName]="'demoRadioName'"
  (onRadioSelect)="onRadioSelect($event)"
></app-money-manager-radio>
<hr>
<app-money-manager-dropdown
  [resetDropdown]="resetDropdown"
  [dropdownList]="dropdownList"
  (onDropdownSelect)="onDropdownSelect($event)"
></app-money-manager-dropdown>
<hr>
<app-money-manager-check-box
  [resetCheckBox]="resetCheckBox"
  [checkBoxList]="checkBoxList"
  [checkBoxName]="'demoCheckBox'"
  (onCheckBoxSelect)="onCheckBoxSelect($event)"
></app-money-manager-check-box>
<hr />
  <app-money-manager-date-picker
    [resetDatePicker]="resetDatePicker"
    (onSelectedFullDate)="onDateSelected($event)"
  ></app-money-manager-date-picker>
<hr>
<app-money-manager-button
  [buttonTitle]="'Loading Modal'"
  [buttonClass]="'btn-primary btn-sm'"
  (onButtonClick)="onLoadingModalClick()"
></app-money-manager-button>
<hr />
<app-money-manager-button
  [buttonTitle]="'Reset'"
  [buttonClass]="'btn-primary'"
  (onButtonClick)="resetData()"
></app-money-manager-button>
<hr>
<app-money-manager-button
  [buttonTitle]="'Open Error'"
  [buttonClass]="'btn-primary'"
  (onButtonClick)="showError()"
></app-money-manager-button>
<app-error-modal
  *ngIf="isError"
  (closeError)="closeError($event)"
>
  <span body>
    {{ errorMessage }}
  </span>
</app-error-modal> | 
<app-money-manager-button
  [buttonTitle]="'Open Success'"
  [buttonClass]="'btn-primary'"
  (onButtonClick)="showSuccess()"
></app-money-manager-button>
<app-success-modal
  *ngIf="isSuccess"
  (closeSuccess)="closeSuccess($event)"
>
  <span body>
    {{ successMessage }}
  </span>
</app-success-modal>

<app-money-manager-loading-modal
  *ngIf="loadingModal"
></app-money-manager-loading-modal>
