// sarathi-vue-1.0/src/components/Users/USA/EQ/BoughtSold/UnitedStatesOfAmericaSharesBoughtSettingsModal.vue
<template>
  <div class="united-states-of-america-shares-bought-settings-modal">
    <div class="services-bought-settings-modal">
      <div class="services-bought-settings-modal-backdrop">
        <div class="services-bought-settings-modal-dialog">
          <div class="services-bought-settings-modal-content">
            <div class="services-bought-settings-modal-header">
              <h3 class="services-bought-settings-modal-title">Settings</h3>
            </div>
            <div
              class="services-bought-settings-modal-body"
            >
              <div class="services-bought-settings-modal-body-content">
                <div class="key">Long Term Only</div>
                <div class="value">
                  <MoneyManagerRadio
                    :resetRadio="false"
                    :radioList="longTermRadioList"
                    :radioDefault="longTermRadioDefault"
                    @onRadioSelect="onLongTermRadioSelect($event)"
                  ></MoneyManagerRadio>
                </div>
              </div>
            </div>
            <div class="services-bought-settings-modal-footer">
              <div class="services-bought-settings-close">
                <span>
                  <MoneyManagerButton
                    :buttonTitle="'Close'"
                    :buttonClass="'btn btn-danger'"
                    @onButtonClick="onCloseSettingsClick()"
                  ></MoneyManagerButton>
                </span>
                <div class="services-bought-settings-continue">
                  <MoneyManagerButton
                    :buttonTitle="'Confirm'"
                    :buttonClass="'btn btn-primary'"
                    @onButtonClick="onConfirmSettingsClick()"
                  ></MoneyManagerButton>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import MoneyManagerButton from "@/components/common/MoneyManagerButton.vue";
import MoneyManagerRadio from "@/components/common/MoneyManagerRadio.vue";

export default {
  name: "UnitedStatesOfAmericaSharesBoughtSettingsModal",
  components: {
    MoneyManagerButton,
    MoneyManagerRadio
  },

  props: {
    longTermRadioList: {
      type: Array,
      required: true
    },

    longTermRadioDefault: {
      type: Object,
      required: true
    }
  },

  data() {
    return {
      longTermRadio: {}
    }
  },

  created() {
    this.longTermRadio = this.longTermRadioDefault;
  },

  methods: {
    onLongTermRadioSelect(longTermRadioSelect) {
      this.longTermRadio = longTermRadioSelect;
    },

    onCloseSettingsClick() {
      this.$emit("onCloseSettingsClick");
    },

    onConfirmSettingsClick() {
      this.$emit("onConfirmSettingsClick", this.longTermRadio);
    }
  }
}
</script>

// sarathi-ang-1.0/src/app/components/users/USA/EQ/BoughtSold/united-states-of-america-shares-bought-settings-modal/united-states-of-america-shares-bought-settings-modal.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';

@Component({
  selector: 'app-united-states-of-america-shares-bought-settings-modal',
  templateUrl: './united-states-of-america-shares-bought-settings-modal.component.html',
  styleUrls: ['./united-states-of-america-shares-bought-settings-modal.component.css']
})
export class UnitedStatesOfAmericaSharesBoughtSettingsModalComponent implements OnInit {

  @Input() longTermRadioList!: Array<any>;
  @Input() longTermRadioDefault!: any;
  @Output("onCloseSettingsClick") closeSettingsClickEventEmitter = new EventEmitter<any>(); 
  @Output("onConfirmSettingsClick") confirmSettingsClickEventEmitter = new EventEmitter<any>();

  longTermRadio: any;

  constructor() { }

  ngOnInit(): void {
    this.longTermRadio = this.longTermRadioDefault;
  }

  onLongTermRadioSelect(longTermRadioSelect: any) {
    this.longTermRadio = longTermRadioSelect;
  }

  onCloseSettingsClick() {
    this.closeSettingsClickEventEmitter.emit();
  }

  onConfirmSettingsClick() {
    this.confirmSettingsClickEventEmitter.emit(this.longTermRadio);
  }
}

<div class="united-states-of-america-shares-bought-settings-modal">
  <div class="services-bought-settings-modal">
    <div class="services-bought-settings-modal-backdrop">
      <div class="services-bought-settings-modal-dialog">
        <div class="services-bought-settings-modal-content">
          <div class="services-bought-settings-modal-header">
            <h3 class="services-bought-settings-modal-title">Settings</h3>
          </div>
          <div
            class="services-bought-settings-modal-body"
          >
            <div class="services-bought-settings-modal-body-content">
              <div class="key">Long Term Only</div>
              <div class="value">
                <app-money-manager-radio
                  [resetRadio]="false"
                  [radioList]="longTermRadioList"
                  [radioDefault]="longTermRadioDefault"
                  (onRadioSelect)="onLongTermRadioSelect($event)"
                ></app-money-manager-radio>
              </div>
            </div>
          </div>
          <div class="services-bought-settings-modal-footer">
            <div class="services-bought-settings-close">
              <span>
                <app-money-manager-button
                  [buttonTitle]="'Close'"
                  [buttonClass]="'btn btn-danger'"
                  (onButtonClick)="onCloseSettingsClick()"
                ></app-money-manager-button>
              </span>
              <div class="services-bought-settings-continue">
                <app-money-manager-button
                  [buttonTitle]="'Confirm'"
                  [buttonClass]="'btn btn-primary'"
                  (onButtonClick)="onConfirmSettingsClick()"
                ></app-money-manager-button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
