// sarathi-ang-1.0/src/app/components/users/USA/EQ/BoughtSold/united-states-of-america-shares-add-shares-header/united-states-of-america-shares-add-shares-header.component.ts
import { Component, EventEmitter, OnInit, Output } from '@angular/core';

@Component({
  selector: 'app-united-states-of-america-shares-add-shares-header',
  templateUrl: './united-states-of-america-shares-add-shares-header.component.html',
  styleUrls: ['./united-states-of-america-shares-add-shares-header.component.css']
})
export class UnitedStatesOfAmericaSharesAddSharesHeaderComponent implements OnInit {

  @Output("onBackButtonClicked") backButtonClickedEventEmitter = new EventEmitter();

  constructor() { }

  ngOnInit(): void {
  }

  onBackButtonClick() {
    this.backButtonClickedEventEmitter.emit();
  }
}

<div class="united-states-of-america-shares-add-shares-header">
  <div class="services-add-scripts-header">
    <div class="header">
      <app-money-manager-button
        [buttonClass]="'navigation-button btn-sm'"
        (onButtonClick)="onBackButtonClick()"
      >
        <span title>
          <i class="fas fa-long-arrow-alt-left"></i> Back
        </span>
      </app-money-manager-button>
    </div>
  </div>
</div>

// sarathi-vue-1.0/src/components/Users/USA/EQ/BoughtSold/UnitedStatesOfAmericaSharesAddSharesHeader.vue
<template>
  <div class="united-states-of-america-shares-add-shares-header">
    <div class="services-add-scripts-header">
      <div class="header">
        <MoneyManagerButton
          :buttonClass="'navigation-button btn-sm'"
          @onButtonClick="onBackButtonClick()"
        >
          <template v-slot:title>
            <i class="fas fa-long-arrow-alt-left"></i> Back
          </template>
        </MoneyManagerButton>
      </div>
    </div>
  </div>
</template>

<script>
import MoneyManagerButton from "@/components/common/MoneyManagerButton.vue";

export default {
  components: {
    MoneyManagerButton
  },

  methods: {
    onBackButtonClick() {
      this.$emit("onBackButtonClicked")
    }
  }
}
</script>
