// sarathi-vue-1.0/src/components/Users/BHA/EQ/Analysis/BhaarathaSharesSectorCategoryAnalysisSettingsModal.vue
<template>
  <div class="bhaaratha-shares-sector-category-analysis-settings-modal">
    <div class="services-analysis-settings-modal">
      <div class="services-analysis-settings-modal-backdrop">
        <div class="services-analysis-settings-modal-dialog">
          <div class="services-analysis-settings-modal-content">
            <div class="services-analysis-settings-modal-header">
              <h3 class="services-analysis-settings-modal-title">Settings</h3>
            </div>
            <div
              class="services-analysis-settings-modal-body"
            >
              <div class="services-analysis-settings-modal-body-content">
                <div class="services-analysis-settings-form">
                  <div class="key">Long Term Only</div>
                  <div class="value">
                    <MoneyManagerRadio
                      :resetRadio="false"
                      :radioList="longTermRadioList"
                      :radioDefault="longTermRadioDefault"
                      @onRadioSelect="onLongTermRadioSelect($event)"
                    ></MoneyManagerRadio>
                  </div>
                </div>

                <div class="services-analysis-settings-form">
                  <div class="key">Value In %</div>
                  <div class="value">
                    <MoneyManagerRadio
                      :resetRadio="false"
                      :radioList="valueInPercentageRadioList"
                      :radioDefault="valueInPercentageRadioDefault"
                      @onRadioSelect="onValueInPercentageRadioSelect($event)"
                    ></MoneyManagerRadio>
                  </div>
                </div>
              </div>
            </div>
            <div class="services-analysis-settings-modal-footer">
              <div class="services-analysis-settings-close">
                <span>
                  <MoneyManagerButton
                    :buttonTitle="'Close'"
                    :buttonClass="'btn btn-danger'"
                    @onButtonClick="onCloseSettingsClick()"
                  ></MoneyManagerButton>
                </span>
                <div class="services-analysis-settings-continue">
                  <MoneyManagerButton
                    :buttonTitle="'Confirm'"
                    :buttonClass="'btn btn-primary'"
                    @onButtonClick="onConfirmSettingsClick()"
                  ></MoneyManagerButton>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import MoneyManagerButton from "@/components/common/MoneyManagerButton.vue";
import MoneyManagerRadio from "@/components/common/MoneyManagerRadio.vue";

export default {
  name: "BhaarathaSharesAnalysisSettingsModal",
  components: {
    MoneyManagerButton,
    MoneyManagerRadio
  },

  props: {
    longTermRadioList: {
      type: Array,
      required: true
    },

    longTermRadioDefault: {
      type: Object,
      required: true
    },
    valueInPercentageRadioList: {
      type: Array,
      required: true
    },

    valueInPercentageRadioDefault: {
      type: Object,
      required: true
    }
  },

  data() {
    return {
      longTermRadio: {},
      valueInPercentageRadio: {}
    }
  },

  created() {
    this.longTermRadio = this.longTermRadioDefault;
    this.valueInPercentageRadio = this.valueInPercentageRadioDefault;
  },

  methods: {
    onLongTermRadioSelect(longTermRadioSelect) {
      this.longTermRadio = longTermRadioSelect;
    },

    onValueInPercentageRadioSelect(valueInPercentageSelect) {
      this.valueInPercentageRadio = valueInPercentageSelect;
    },

    onCloseSettingsClick() {
      this.$emit("onCloseSettingsClick");
    },

    onConfirmSettingsClick() {
      this.$emit("onConfirmSettingsClick", { longTermRadio: this.longTermRadio, valueInPercentageRadio: this.valueInPercentageRadio});
    }
  }
}
</script>

// sarathi-ang-1.0/src/app/components/users/BHA/EQ/Analysis/bhaaratha-shares-sector-category-analysis-settings-modal/bhaaratha-shares-sector-category-analysis-settings-modal.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';

@Component({
  selector: 'app-bhaaratha-shares-sector-category-analysis-settings-modal',
  templateUrl: './bhaaratha-shares-sector-category-analysis-settings-modal.component.html',
  styleUrls: ['./bhaaratha-shares-sector-category-analysis-settings-modal.component.css']
})
export class BhaarathaSharesSectorCategoryAnalysisSettingsModalComponent implements OnInit {

  @Input() longTermRadioList!: Array<any>;
  @Input() longTermRadioDefault!: any;
  @Input() valueInPercentageRadioList!: Array<any>;
  @Input() valueInPercentageRadioDefault!: any;
  @Output("onCloseSettingsClick") onCloseSettingsClickEventEmitter = new EventEmitter();
  @Output("onConfirmSettingsClick") onConfirmSettingsClickEventEmitter = new EventEmitter<any>();

  longTermRadio: any = {};
  valueInPercentageRadio: any = {};

  constructor() { }

  ngOnInit(): void {
    this.longTermRadio = this.longTermRadioDefault;
    this.valueInPercentageRadio = this.valueInPercentageRadioDefault;
  }

  onLongTermRadioSelect(longTermRadioSelect: any) {
    this.longTermRadio = longTermRadioSelect;
  }

  onValueInPercentageRadioSelect(valueInPercentageSelect: any) {
    this.valueInPercentageRadio = valueInPercentageSelect;
  }

  onCloseSettingsClick() {
    this.onCloseSettingsClickEventEmitter.emit();
  }

  onConfirmSettingsClick() {
    this.onConfirmSettingsClickEventEmitter.emit({ longTermRadio: this.longTermRadio, valueInPercentageRadio: this.valueInPercentageRadio});
  }

}

<div class="bhaaratha-shares-sector-category-analysis-settings-modal">
  <div class="mm-bhaaratha-shares-analysis-settings">
    <div class="services-analysis-settings-modal">
      <div class="services-analysis-settings-modal-backdrop">
        <div class="services-analysis-settings-modal-dialog">
          <div class="services-analysis-settings-modal-content">
            <div class="services-analysis-settings-modal-header">
              <h3 class="services-analysis-settings-modal-title">Settings</h3>
            </div>
            <div
              class="services-analysis-settings-modal-body"
            >
              <div class="services-analysis-settings-modal-body-content">
                <div class="services-analysis-settings-form">
                  <div class="key">Long Term Only</div>
                  <div class="value">
                    <app-money-manager-radio
                      [resetRadio]="false"
                      [radioList]="longTermRadioList"
                      [radioDefault]="longTermRadioDefault"
                      [radioName]="'longTermOnlyRadio'"
                      (onRadioSelect)="onLongTermRadioSelect($event)"
                    ></app-money-manager-radio>
                  </div>
                </div>

                <div class="services-analysis-settings-form">
                  <div class="key">Value In %</div>
                  <div class="value">
                    <app-money-manager-radio
                      [resetRadio]="false"
                      [radioList]="valueInPercentageRadioList"
                      [radioDefault]="valueInPercentageRadioDefault"
                      [radioName]="'valueInPercentageRadio'"
                      (onRadioSelect)="onValueInPercentageRadioSelect($event)"
                    ></app-money-manager-radio>
                  </div>
                </div>
              </div>
            </div>
            <div class="services-analysis-settings-modal-footer">
              <div class="services-analysis-settings-close">
                <span>
                  <app-money-manager-button
                    [buttonTitle]="'Close'"
                    [buttonClass]="'btn btn-danger'"
                    (onButtonClick)="onCloseSettingsClick()"
                  ></app-money-manager-button>
                </span>
                <div class="services-analysis-settings-continue">
                  <app-money-manager-button
                    [buttonTitle]="'Confirm'"
                    [buttonClass]="'btn btn-primary'"
                    (onButtonClick)="onConfirmSettingsClick()"
                  ></app-money-manager-button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
