// sarathi-vue-1.0/src/components/Users/BHA/EQ/Analysis/BhaarathaSharesOneAnalysisHeader.vue
<template>
  <div class="bhaaratha-shares-one-analysis-header">
    <div class="services-one-analysis-header">
      <div class="header">
        <span class="left-items">
          <MoneyManagerButton
            :buttonClass="'navigation-button btn-sm'"
            @onButtonClick="onBackButtonClick()"
          >
            <template v-slot:title>
              <i class="fas fa-long-arrow-alt-left"></i> Back
            </template>
          </MoneyManagerButton>
        </span>
      </div>
    </div>
  </div>
</template>

<script>
import MoneyManagerButton from "@/components/common/MoneyManagerButton.vue";

export default {
  components: {
    MoneyManagerButton
  },

  methods: {
    onBackButtonClick() {
      this.$emit("onBackButtonClick");
    }
  }
}
</script>

// sarathi-ang-1.0/src/app/components/users/BHA/EQ/Analysis/bhaaratha-shares-one-analysis-header/bhaaratha-shares-one-analysis-header.component.ts
import { Component, EventEmitter, OnInit, Output } from '@angular/core';

@Component({
  selector: 'app-bhaaratha-shares-one-analysis-header',
  templateUrl: './bhaaratha-shares-one-analysis-header.component.html',
  styleUrls: ['./bhaaratha-shares-one-analysis-header.component.css']
})
export class BhaarathaSharesOneAnalysisHeaderComponent implements OnInit {

  @Output("onBackButtonClick") onBackButtonClickEventEmitter = new EventEmitter();
  
  constructor() { }

  ngOnInit(): void {
  }

  onBackButtonClick() {
    this.onBackButtonClickEventEmitter.emit();
  }

}

<div class="bhaaratha-shares-one-analysis-header">
  <div class="services-one-analysis-header">
    <div class="header">
      <span class="left-items">
        <app-money-manager-button
          [buttonClass]="'navigation-button btn-sm'"
          (onButtonClick)="onBackButtonClick()"
        >
          <span title>
            <i class="fas fa-long-arrow-alt-left"></i> Back
          </span>
        </app-money-manager-button>
      </span>
    </div>
  </div>
</div>
