// sarathi-vue-1.0/src/components/common/MoneyManagerLoadingModal.vue
<template>
  <div class="mm-loading-modal">
    <div class="mm-loading-modal-backdrop">
      <div class="mm-loading-modal-dialog">
        <div class="mm-loading-modal-content">
            <div class="mm-loading-modal-header">
              ******* {{ headingDisplay }} *******
            </div>
            <div class="mm-loading-modal-body">
              <MoneyManagerLoading></MoneyManagerLoading>
            </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import MoneyManagerLoading from "@/components/common/MoneyManagerLoading.vue";

export default {
  name: "MoneyManagerLoadingModal",

  components: {
    MoneyManagerLoading
  },

  props: {
    headingDisplay: {
      type: String,
      default: () => "Your patience is greatly valued"
    }
  }
}
</script>

// sarathi-ang-1.0/src/app/components/common/money-manager-loading-modal/money-manager-loading-modal.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-money-manager-loading-modal',
  templateUrl: './money-manager-loading-modal.component.html',
  styleUrls: ['./money-manager-loading-modal.component.css']
})
export class MoneyManagerLoadingModalComponent implements OnInit {

  @Input() headingDisplay!: string;

  constructor() { }

  ngOnInit(): void {
    if (!this.headingDisplay) {
      this.headingDisplay = "Your patience is greatly valued";
    }
  }

}

<div class="mm-loading-modal">
  <div class="mm-loading-modal-backdrop">
    <div class="mm-loading-modal-dialog">
      <div class="mm-loading-modal-content">
          <div class="mm-loading-modal-header">
            ******* {{ headingDisplay }} *******
          </div>
          <div class="mm-loading-modal-body">
            <app-money-manager-loading></app-money-manager-loading>
          </div>
      </div>
    </div>
  </div>
</div>
