// sarathi-ang-1.0/src/app/components/users/USA/EQ/ShortTermInvestment/united-states-of-america-shares-short-term-investment-header/united-states-of-america-shares-short-term-investment-header.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';

@Component({
  selector: 'app-united-states-of-america-shares-short-term-investment-header',
  templateUrl: './united-states-of-america-shares-short-term-investment-header.component.html',
  styleUrls: ['./united-states-of-america-shares-short-term-investment-header.component.css']
})
export class UnitedStatesOfAmericaSharesShortTermInvestmentHeaderComponent implements OnInit {

  @Input() isRefreshButtonDisabled!: boolean;
  @Input() oneShareShortTermInvestment: boolean = false;
  @Output("onBackButtonClick") onBackButtonClickEventEmitter = new EventEmitter();
  @Output("onRefreshClick") onRefreshClickEventEmitter = new EventEmitter();
  @Output("onAddShortTermInvestmentClick") onAddShortTermInvestmentClickEventEmitter = new EventEmitter();
  
  constructor() { }

  ngOnInit(): void {
  }

  onBackButtonClick() {
    this.onBackButtonClickEventEmitter.emit();
  }

  onRefreshClick() {
    this.onRefreshClickEventEmitter.emit();
  }

  onAddShortTermInvestmentClick() {
    this.onAddShortTermInvestmentClickEventEmitter.emit();
  }

}

<div class="united-states-of-america-shares-short-term-investment-header">
  <div class="services-short-term-investment-header">
    <div class="header">
      <span class="left-items">
        <app-money-manager-button
          *ngIf="oneShareShortTermInvestment"
          [buttonClass]="'navigation-button btn-sm'"
          (onButtonClick)="onBackButtonClick()"
        >
          <span title>
            <i class="fas fa-long-arrow-alt-left"></i> Back
          </span>
        </app-money-manager-button>
      </span>

      <span class="left-items">
        <app-money-manager-button
          [buttonClass]="isRefreshButtonDisabled ? 'btn-sm' : 'btn-primary btn-sm'"
          [buttonDisabled]="isRefreshButtonDisabled"
          (onButtonClick)="onRefreshClick()"
        >
          <span title>
            <i class="fa fa-refresh"></i> Refresh
          </span>
        </app-money-manager-button>
      </span>

      <div class="right">
        <span class="right-items">
          <app-money-manager-button
            [buttonClass]="'btn-buy btn-sm'"
            (onButtonClick)="onAddShortTermInvestmentClick()"
          >
            <span title>
              Add
            </span>
          </app-money-manager-button>
        </span>
      </div>
    </div>
  </div>
</div>

// sarathi-vue-1.0/src/components/Users/USA/EQ/ShortTermInvestment/UnitedStatesOfAmericaSharesShortTermInvestmentHeader.vue
<template>
  <div class="united-states-of-america-shares-short-term-investment-header">
    <div class="services-short-term-investment-header">
      <div class="header">
        <span class="left-items">
          <MoneyManagerButton v-if="oneShareShortTermInvestment"
            :buttonClass="'navigation-button btn-sm'"
            @onButtonClick="onBackButtonClick()"
          >
            <template v-slot:title>
              <i class="fas fa-long-arrow-alt-left"></i> Back
            </template>
          </MoneyManagerButton>
        </span>

        <span class="left-items">
          <MoneyManagerButton
            :buttonClass="isRefreshButtonDisabled ? 'btn-sm' : 'btn-primary btn-sm'"
            :buttonDisabled="isRefreshButtonDisabled"
            @onButtonClick="onRefreshClick()"
          >
            <template v-slot:title>
              <i class="fa fa-refresh"></i> Refresh
            </template>
          </MoneyManagerButton>
        </span>

        <div class="right">
          <span class="right-items">
            <MoneyManagerButton
              :buttonClass="'btn-buy btn-sm'"
              @onButtonClick="onAddShortTermInvestmentClick()"
            >
              <template v-slot:title>
                Add
              </template>
            </MoneyManagerButton>
          </span>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import MoneyManagerButton from "@/components/common/MoneyManagerButton.vue";

export default {
  components: {
    MoneyManagerButton
  },

  props: {
    isRefreshButtonDisabled: {
      type: Boolean,
      required: true
    },

    oneShareShortTermInvestment: {
      type: Boolean,
      default: false
    }
  },

  methods: {
    onBackButtonClick() {
      this.$emit("onBackButtonClick");
    },

    onRefreshClick() {
      this.$emit("onRefreshClick");
    },

    onAddShortTermInvestmentClick() {
      this.$emit("onAddShortTermInvestmentClick");
    }
  }
}
</script>
