// sarathi-ang-1.0/src/app/components/users/BHA/EQ/OneShareDetails/bhaaratha-shares-one-share-details-header/bhaaratha-shares-one-share-details-header.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-bhaaratha-shares-one-share-details-header',
  templateUrl: './bhaaratha-shares-one-share-details-header.component.html',
  styleUrls: ['./bhaaratha-shares-one-share-details-header.component.css']
})
export class BhaarathaSharesOneShareDetailsHeaderComponent implements OnInit {

  @Input() type!: string;
  @Input() isRefreshButtonDisabled!: boolean;
  @Output("onRefreshClick") onRefreshClickEventEmitter = new EventEmitter<any>();

  constructor(
    private router: Router
  ) { }

  ngOnInit(): void {
  }

  onBackButtonClick() {
    this.router.navigate(["/users/BHA/EQ/" + this.type]);
  }

  onRefreshClick() {
    this.onRefreshClickEventEmitter.emit();
  }

}

<div class="bhaaratha-shares-one-share-details-header">
  <div class="services-one-script-details-header">
    <div class="header">
      <span class="left-items">
        <app-money-manager-button
          [buttonClass]="'navigation-button btn-sm'"
          (onButtonClick)="onBackButtonClick()"
        >
          <span title>
            <i class="fas fa-long-arrow-alt-left"></i> Back
          </span>
        </app-money-manager-button>
      </span>

      <span class="left-items">
        <app-money-manager-button
          [buttonClass]="isRefreshButtonDisabled ? 'btn-sm' : 'btn-primary btn-sm'"
          [buttonDisabled]="isRefreshButtonDisabled"
          (onButtonClick)="onRefreshClick()"
        >
          <span title>
            <i class="fa fa-refresh"></i>
          </span>
        </app-money-manager-button>
      </span>

    </div>
  </div>
</div>

// sarathi-vue-1.0/src/components/Users/BHA/EQ/OneShareDetails/BhaarathaSharesOneShareDetailsHeader.vue
<template>
  <div class="bhaaratha-shares-one-share-details-header">
    <div class="services-one-script-details-header">
      <div class="header">
        <span class="left-items">
          <MoneyManagerButton
            :buttonClass="'navigation-button btn-sm'"
            @onButtonClick="onBackButtonClick()"
          >
            <template v-slot:title>
              <i class="fas fa-long-arrow-alt-left"></i> Back
            </template>
          </MoneyManagerButton>
        </span>

        <span class="left-items">
          <MoneyManagerButton
            :buttonClass="isRefreshButtonDisabled ? 'btn-sm' : 'btn-primary btn-sm'"
            :buttonDisabled="isRefreshButtonDisabled"
            @onButtonClick="onRefreshClick()"
          >
            <template v-slot:title>
              <i class="fa fa-refresh"></i>
            </template>
          </MoneyManagerButton>
        </span>

      </div>
    </div>
  </div>
</template>

<script>
import MoneyManagerButton from "@/components/common/MoneyManagerButton.vue";

export default {
  components: {
    MoneyManagerButton
  },

  props: {
    type: {
      type: String,
      requited: true
    },
    isRefreshButtonDisabled: {
      type: Boolean,
      required: true
    }
  },

  methods: {
    onBackButtonClick() {
      this.$router.push("/users/BHA/EQ/" + this.type);
    },

    onRefreshClick() {
      this.$emit("onRefreshClick");
    }
  }
}
</script>
