// sarathi-vue-1.0/src/components/Users/BHA/EQ/Analysis/BhaarathaSharesSectorCategoryAnalysisHeader.vue
<template>
  <div class="bhaaratha-shares-sector-category-analysis-header">
    <div class="services-analysis-sector-category-header">
      <div class="header">
        <span class="left-items">
          <MoneyManagerButton
            :buttonClass="'navigation-button btn-sm'"
            @onButtonClick="onBackButtonClick()"
          >
            <template v-slot:title>
              <i class="fas fa-long-arrow-alt-left"></i> Back
            </template>
          </MoneyManagerButton>
        </span>

        <span class="left-items">
          <MoneyManagerButton
            :buttonClass="isRefreshButtonDisabled ? 'btn-sm' : 'btn-primary btn-sm'"
            :buttonDisabled="isRefreshButtonDisabled"
            @onButtonClick="onRefreshClick()"
          >
            <template v-slot:title>
              Refresh <i class="fa fa-refresh"></i>
            </template>
          </MoneyManagerButton>
        </span>

        <span class="left-items">
          <MoneyManagerDropdown
            :resetDropdown="resetTypeDropdown"
            :disableDropdown="isTypeDropdownDisabled"
            :dropdownList="typeDropdownList"
            :placeholder="typeDropdownPlaceholder"
            @onDropdownSelect="onTypeDropdownSelect($event)"
          ></MoneyManagerDropdown>
        </span>

        <span class="left-items">
          <MoneyManagerDropdown
            v-if="showOneAnalysis"
            :resetDropdown="resetOneAnalysisDropdown"
            :disableDropdown="isTypeDropdownDisabled"
            :dropdownList="oneAnalysisDropdownList"
            :placeholder="'One Analysis'"
            @onDropdownSelect="onOneAnalysisDropdownSelect($event)"
          ></MoneyManagerDropdown>
        </span>

        <div class="right">
          <span class="right-items">
            <MoneyManagerButton
              :buttonClass="isSettingsButtonDisabled ? 'btn-sm' : 'btn-secondary btn-sm'"
              :buttonDisabled="isSettingsButtonDisabled"
              @onButtonClick="onSettingsClick()"
            >
              <template v-slot:title>
                <i class="fa fa-cog"></i>
              </template>
            </MoneyManagerButton>
          </span>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import MoneyManagerButton from "@/components/common/MoneyManagerButton.vue";
import MoneyManagerDropdown from "@/components/common/MoneyManagerDropdown.vue";

export default {
  components: {
    MoneyManagerButton,
    MoneyManagerDropdown
  },

  props: {
    isRefreshButtonDisabled: {
      type: Boolean,
      required: true
    },
    isTypeDropdownDisabled: {
      type: Boolean,
      required: true
    },
    typeDropdownList: {
      type: Array,
      required: true
    },
    typeDropdownPlaceholder: {
      type: String,
      required: true
    },
    isSettingsButtonDisabled: {
      type: Boolean,
      required: true
    },
    oneAnalysisDropdownList: {
      type: Array,
      required: true
    },
    showOneAnalysis: {
      type: Boolean,
      required: true
    }
  },

  data() {
    return {
      resetTypeDropdown: false,
      resetOneAnalysisDropdown: false,
      resetAnalysisServiceDropdown: false,
    }
  },

  methods: {
    onRefreshClick() {
      this.$emit("onRefreshClick");
    },

    onTypeDropdownSelect(dropdownSelected) {
      this.resetTypeDropdown = false;
      switch (dropdownSelected.value) {
        case "Sector":
          this.$emit("onSectorAnalysisSelect");
          break;
        case "Category":
          this.$emit("onCategoryAnalysisSelect");
          break;
      }
    },

    onSettingsClick() {
      this.$emit("onSettingsClick");
    },

    onOneAnalysisDropdownSelect(selectedDropdown) {
      this.$emit("onOneAnalysisDropdownSelect", selectedDropdown);
    },

    onAnalysisServiceDropdownSelect(selectedDropdown) {
      this.resetAnalysisServiceDropdown = false;
      this.$emit("onAnalysisServiceSelect", selectedDropdown);
    },

    onBackButtonClick() {
      this.$emit("onBackButtonClick");
    }
  }
}
</script>

// sarathi-ang-1.0/src/app/components/users/BHA/EQ/Analysis/bhaaratha-shares-sector-category-analysis-header/bhaaratha-shares-sector-category-analysis-header.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';

@Component({
  selector: 'app-bhaaratha-shares-sector-category-analysis-header',
  templateUrl: './bhaaratha-shares-sector-category-analysis-header.component.html',
  styleUrls: ['./bhaaratha-shares-sector-category-analysis-header.component.css']
})
export class BhaarathaSharesSectorCategoryAnalysisHeaderComponent implements OnInit {

  @Input() isRefreshButtonDisabled!: boolean;
  @Input() isTypeDropdownDisabled!: boolean
  @Input() typeDropdownList!: Array<any>;
  @Input() typeDropdownPlaceholder!: string;
  @Input() isSettingsButtonDisabled!: boolean;
  @Input() oneAnalysisDropdownList!: Array<any>;
  @Input() showOneAnalysis!: boolean;
  @Output("onRefreshClick") onRefreshClickEventEmitter = new EventEmitter();
  @Output("onSectorAnalysisSelect") onSectorAnalysisSelectEventEmitter = new EventEmitter();
  @Output("onCategoryAnalysisSelect") onCategoryAnalysisSelectEventEmitter = new EventEmitter();
  @Output("onSettingsClick") onSettingsClickEventEmitter = new EventEmitter();
  @Output("onOneAnalysisDropdownSelect") onOneAnalysisDropdownSelectEventEmitter = new EventEmitter<any>();
  @Output("onAnalysisServiceDropdownSelect") onAnalysisServiceDropdownSelectEventEmitter = new EventEmitter<any>();
  @Output("onBackButtonClick") onBackButtonClickEventEmitter = new EventEmitter();

  resetTypeDropdown: boolean = false;
  resetOneAnalysisDropdown: boolean = false;
  resetAnalysisServiceDropdown: boolean = false;

  constructor() { }

  ngOnInit(): void {
  }

  onRefreshClick() {
    this.onRefreshClickEventEmitter.emit();
  }

  onTypeDropdownSelect(dropdownSelected: any) {
    this.resetTypeDropdown = false;
    switch (dropdownSelected.value) {
      case "Sector":
        this.onSectorAnalysisSelectEventEmitter.emit();
        break;
      case "Category":
        this.onCategoryAnalysisSelectEventEmitter.emit();
        break;
    }
  }

  onSettingsClick() {
    this.onSettingsClickEventEmitter.emit();
  }

  onOneAnalysisDropdownSelect(selectedDropdown: any) {
    this.onOneAnalysisDropdownSelectEventEmitter.emit(selectedDropdown);
  }

  onAnalysisServiceDropdownSelect(selectedDropdown: any) {
    this.resetAnalysisServiceDropdown = false;
    this.onAnalysisServiceDropdownSelectEventEmitter.emit();
  }

  onBackButtonClick() {
    this.onBackButtonClickEventEmitter.emit("selectedDropdown");
  }

}

<div class="bhaaratha-shares-sector-category-analysis-header">
  <div class="services-analysis-sector-category-header">
    <div class="header">
      <span class="left-items">
        <app-money-manager-button
          [buttonClass]="'navigation-button btn-sm'"
          (onButtonClick)="onBackButtonClick()"
        >
          <span title>
            <i class="fas fa-long-arrow-alt-left"></i> Back
          </span>
        </app-money-manager-button>
      </span>
  
      <span class="left-items">
        <app-money-manager-button
          [buttonClass]="isRefreshButtonDisabled ? 'btn-sm' : 'btn-primary btn-sm'"
          [buttonDisabled]="isRefreshButtonDisabled"
          (onButtonClick)="onRefreshClick()"
        >
          <span title>
            Refresh <i class="fa fa-refresh"></i>
          </span>
        </app-money-manager-button>
      </span>

      <span class="left-items">
        <app-money-manager-dropdown
          [resetDropdown]="resetTypeDropdown"
          [disableDropdown]="isTypeDropdownDisabled"
          [dropdownList]="typeDropdownList"
          [placeholder]="typeDropdownPlaceholder"
          (onDropdownSelect)="onTypeDropdownSelect($event)"
        ></app-money-manager-dropdown>
      </span>

      <span class="left-items">
        <app-money-manager-dropdown
          *ngIf="showOneAnalysis"
          [resetDropdown]="resetOneAnalysisDropdown"
          [disableDropdown]="isTypeDropdownDisabled"
          [dropdownList]="oneAnalysisDropdownList"
          [placeholder]="'One Analysis'"
          (onDropdownSelect)="onOneAnalysisDropdownSelect($event)"
        ></app-money-manager-dropdown>
      </span>

      <div class="right">
        <span class="right-items">
          <app-money-manager-button
            [buttonClass]="isSettingsButtonDisabled ? 'btn-sm' : 'btn-secondary btn-sm'"
            [buttonDisabled]="isSettingsButtonDisabled"
            (onButtonClick)="onSettingsClick()"
          >
            <span title>
              <i class="fa fa-cog"></i>
            </span>
          </app-money-manager-button>
        </span>
      </div>
    </div>
  </div>
</div>
