// sarathi-vue-1.0/src/components/Users/USA/EQ/UnitedStatesOfAmericaSharesHome.vue
<template>
  <div class="united-states-of-america-shares-home">
    <UnitedStatesOfAmericaSharesHomeHeader
      :otherServicesDropdownResetDropdown="otherServicesDropdownResetDropdown"
      :otherServicesDropdownList="otherServicesDropdownList"
      @onOtherServicesDropdownSelect="onOtherServicesDropdownSelect($event)"
    ></UnitedStatesOfAmericaSharesHomeHeader>
  </div>
</template>

<script>
import UnitedStatesOfAmericaSharesHomeHeader from "@/components/Users/USA/EQ/Home/UnitedStatesOfAmericaSharesHomeHeader.vue";

export default {
  name: "UnitedStatesOfAmericaSharesHome",
  components: {
    UnitedStatesOfAmericaSharesHomeHeader
  },

  data() {
    return {
      otherServicesDropdownResetDropdown: false,
      otherServicesDropdownList: []
    }
  },

  created() {
    this.otherServicesDropdownList = [
      {
        id: "short-term-investment",
        value: "Short Term Investment"
      }
    ];
  },

  methods: {
    onOtherServicesDropdownSelect(otherServicesDropdownSelected) {
      this.otherServicesDropdownResetDropdown = false;
      this.$router.push("/users/USA/EQ/" + otherServicesDropdownSelected.id);
    }
  }
}
</script>

// sarathi-ang-1.0/src/app/components/users/USA/EQ/united-states-of-america-shares-home/united-states-of-america-shares-home.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-united-states-of-america-shares-home',
  templateUrl: './united-states-of-america-shares-home.component.html',
  styleUrls: ['./united-states-of-america-shares-home.component.css']
})
export class UnitedStatesOfAmericaSharesHomeComponent implements OnInit {

  otherServicesDropdownResetDropdown: boolean = false;
  otherServicesDropdownList: Array<any> = [];

  constructor(
    private router: Router
  ) { }

  ngOnInit(): void {
    this.otherServicesDropdownList = [
      {
        id: "short-term-investment",
        value: "Short Term Investment"
      }
    ];
  }

  onOtherServicesDropdownSelect(otherServicesDropdownSelected: any) {
    this.otherServicesDropdownResetDropdown = false;
    this.router.navigate(["/users/USA/EQ/" + otherServicesDropdownSelected.id]);
  }
}

<div class="bhaaratha-shares-home">
  <app-bhaaratha-shares-home-header
    [otherServicesDropdownResetDropdown]="otherServicesDropdownResetDropdown"
    [otherServicesDropdownList]="otherServicesDropdownList"
    (onOtherServicesDropdownSelect)="onOtherServicesDropdownSelect($event)"
  ></app-bhaaratha-shares-home-header>
</div>
