// sarathi-vue-1.0/src/components/Users/BHA/EQ/BhaarathaSharesBought.vue
<template>
  <div class="bhaaratha-shares-bought">
    <BhaarathaSharesBoughtSoldHeader
      :type="type"
      :isSearchFieldDisabled="isSearchFieldDisabled"
      :isSearchButtonDisabled="isSearchButtonDisabled"
      :isRefreshButtonDisabled="isRefreshButtonDisabled"
      :isHeaderDropdownDisabled="isHeaderDropdownDisabled"
      :headerDropdownList="headerDropdownList"
      :headerDropdownPlaceholder="headerDropdownPlaceholder"
      :isLongTermOnly="isLongTermOnly"
      :isSettingsButtonDisabled="isSettingsButtonDisabled"
      @onSearchClick="onSearchClick($event)"
      @onRefreshClick="onRefreshClick($event)"
      @onConsolidatedSelect="onConsolidatedSelect($event)"
      @onNonConsolidatedSelect="onNonConsolidatedSelect($event)"
      @onSettingsClick="onSettingsClick()"
    ></BhaarathaSharesBoughtSoldHeader>
    <BhaarathaSharesBoughtAndSoldData
      :type="'bought'"
      :loading="loading"
      :noRecords="noRecords"
      :bhaarathaSharesList="bhaarathaSharesList"
      :bhaarathaSharesTotal="bhaarathaSharesTotal"
    ></BhaarathaSharesBoughtAndSoldData>

    <BhaarathaSharesBoughtSettingsModal
      v-if="showSettings"
      :longTermRadioList="longTermRadioList"
      :longTermRadioDefault="longTermRadioDefault"
      @onCloseSettingsClick="onCloseSettingsClick()"
      @onConfirmSettingsClick="onConfirmSettingsClick($event)"
    ></BhaarathaSharesBoughtSettingsModal>

    <ErrorModal
      v-if="showError"
      :errorMessage="errorMessage"
    >
      <template v-slot:header>
        <h3 class="mm-error-modal-title">Error!!</h3>
        <span>
          <MoneyManagerButton
            :buttonClass="'btn-close'"
            @onButtonClick="closeError()"
          >
          </MoneyManagerButton>
        </span>
      </template>
    </ErrorModal>

  </div>
</template>

<script>
import BhaarathaSharesBoughtSettingsModal from "@/components/Users/BHA/EQ/BoughtSold/BhaarathaSharesBoughtSettingsModal.vue";
import ErrorModal from "@/components/common/ErrorModal.vue";
import MoneyManagerButton from "@/components/common/MoneyManagerButton.vue";
import BhaarathaSharesBoughtSoldHeader from '@/components/Users/BHA/EQ/BoughtSold/BhaarathaSharesBoughtSoldHeader.vue';
import BhaarathaSharesBoughtAndSoldData from '@/components/Users/BHA/EQ/BoughtSold/BhaarathaSharesBoughtAndSoldData.vue';
import services from "@/assets/services/services.json";
import axios from "axios";


export default {
  components: {
    BhaarathaSharesBoughtSettingsModal,
    ErrorModal,
    MoneyManagerButton,
    BhaarathaSharesBoughtSoldHeader,
    BhaarathaSharesBoughtAndSoldData
},

  data() {
    return {
      type: "bought",
      isSearchFieldDisabled: false,
      isSearchButtonDisabled: false,
      isRefreshButtonDisabled: false,
      isHeaderDropdownDisabled: false,
      headerDropdownList: [
        {
          id: "1",
          value: "Consolidated"
        },
        {
          id: "2",
          value: "Non-Consolidated"
        }
      ],
      headerDropdownPlaceholder: "Consolidated",
      isNonConsolidated: false,
      isLongTermOnly: false,
      searchText: "",
      loading: true,
      noRecords: false,
      bhaarathaSharesList: [],
      bhaarathaSharesTotal: {},
      isSettingsButtonDisabled: false,
      // Error/Success Modal
      showError: false,
      errorMessage: "",
      // Bought shares settings
      longTermRadioList: [
        {
          id: "Y",
          value: "Yes"
        },
        {
          id: "N",
          value: "No"
        }
      ],
      longTermRadioDefault: {},
      showSettings: false
    }
  },

  created() {
    this.longTermRadioDefault = this.longTermRadioList[1];
    this.isLongTermOnly = this.longTermRadioDefault.value === "Yes" ? true : false;
    this.getBoughtShares();
  },

  methods: {
    getBoughtShares() {
      this.loading = true;
      this.isSearchFieldDisabled = true;
      this.isRefreshButtonDisabled = true;
      this.isHeaderDropdownDisabled = true;
      this.noRecords = false;
      this.isSettingsButtonDisabled = true;

      axios.get(services.bhaarathaSharesShares + "?type=bought&searchTerm=" + this.searchText + "&isNonConsolidated=" + this.isNonConsolidated + "&isLongTermOnly=" + this.isLongTermOnly).then(response => {
        if (response.status === 204) {
          this.noRecords = true;
          this.loading = false;
          //
          this.isSearchFieldDisabled = false;
          this.isRefreshButtonDisabled = false;
          this.isHeaderDropdownDisabled = false;
          this.isSettingsButtonDisabled = false;
        } else {
          this.bhaarathaSharesList = response.data.bhaarathaSharesList;
          this.bhaarathaSharesTotal = response.data.bhaarathaSharesTotal
          this.loading = false;
          //
          this.isSearchFieldDisabled = false;
          this.isRefreshButtonDisabled = false;
          this.isHeaderDropdownDisabled = false;
          this.loading = false;
          this.isSettingsButtonDisabled = false;
        }
      }).catch(error => {
        error.response.data.error.map((e) => {
          this.errorMessage = e.errorMessage;
          this.showError = true;
        });
      });
    },

    onSearchClick(bhaarathaShares) {
      this.searchText = bhaarathaShares.searchText;
      this.isNonConsolidated = bhaarathaShares.isNonConsolidated;
      this.isLongTermOnly = bhaarathaShares.isLongTermOnly;
      this.getBoughtShares();
    },

    onRefreshClick(bhaarathaShares) {
      this.searchText = bhaarathaShares.searchText;
      this.isNonConsolidated = bhaarathaShares.isNonConsolidated;
      this.isLongTermOnly = bhaarathaShares.isLongTermOnly;
      this.getBoughtShares();
    },

    onConsolidatedSelect(bhaarathaShares) {
      this.searchText = bhaarathaShares.searchText;
      this.isNonConsolidated = bhaarathaShares.isNonConsolidated;
      this.isLongTermOnly = bhaarathaShares.isLongTermOnly;
      this.getBoughtShares();
    },

    onNonConsolidatedSelect(bhaarathaShares) {
      this.searchText = bhaarathaShares.searchText;
      this.isNonConsolidated = bhaarathaShares.isNonConsolidated;
      this.isLongTermOnly = bhaarathaShares.isLongTermOnly;
      this.getBoughtShares();
    },

    onSettingsClick() {
      this.showSettings = true;
    },

    onCloseSettingsClick() {
      this.showSettings = false;
    },

    onConfirmSettingsClick(longTermRadio) {
      this.isLongTermOnly = longTermRadio.value === "Yes" ? true : false;
      this.getBoughtShares();
      this.showSettings = false;
      this.longTermRadioDefault = longTermRadio;
    },

    closeError() {
      this.showError = false;
      this.errorMessage = "";
    }
  }
}
</script>

// sarathi-ang-1.0/src/app/components/users/BHA/EQ/bhaaratha-shares-bought/bhaaratha-shares-bought.component.ts
import { HttpClient } from '@angular/common/http';
import { Component, OnInit } from '@angular/core';
import services from 'src/assets/services/services.json';

@Component({
  selector: 'app-bhaaratha-shares-bought',
  templateUrl: './bhaaratha-shares-bought.component.html',
  styleUrls: ['./bhaaratha-shares-bought.component.css']
})
export class BhaarathaSharesBoughtComponent implements OnInit {

  type: string = "bought";
  isSearchFieldDisabled: boolean = false;
  isSearchButtonDisabled: boolean = false;
  isRefreshButtonDisabled: boolean = false;
  isHeaderDropdownDisabled: boolean = false;
  headerDropdownList: Array<any> =
  [
    {
      id: "1",
      value: "Consolidated"
    },
    {
      id: "2",
      value: "Non-Consolidated"
    }
  ];
  headerDropdownPlaceholder: string = "Consolidated";
  isNonConsolidated: boolean = false;
  isLongTermOnly: boolean = false;
  searchText: string = "";
  loading: boolean = true;
  noRecords: boolean = false;
  bhaarathaSharesList: Array<any> = [];
  bhaarathaSharesTotal: Object = {};
  isSettingsButtonDisabled: boolean = false;
  // Error/Success Modal
  showError: boolean  = false;
  errorMessage: string = "";
  // Bought shares settings
  longTermRadioList: Array<any> =
  [
    {
      id: "Y",
      value: "Yes"
    },
    {
      id: "N",
      value: "No"
    }
  ];
  longTermRadioDefault: any = {};
  showSettings: boolean = false;

  constructor(
    private http: HttpClient
  ) { }

  ngOnInit(): void {
    this.longTermRadioDefault = this.longTermRadioList[1];
    this.isLongTermOnly = this.longTermRadioDefault.value === "Yes" ? true : false;
    this.getBoughtShares();
  }

  getBoughtShares() {
    this.loading = true;
    this.isSearchFieldDisabled = true;
    this.isRefreshButtonDisabled = true;
    this.isHeaderDropdownDisabled = true;
    this.noRecords = false;
    this.isSettingsButtonDisabled = true;

    this.http.get(services.bhaarathaSharesShares + "?type=bought&searchTerm=" + this.searchText + "&isNonConsolidated=" + this.isNonConsolidated + "&isLongTermOnly=" + this.isLongTermOnly).subscribe((response: any) => {
      if (response === null) {
        this.noRecords = true;
        this.loading = false;
        //
        this.isSearchFieldDisabled = false;
        this.isRefreshButtonDisabled = false;
        this.isHeaderDropdownDisabled = false;
        this.isSettingsButtonDisabled = false;
      } else {
        this.bhaarathaSharesList = response.bhaarathaSharesList;
        this.bhaarathaSharesTotal = response.bhaarathaSharesTotal
        this.loading = false;
        //
        this.isSearchFieldDisabled = false;
        this.isRefreshButtonDisabled = false;
        this.isHeaderDropdownDisabled = false;
        this.loading = false;
        this.isSettingsButtonDisabled = false;
      }
    }, error => {
      error.error.error.map((e: any) => {
        this.errorMessage = e.errorMessage;
        this.showError = true;
      });
    });
  }

  onSearchClick(bhaarathaShares: any) {
    this.searchText = bhaarathaShares.searchText;
    this.isNonConsolidated = bhaarathaShares.isNonConsolidated;
    this.isLongTermOnly = bhaarathaShares.isLongTermOnly;
    this.getBoughtShares();
  }

  onRefreshClick(bhaarathaShares: any) {
    this.searchText = bhaarathaShares.searchText;
    this.isNonConsolidated = bhaarathaShares.isNonConsolidated;
    this.isLongTermOnly = bhaarathaShares.isLongTermOnly;
    this.getBoughtShares();
  }

  onConsolidatedSelect(bhaarathaShares: any) {
    this.searchText = bhaarathaShares.searchText;
    this.isNonConsolidated = bhaarathaShares.isNonConsolidated;
    this.isLongTermOnly = bhaarathaShares.isLongTermOnly;
    this.getBoughtShares();
  }

  onNonConsolidatedSelect(bhaarathaShares: any) {
    this.searchText = bhaarathaShares.searchText;
    this.isNonConsolidated = bhaarathaShares.isNonConsolidated;
    this.isLongTermOnly = bhaarathaShares.isLongTermOnly;
    this.getBoughtShares();
  }
  
  onSettingsClick() {
    this.showSettings = true;
  }
  
  onCloseSettingsClick() {
    this.showSettings = false;
  }
  
  onConfirmSettingsClick(longTermRadio: any) {
    this.isLongTermOnly = longTermRadio.value === "Yes" ? true : false;
    this.getBoughtShares();
    this.showSettings = false;
    this.longTermRadioDefault = longTermRadio;
  }

  closeError() {
    this.showError = false;
    this.errorMessage = "";
  }
}

<div class="bhaaratha-shares-bought">
  <app-bhaaratha-shares-bought-sold-header
    [type]="type"
    [isSearchFieldDisabled]="isSearchFieldDisabled"
    [isSearchButtonDisabled]="isSearchButtonDisabled"
    [isRefreshButtonDisabled]="isRefreshButtonDisabled"
    [isHeaderDropdownDisabled]="isHeaderDropdownDisabled"
    [headerDropdownList]="headerDropdownList"
    [headerDropdownPlaceholder]="headerDropdownPlaceholder"
    [isLongTermOnly]="isLongTermOnly"
    [isSettingsButtonDisabled]="isSettingsButtonDisabled"
    (onSearchClick)="onSearchClick($event)"
    (onRefreshClick)="onRefreshClick($event)"
    (onConsolidatedSelect)="onConsolidatedSelect($event)"
    (onNonConsolidatedSelect)="onNonConsolidatedSelect($event)"
    (onSettingsClick)="onSettingsClick()"
  ></app-bhaaratha-shares-bought-sold-header>

  <app-bhaaratha-shares-bought-and-sold-data
    [type]="'bought'"
    [loading]="loading"
    [noRecords]="noRecords"
    [bhaarathaSharesList]="bhaarathaSharesList"
    [bhaarathaSharesTotal]="bhaarathaSharesTotal"
  ></app-bhaaratha-shares-bought-and-sold-data>

  <app-bhaaratha-shares-bought-settings-modal
    *ngIf="showSettings"
    [longTermRadioList]="longTermRadioList"
    [longTermRadioDefault]="longTermRadioDefault"
    (onCloseSettingsClick)="onCloseSettingsClick()"
    (onConfirmSettingsClick)="onConfirmSettingsClick($event)"
  ></app-bhaaratha-shares-bought-settings-modal>

  <app-error-modal
    *ngIf="showError"
    (closeError)="closeError()"
  >
    <span body>
      {{ errorMessage }}
    </span>
  </app-error-modal>
</div>
