// sarathi-vue-1.0/src/components/Users/BHA/EQ/OneShareDetails/BhaarathaSharesOneShareDetailsData.vue
<template>
  <div class="bhaaratha-shares-one-share-details-data">
    <div class="services-one-script-details-data">
      <div class="spinner" v-if="loading">
        <MoneyManagerLoading></MoneyManagerLoading>
      </div>
      <div v-if="noRecords" class="no-records">
        ******* NO RECORDS *******
      </div>
      <div v-if="!loading && !noRecords">
        <div class="services-one-script-details-table">
          <div class="mm-table">
            <table class="mm-table-data">
              <thead>
                <tr>
                  <th>SCRIPT NAME</th>
                  <th>PURCHASE PRICE</th>
                  <th>PURCHASE TOTAL</th>
                  <th>PURCHASE NET</th>
                  <th>SELL PRICE</th>
                  <th>SELL TOTAL</th>
                  <th>SELL NET</th>
                  <th>P/L</th>
                  <th>P/L (%)</th>
                  <th>NET P/L</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="bhaarathaShares of bhaarathaSharesList" :key="bhaarathaShares.id">
                  <td>{{ bhaarathaShares.scriptName }}</td>
                  <td>{{ bhaarathaShares.purchasePrice }}</td>
                  <td>{{ bhaarathaShares.purchaseTotal }}</td>
                  <td>{{ bhaarathaShares.purchaseNetPricePerUnit }}</td>
                  <td>{{ bhaarathaShares.sellPrice }}</td>
                  <td>{{ bhaarathaShares.sellTotal }}</td>
                  <td>{{ bhaarathaShares.sellNetPricePerUnit }}</td>
                  <td v-highlight-by-numbers>{{ bhaarathaShares.totalProfitLoss }}</td>
                  <td v-highlight-by-numbers>{{ bhaarathaShares.totalProfitLossPercentage }}%</td>
                  <td v-highlight-by-numbers>{{ bhaarathaShares.netProfitLossPerUnit }}</td>
                </tr>
              </tbody>
              <tfoot>
                <tr>
                  <td>TOTAL</td>
                  <td>{{ bhaarathaSharesTotal.purchasePrice }}</td>
                  <td>{{ bhaarathaSharesTotal.purchaseTotal }}</td>
                  <td>{{ bhaarathaSharesTotal.purchaseNetPricePerUnit }}</td>
                  <td>{{ bhaarathaSharesTotal.sellPrice }}</td>
                  <td>{{ bhaarathaSharesTotal.sellTotal }}</td>
                  <td>{{ bhaarathaSharesTotal.sellNetPricePerUnit }}</td>
                  <td v-highlight-by-numbers>{{ bhaarathaSharesTotal.totalProfitLoss }}</td>
                  <td v-highlight-by-numbers>{{ bhaarathaSharesTotal.totalProfitLossPercentage }}%</td>
                  <td v-highlight-by-numbers>{{ bhaarathaSharesTotal.netProfitLossPerUnit }}</td>
                </tr>
              </tfoot>
            </table>
          </div>
          <div class="services-one-script-details-content">
            Your portfolio has provided a total return of <span v-highlight-by-numbers="'bold'">{{ bhaarathaSharesTotal.totalProfitLoss }}</span> (<span v-highlight-by-numbers="'bold'">{{ bhaarathaSharesTotal.totalProfitLossPercentage }}%</span>) and per unit net return of <span v-highlight-by-numbers="'bold'">{{ bhaarathaSharesTotal.netProfitLossPerUnit }}</span>
          </div>
          <hr />
          <div class="services-one-script-exchange-details">
            <div class="services-one-script-exchange-radio">
              <MoneyManagerRadio
                :resetRadio="false"
                :radioList="stockExchangeRadioList"
                :radioDefault="stockExchangeRadioDefault"
                @onRadioSelect="onStockExchangeSelect($event)"
              ></MoneyManagerRadio>
            </div>

            <div class="services-one-script-exchange-content">
              <BhaarathaSharesOneShareDetailsBseNseData
                v-if="stockExchangeSelected === 'BSE'"
                :oneShareDetails="bseOneShareDetails"
              ></BhaarathaSharesOneShareDetailsBseNseData>
              <BhaarathaSharesOneShareDetailsBseNseData
                v-if="stockExchangeSelected === 'NSE'"
                :oneShareDetails="nseOneShareDetails"
              ></BhaarathaSharesOneShareDetailsBseNseData>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import MoneyManagerLoading from "@/components/common/MoneyManagerLoading.vue";
import MoneyManagerRadio from "@/components/common/MoneyManagerRadio.vue";
import BhaarathaSharesOneShareDetailsBseNseData from "@/components/Users/BHA/EQ/OneShareDetails/BhaarathaSharesOneShareDetailsBseNseData.vue"

export default {
  components: {
    MoneyManagerLoading,
    MoneyManagerRadio,
    BhaarathaSharesOneShareDetailsBseNseData
  },

  props: {
    loading: {
      type: Boolean,
      required: true
    },
    noRecords: {
      type: Boolean,
      required: true
    },
    pageRefreshed: {
      type: Boolean,
      required: true
    },
    bhaarathaSharesList: {
      type: Array,
      required: true
    },
    bhaarathaSharesTotal: {
      type: Object,
      required: true
    },
    bseOneShareDetails: {
      type: Object,
      required: true
    },
    nseOneShareDetails: {
      type: Object,
      required: true
    }
  },

  data () {
    return {
     stockExchangeRadioList: [],
     stockExchangeRadioDefault: {},
     stockExchangeSelected: ""
   }
  },

  created() {
    this.getStockExchangeRadioList();
    this.getStockExchangeRadioDefault();
    this.stockExchangeSelected = "BSE";
  },

  watch: {
    pageRefreshed(newValue) {
      if (newValue) {
        this.getStockExchangeRadioList();
        this.getStockExchangeRadioDefault();
        this.stockExchangeSelected = "BSE";
      }
    }
  },

  methods: {
    getStockExchangeRadioList() {
      this.stockExchangeRadioList = [
        {
          id: "bse",
          value: "BSE"
        },
        {
          id: "nse",
          value: "NSE"
        }
      ];
    },

    getStockExchangeRadioDefault() {
      this.stockExchangeRadioDefault = this.stockExchangeRadioList[0];
    },

    onStockExchangeSelect(stockExchange) {
      this.stockExchangeSelected = stockExchange.value
    }
  }
}
</script>

// sarathi-ang-1.0/src/app/components/users/BHA/EQ/OneShareDetails/bhaaratha-shares-one-share-details-data/bhaaratha-shares-one-share-details-data.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-bhaaratha-shares-one-share-details-data',
  templateUrl: './bhaaratha-shares-one-share-details-data.component.html',
  styleUrls: ['./bhaaratha-shares-one-share-details-data.component.css']
})
export class BhaarathaSharesOneShareDetailsDataComponent implements OnInit {

  @Input() loading!: boolean;
  @Input() noRecords!: boolean;
  @Input() pageRefreshed!: boolean;
  @Input() bhaarathaSharesList!: Array<any>;
  @Input() bhaarathaSharesTotal!: any;
  @Input() bseOneShareDetails!: any;
  @Input() nseOneShareDetails!: any;

  stockExchangeRadioList: Array<any> = [];
  stockExchangeRadioDefault: any;
  stockExchangeSelected: string = "";

  constructor() { }

  ngOnInit(): void {
    this.getStockExchangeRadioList();
    this.getStockExchangeRadioDefault();
    this.stockExchangeSelected = "BSE";
  }

  ngOnChanges(): void {
    if (this.pageRefreshed) {
      this.getStockExchangeRadioList();
      this.getStockExchangeRadioDefault();
      this.stockExchangeSelected = "BSE";
    }
  }

  getStockExchangeRadioList() {
    this.stockExchangeRadioList = [
      {
        id: "bse",
        value: "BSE"
      },
      {
        id: "nse",
        value: "NSE"
      }
    ];
  }

  getStockExchangeRadioDefault() {
    this.stockExchangeRadioDefault = this.stockExchangeRadioList[0];
  }

  onStockExchangeSelect(stockExchange: any) {
    this.stockExchangeSelected = stockExchange.value;
  }

}

<div class="bhaaratha-shares-one-share-details-data">
  <div class="services-one-script-details-data">
    <div class="spinner" *ngIf="loading">
      <app-money-manager-loading></app-money-manager-loading>
    </div>
    <div *ngIf="noRecords" class="no-records">
      ******* NO RECORDS *******
    </div>
    <div *ngIf="!loading && !noRecords">
      <div class="services-one-script-details-table">
        <div class="mm-table">
          <table class="mm-table-data">
            <thead>
              <tr>
                <th>SCRIPT NAME</th>
                <th>PURCHASE PRICE</th>
                <th>PURCHASE TOTAL</th>
                <th>PURCHASE NET</th>
                <th>SELL PRICE</th>
                <th>SELL TOTAL</th>
                <th>SELL NET</th>
                <th>P/L</th>
                <th>P/L (%)</th>
                <th>NET P/L</th>
              </tr>
            </thead>
            <tbody>
              <tr *ngFor="let bhaarathaShares of bhaarathaSharesList">
                <td>{{ bhaarathaShares.scriptName }}</td>
                <td>{{ bhaarathaShares.purchasePrice }}</td>
                <td>{{ bhaarathaShares.purchaseTotal }}</td>
                <td>{{ bhaarathaShares.purchaseNetPricePerUnit }}</td>
                <td>{{ bhaarathaShares.sellPrice }}</td>
                <td>{{ bhaarathaShares.sellTotal }}</td>
                <td>{{ bhaarathaShares.sellNetPricePerUnit }}</td>
                <td appHighlightByNumbers [value]="bhaarathaShares.totalProfitLoss">{{ bhaarathaShares.totalProfitLoss }}</td>
                <td appHighlightByNumbers [value]="bhaarathaShares.totalProfitLossPercentage">{{ bhaarathaShares.totalProfitLossPercentage }}%</td>
                <td appHighlightByNumbers [value]="bhaarathaShares.netProfitLossPerUnit">{{ bhaarathaShares.netProfitLossPerUnit }}</td>
              </tr>
            </tbody>
            <tfoot>
              <tr>
                <td>TOTAL</td>
                <td>{{ bhaarathaSharesTotal.purchasePrice }}</td>
                <td>{{ bhaarathaSharesTotal.purchaseTotal }}</td>
                <td>{{ bhaarathaSharesTotal.purchaseNetPricePerUnit }}</td>
                <td>{{ bhaarathaSharesTotal.sellPrice }}</td>
                <td>{{ bhaarathaSharesTotal.sellTotal }}</td>
                <td>{{ bhaarathaSharesTotal.sellNetPricePerUnit }}</td>
                <td appHighlightByNumbers [value]="bhaarathaSharesTotal.totalProfitLoss">{{ bhaarathaSharesTotal.totalProfitLoss }}</td>
                <td appHighlightByNumbers [value]="bhaarathaSharesTotal.totalProfitLossPercentage">{{ bhaarathaSharesTotal.totalProfitLossPercentage }}%</td>
                <td appHighlightByNumbers [value]="bhaarathaSharesTotal.netProfitLossPerUnit">{{ bhaarathaSharesTotal.netProfitLossPerUnit }}</td>
              </tr>
            </tfoot>
          </table>
        </div>
        <div class="services-one-script-details-content">
          Your portfolio has provided a total return of <span appHighlightByNumbers [value]="bhaarathaSharesTotal.totalProfitLoss" [fontWeight]="'bold'">{{ bhaarathaSharesTotal.totalProfitLoss }}</span> (<span appHighlightByNumbers [value]="bhaarathaSharesTotal.totalProfitLossPercentage" [fontWeight]="'bold'">{{ bhaarathaSharesTotal.totalProfitLossPercentage }}%</span>) and per unit net return of <span appHighlightByNumbers [value]="bhaarathaSharesTotal.netProfitLossPerUnit" [fontWeight]="'bold'">{{ bhaarathaSharesTotal.netProfitLossPerUnit }}</span>
        </div>
        <hr />
        <div class="services-one-script-exchange-details">
          <div class="services-one-script-exchange-radio">
            <app-money-manager-radio
              [resetRadio]="false"
              [radioList]="stockExchangeRadioList"
              [radioDefault]="stockExchangeRadioDefault"
              [radioName]="'bhaarathaSharesOneShareDetailsStockExchangeRadio'"
              (onRadioSelect)="onStockExchangeSelect($event)"
            ></app-money-manager-radio>
          </div>
  
          <div class="services-one-script-exchange-content">
            <app-bhaaratha-shares-one-share-details-bse-nse-data
              *ngIf="stockExchangeSelected === 'BSE'"
              [oneShareDetails]="bseOneShareDetails"
            ></app-bhaaratha-shares-one-share-details-bse-nse-data>
            <app-bhaaratha-shares-one-share-details-bse-nse-data
              *ngIf="stockExchangeSelected === 'NSE'"
              [oneShareDetails]="nseOneShareDetails"
            ></app-bhaaratha-shares-one-share-details-bse-nse-data>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
