// sarathi-ang-1.0/src/app/components/common/DatePicker/money-manager-date-picker-month-view/money-manager-date-picker-month-view.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';

@Component({
  selector: 'app-money-manager-date-picker-month-view',
  templateUrl: './money-manager-date-picker-month-view.component.html',
  styleUrls: ['./money-manager-date-picker-month-view.component.css']
})
export class MoneyManagerDatePickerMonthViewComponent implements OnInit {

  @Input() calendarMonthsList!: Array<any>;
  @Input() displayMonth!: string;
  @Output("onMonthSelect") monthSelectEventEmitter = new EventEmitter<string>();

  constructor() { }

  ngOnInit(): void {
  }

  onMonthSelect(month: string) {
    this.monthSelectEventEmitter.emit(month);
  }
}

<div class="date-picker-month-view">
  <div class="date-picker-top-container">
    <span class="date-picker-top">{{ displayMonth }}</span>
    <div class="date-picker-table">
      <div class="date-picker-month-heading">MONTH</div>
      <table>
        <tr *ngFor="let calendarMonth of calendarMonthsList">
          <td
            *ngFor="let monthList of calendarMonth.monthList"
            [id]="[displayMonth === monthList.month ? 'date-picker-month-id' : '' ]"
            class="date-picker-month"
            (click)="onMonthSelect(monthList.month)"
          >
            {{ monthList.month }}
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>

// sarathi-vue-1.0/src/components/common/DatePicker/MoneyManagerDatePickerMonthView.vue
<template>
  <div class="date-picker-month-view">
    <div class="date-picker-top-container">
      <span class="date-picker-top">{{ displayMonth }}</span>
      <div class="date-picker-table">
        <div class="date-picker-month-heading">MONTH</div>
        <table>
          <tr v-for="calendarMonth of calendarMonthsList" :key="calendarMonth.rowId">
            <td
              v-for="monthList of calendarMonth.monthList"
              :key="monthList.monthId" 
              :id="[displayMonth === monthList.month ? 'date-picker-month-id' : '' ]"
              class="date-picker-month"
              @click="onMonthSelect(monthList.month)"
            >
              {{ monthList.month }}
            </td>
          </tr>
        </table>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    calendarMonthsList: {
      type: Array,
      required: true
    },
    displayMonth: {
      type: String,
      required: true
    }
  },

  methods: {
    onMonthSelect(month) {
      this.$emit("onMonthSelect", month);
    }
  }
}
</script>
