// sarathi-ang-1.0/src/app/components/common/DatePicker/money-manager-date-picker-date-view/money-manager-date-picker-date-view.component.ts
import { KeyValue } from '@angular/common';
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';

@Component({
  selector: 'app-money-manager-date-picker-date-view',
  templateUrl: './money-manager-date-picker-date-view.component.html',
  styleUrls: ['./money-manager-date-picker-date-view.component.css']
})
export class MoneyManagerDatePickerDateViewComponent implements OnInit {

  @Input() dayMap!: Map<any, any>;
  @Input() displayMonth!: string;
  @Input() displayYear!: string;
  @Input() calendarDaysList!: Array<any>;
  @Input() selectedDate!: string;
  @Input() selectedMonth!: string;
  @Input() selectedYear!: string;
  @Output("onDateSelect") dateSelectEventEmitter = new EventEmitter<any>();
  @Output("onPreviousMonth") previousMonthEventEmitter = new EventEmitter<any>();
  @Output("onNextMonth") nextMonthEventEmitter = new EventEmitter<any>();
  @Output("onMonthClick") monthClickEventEmitter = new EventEmitter<any>();
  @Output("onYearClick") yearClickEventEmitter = new EventEmitter<any>();

  constructor() { }

  ngOnInit(): void {
  }

  onDateClick(date: string) {
    if (date !== "") {
      this.dateSelectEventEmitter.emit({date: date, month: this.displayMonth, year: this.displayYear});
    }
  }

  onPreviousMonthClick() {
    this.previousMonthEventEmitter.emit();
  }

  onNextMonthClick() {
    this.nextMonthEventEmitter.emit();
  }

  onMonthClick() {
    this.monthClickEventEmitter.emit();
  }

  onYearClick() {
    this.yearClickEventEmitter.emit();
  }

  originalOrder = (a: KeyValue<string, any>, b: KeyValue<string, any>): number => {
    return 0;
  }
}

<div class="date-picker-date-view">
  <div class="date-picker-top-container">
    <span
      class="date-picker-top"
      (click)="onPreviousMonthClick()"
    ><i class="fas fa-caret-left"></i></span>
    <span
      class="date-picker-top"
      (click)="onMonthClick()"
    >{{ displayMonth }}</span>
    <span
      class="date-picker-top"
      (click)="onYearClick()"
    >{{ displayYear }}</span>
    <span
      class="date-picker-top"
      (click)="onNextMonthClick()"
    ><i class="fas fa-caret-right"></i></span>
  </div>
  <div class="date-picker-table">
    <table>
      <tr>
        <td *ngFor="let map of dayMap | keyvalue: originalOrder"> {{ map.value }} </td>
      </tr>
      <tr *ngFor="let calendarDay of calendarDaysList">
        <td
          *ngFor="let weeklyDay of calendarDay.weeklyDaysList"
          [id]="[weeklyDay.value === selectedDate && displayMonth === selectedMonth && displayYear === selectedYear ? 'date-picker-date-id' : '']"
          [ngClass]="[weeklyDay.value !== '' ? 'date-picker-date' : '']"
          (click)="onDateClick(weeklyDay.value)"
        >
          {{ weeklyDay.value }}
        </td>
      </tr>
    </table>
  </div>
</div>

// sarathi-vue-1.0/src/components/common/DatePicker/MoneyManagerDatePickerDateView.vue
<template>
  <div class="date-picker-date-view">
    <div class="date-picker-top-container">
      <span
        class="date-picker-top"
        @click="onPreviousMonthClick()"
      ><i class="fas fa-caret-left"></i></span>
      <span
        class="date-picker-top"
        @click="onMonthClick()"
      >{{ displayMonth }}</span>
      <span
        class="date-picker-top"
        @click="onYearClick()"
      >{{ displayYear }}</span>
      <span
        class="date-picker-top"
        @click="onNextMonthClick()"
      ><i class="fas fa-caret-right"></i></span>
    </div>
    <div class="date-picker-table">
      <table>
        <tr>
          <td v-for="[key, value] of dayMap" :key="key" class="date-picker-day">{{ value }}</td>
        </tr>
        <tr v-for="calendarDay of calendarDaysList" :key="calendarDay.weekId">
          <td
            v-for="weeklyDay of calendarDay.weeklyDaysList" :key="weeklyDay.id"
            :id="[weeklyDay.value === selectedDate && displayMonth === selectedMonth && displayYear === selectedYear ? 'date-picker-date-id' : '']"
            :class="[weeklyDay.value !== '' ? 'date-picker-date' : '']"
            @click="onDateClick(weeklyDay.value)"
          >
            {{ weeklyDay.value }}
          </td>
        </tr>
      </table>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    dayMap: {
      type: Map,
      required: true
    },
    displayMonth: {
      type: String,
      required: true
    },
    displayYear: {
      type: String,
      required: true
    },
    calendarDaysList: {
      type: Array,
      required: true
    },
    selectedDate: {
      type: String,
      required: true
    },
    selectedMonth: {
      type: String,
      required: true
    },
    selectedYear: {
      type: String,
      required: true
    }
  },

  methods: {
    onDateClick(date) {
      if (date !== "") {
        this.$emit("onDateSelect", {date: date, month: this.displayMonth, year: this.displayYear});
      }
    },

    onPreviousMonthClick() {
      this.$emit("onPreviousMonth");
    },

    onNextMonthClick() {
      this.$emit("onNextMonth");
    },

    onMonthClick() {
      this.$emit("onMonthClick");
    },

    onYearClick() {
      this.$emit("onYearClick");
    }
  }
}
</script>
