// sarathi-vue-1.0/src/components/Users/USA/EQ/Analysis/UnitedStatesOfAmericaSharesAnalysisServicesHeader.vue
<template>
  <div class="united-states-of-america-shares-analysis-services-header">
    <div class="services-analysis-header">
      <MoneyManagerDropdown
        :resetDropdown="resetAnalysisServicesDropdown"
        :dropdownList="analysisServicesDropdownList"
        :placeholder="'Analysis Services'"
        @onDropdownSelect="onAnalysisServicesDropdownSelect($event)"
      ></MoneyManagerDropdown>
    </div>
  </div>
</template>

<script>
import MoneyManagerDropdown from "@/components/common/MoneyManagerDropdown.vue";

export default {
  components: {
    MoneyManagerDropdown
  },

  props: {
    resetAnalysisServicesDropdown: {
      type: Boolean,
      required: true
    },
    analysisServicesDropdownList: {
      type: Array,
      required: true
    }
  },

  methods: {
    onAnalysisServicesDropdownSelect(selectedAnalysisServices) {
      this.$emit("onAnalysisServicesDropdownSelect", selectedAnalysisServices);
    }
  }
}
</script>

// sarathi-ang-1.0/src/app/components/users/USA/EQ/Analysis/united-states-of-america-shares-analysis-services-header/united-states-of-america-shares-analysis-services-header.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';

@Component({
  selector: 'app-united-states-of-america-shares-analysis-services-header',
  templateUrl: './united-states-of-america-shares-analysis-services-header.component.html',
  styleUrls: ['./united-states-of-america-shares-analysis-services-header.component.css']
})
export class UnitedStatesOfAmericaSharesAnalysisServicesHeaderComponent implements OnInit {

  @Input() resetAnalysisServicesDropdown!: boolean;
  @Input() analysisServicesDropdownList!: Array<any>;
  @Output("onAnalysisServicesDropdownSelect") onAnalysisServicesDropdownSelectEventEmitter = new EventEmitter<any>();

  constructor() { }

  ngOnInit(): void {
  }

  onAnalysisServicesDropdownSelect(selectedAnalysisServices: any) {
    this.onAnalysisServicesDropdownSelectEventEmitter.emit(selectedAnalysisServices);
  }
}

<div class="united-states-of-america-shares-analysis-services-header">
  <div class="services-analysis-header">
    <app-money-manager-dropdown
      [resetDropdown]="resetAnalysisServicesDropdown"
      [dropdownList]="analysisServicesDropdownList"
      [placeholder]="'Analysis Services'"
      (onDropdownSelect)="onAnalysisServicesDropdownSelect($event)"
    ></app-money-manager-dropdown>
  </div>
</div>
