// sarathi-vue-1.0/src/components/Users/BHA/EQ/Home/BhaarathaSharesHomeHeader.vue
<template>
  <div class="bhaaratha-shares-home-header">
    <div class="services-home-header">
      <MoneyManagerDropdown
        :resetDropdown="otherServicesDropdownResetDropdown"
        :dropdownList="otherServicesDropdownList"
        :placeholder="'Other Services'"
        @onDropdownSelect="onOtherServicesDropdownSelect($event)"
      ></MoneyManagerDropdown>
    </div>
  </div>
</template>

<script>
import MoneyManagerDropdown from "@/components/common/MoneyManagerDropdown.vue";

export default {
  components: {
    MoneyManagerDropdown
  },

  props: {
    otherServicesDropdownResetDropdown: {
      type: Boolean,
      required: true
    },
    otherServicesDropdownList: {
      type: Array,
      required: true
    }
  },

  methods: {
    onOtherServicesDropdownSelect(dropdownServicesSelected) {
      this.$emit('onOtherServicesDropdownSelect', dropdownServicesSelected);
    }
  }
}
</script>

// sarathi-ang-1.0/src/app/components/users/BHA/EQ/Home/bhaaratha-shares-home-header/bhaaratha-shares-home-header.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';

@Component({
  selector: 'app-bhaaratha-shares-home-header',
  templateUrl: './bhaaratha-shares-home-header.component.html',
  styleUrls: ['./bhaaratha-shares-home-header.component.css']
})
export class BhaarathaSharesHomeHeaderComponent implements OnInit {

  @Input() otherServicesDropdownResetDropdown!: boolean;
  @Input() otherServicesDropdownList!: Array<any>;
  @Output("onOtherServicesDropdownSelect") onOtherServicesDropdownSelectEventEmitter = new EventEmitter<any>();

  constructor() { }

  ngOnInit(): void {
  }

  onOtherServicesDropdownSelect(dropdownServicesSelected: any) {
    this.onOtherServicesDropdownSelectEventEmitter.emit(dropdownServicesSelected);
  }

}
