// sarathi-vue-1.0/src/components/MoneyManagerHeader.vue
<template>
  <div class="mm-header">
    <img class="mm-header-logo" src="../assets/logo/money-manager-full-logo.jpg" />
    <div class="mm-header-right">
      <div>{{ sarathiAppDetails }}</div>
      <div>{{ anukyaAppDetails }}</div>
    </div>
  </div>
</template>

<script>
import axios from "axios";
import services from "@/assets/services/services.json";

export default {
  data() {
    return {
      sarathiAppDetails: "",
      anukyaAppDetails: ""
    }
  },
  mounted() {
    axios.get(services.preData).then(response => {
      // Store - Country Details
      this.$store.commit("preData/SET_COUNTRY_DETAILS_MAP", response.data.countryDetailsMap);

      // Store - Services Offered Details Map
      this.$store.commit("preData/SET_SERVICES_OFFERED_DETAILS_MAP", response.data.servicesOfferedDetailsMap);

      // Store - Countries and Services Offered Details Map
      this.$store.commit("preData/SET_COUNTRIES_AND_SERVICES_OFFERED_DETAILS_MAP", response.data.countriesAndServicesOfferedDetailsMap);

      // Store - Gender Details Map
      this.$store.commit("preData/SET_GENDER_DETAILS_MAP", response.data.genderDetailsMap);

      // Store - Sub Services Details Map
      this.$store.commit("preData/SET_SUB_SERVICES_DETAILS_MAP", response.data.subServicesDetailsMap);

      // Store - Sub Services By Service Code Details Map
      this.$store.commit("preData/SET_SUB_SERVICES_BY_SERVICE_CODE_DETAILS_MAP", response.data.subServicesByServiceCodeDetailsMap);
    });

    this.sarathiAppDetails = "SARATHI (" + process.env.VUE_APP_ACTIVE_PROFILE + "): " + "v" + process.env.VUE_APP_VERSION;

    axios.get(services.appDetails).then(response => {
      this.anukyaAppDetails = response.data;
    }).catch(error => {
      console.log(error);
      this.anukyaAppDetails = "ERROR"
    })
  }
}
</script>

// sarathi-ang-1.0/src/app/components/money-manager-header/money-manager-header.component.ts
import { Component, OnInit } from '@angular/core';
import { environment } from 'src/environments/environment';
import { HttpClient } from '@angular/common/http';
import services from '../../../assets/services/services.json';
import { PreDataStoreService } from 'src/app/common/store/pre-data/pre-data-store.service';

@Component({
  selector: 'app-money-manager-header',
  templateUrl: './money-manager-header.component.html',
  styleUrls: ['./money-manager-header.component.css']
})
export class MoneyManagerHeaderComponent implements OnInit {

  sarathiAppDetails: string = "";
  anukyaAppDetails: string = "";

  constructor(
    private http: HttpClient,
    private preDataStoreService: PreDataStoreService
  ) { }

  ngOnInit(): void {
    this.http.get<any>(services.preData).subscribe(response => {
      // Store - Country Details
      this.preDataStoreService.setCountryDetailsMap(response.countryDetailsMap);

      // Store - Services Offered Details
      this.preDataStoreService.setServicesOfferedDetailsMap(response.servicesOfferedDetailsMap);

      // Store - Countries and Services Offered Details
      this.preDataStoreService.setCountriesAndServicesOfferedDetailsMap(response.countriesAndServicesOfferedDetailsMap);

      // Store - Gender Details
      this.preDataStoreService.setGenderDetailsMap(response.genderDetailsMap);

      // Store - Sub Services Details
      this.preDataStoreService.setSubServicesDetailsMap(response.subServicesDetailsMap);

      // Store - Sub Services by Service Code Details
      this.preDataStoreService.setSubServicesByServiceCodeDetailsMap(response.subServicesByServiceCodeDetailsMap);
    });

    this.sarathiAppDetails = "SARATHI (" + environment.ACTIVE_PROFILE + "): " + "v" + environment.APP_VERSION;

    this.http.get<any>(services.appDetails, { responseType: 'text' as 'json' }).subscribe(response => {
      this.anukyaAppDetails = response;
    }, error => {
      console.log(error);
      this.anukyaAppDetails = "ERROR";
    })
  }
}

<div class="mm-header">
    <img class="mm-header-logo" src="../../../assets/logo/money-manager-full-logo.jpg" />
    <div class="mm-header-right">
        <div>{{ sarathiAppDetails }}</div>
        <div>{{ anukyaAppDetails }}</div>
    </div>
</div>
