// sarathi-vue-1.0/src/components/Users/BHA/EQ/BhaarathaSharesBulkUpload.vue
<template>
  <div class="bhaaratha-shares-bulk-upload">
    <div class="services-bulk-upload">
      <div class="header">
        <span class="left-items">
          <MoneyManagerButton
            :buttonTitle="'Home'"
            :buttonClass="'btn-primary btn-sm'"
            @onButtonClick="onHomeButtonClick()"
          ></MoneyManagerButton>
        </span>

        <span class="left-items">
          <MoneyManagerButton
            :buttonTitle="'Bought'"
            :buttonClass="'btn-buy btn-sm btn-sm'"
            @onButtonClick="onBoughtButtonClick()"
          ></MoneyManagerButton>
        </span>

        <span class="left-items">
          <MoneyManagerButton
            :buttonTitle="'Sold'"
            :buttonClass="'btn-sell btn-sm'"
            @onButtonClick="onSoldButtonClick()"
          ></MoneyManagerButton>
        </span>

        <div class="right">
          <span class="right-items">
            <MoneyManagerButton
              :buttonClass="'btn-secondary btn-sm'"
              @onButtonClick="onDownloadBulkUploadDocumentClick()"
            >
              <template v-slot:title>
                <i class="fa fa-download"></i>
              </template>
            </MoneyManagerButton>
          </span>
        </div>
      </div>

      <div class="spinner" v-if="loading">
        <MoneyManagerLoading></MoneyManagerLoading>
      </div>
      <div v-if="!loading" class="services-bulk-upload-area">
        <div class="services-bulk-upload-input">
          <input type="file" id="file-upload" ref="bhaarathaSharesBulkUploadFileUpload" class="input-file-upload" @change="onInputFileUploadChange($event)">
          <MoneyManagerButton
            :buttonClass="'btn-secondary btn-sm'"
            @onButtonClick="uploadFileClick()"
          >
            <template v-slot:title>
              <i class="fa fa-upload"></i>
            </template>
          </MoneyManagerButton>
          <span class="file-name">{{ filename }}</span>
        </div>
        <div class="services-bulk-upload-clear-submit">
          <span>
            <MoneyManagerButton
              :buttonTitle="'Clear'"
              :buttonDisabled="file === null"
              :buttonClass="file === null ? 'btn-sm' : 'btn-secondary btn-sm'"
              @onButtonClick="onBulkUploadClear()"
            ></MoneyManagerButton>
          </span>
          <div class="services-bulk-upload-submit">
            <MoneyManagerButton
              :buttonTitle="'Submit'"
              :buttonDisabled="file === null"
              :buttonClass="file === null ? 'btn-sm' : 'btn-primary btn-sm'"
              @onButtonClick="onBulkUploadSubmit()"
            ></MoneyManagerButton>
          </div>
        </div>
      </div>

      <SuccessModal
        v-if="showSuccess"
      >
        <template v-slot:header>
          <h3 class="mm-success-modal-title">Success!!</h3>
          <span>
            <MoneyManagerButton
              :buttonClass="'btn-close'"
              @onButtonClick="closeSuccess()"
            >
            </MoneyManagerButton>
          </span>
        </template>
        <template v-slot:body>
          <span v-html="successMessage"></span>
        </template>
      </SuccessModal>

      <ErrorModal
        v-if="showError"
      >
        <template v-slot:header>
          <h3 class="mm-error-modal-title">Error!!</h3>
          <span>
            <MoneyManagerButton
              :buttonClass="'btn-close'"
              @onButtonClick="closeError()"
            >
            </MoneyManagerButton>
          </span>
        </template>
        <template v-slot:body>
          <span v-html="errorMessage"></span>
        </template>
      </ErrorModal>
    </div>
  </div>
</template>

<script>
import MoneyManagerLoading from "@/components/common/MoneyManagerLoading.vue";
import MoneyManagerButton from "@/components/common/MoneyManagerButton.vue";
import SuccessModal from "@/components/common/SuccessModal.vue";
import ErrorModal from "@/components/common/ErrorModal.vue";
import axios from 'axios';
import services from "@/assets/services/services.json";

export default {

  components: {
    MoneyManagerLoading,
    MoneyManagerButton,
    SuccessModal,
    ErrorModal
  },

  data() {
    return {
      loading: false,
      file: null,
      filename: "",
      showSuccess: false,
      successMessage: "",
      showError: false,
      errorMessage: ""
    }
  },

  methods: {
    onHomeButtonClick() {
      this.$router.push("/users/BHA/EQ/home");
    },

    onBoughtButtonClick() {
      this.$router.push("/users/BHA/EQ/bought");
    },

    onSoldButtonClick() {
      this.$router.push("/users/BHA/EQ/sold");
    },

    onDownloadBulkUploadDocumentClick() {
      axios.get(services.bhaarathaSharesDownloadBulkUploadDocument, { responseType: 'blob' }).then(response => {
        let a = document.createElement("a");
        document.body.appendChild(a);

        let file = window.URL.createObjectURL(new Blob([response.data], { type : "application/vnd.ms-excel" }));

        a.href = file;
        a.download = response.headers.filename;
        a.click();
      }).catch(error => {
        error.response.data.error.map((e) => {
          this.errorMessage = e.errorMessage;
          this.showError = true;
        });
      });
    },

    uploadFileClick() {
      document.getElementById("file-upload").click();
    },

    onInputFileUploadChange(event) {
      this.file = event.target.files[0];
      this.filename = this.file.name;
    },

    onBulkUploadClear() {
      this.file = null;
      this.filename = "";
      this.$refs.bhaarathaSharesBulkUploadFileUpload.value="";
    },

    onBulkUploadSubmit() {
      this.loading = true;

      let formData = new FormData();
      formData.append("file", this.file);

      axios.post(services.bhaarathaSharesBulkUploadDocument, formData).then(response => {
        this.successMessage = response.data.message;
        this.showSuccess = true;
        this.file = null;
        this.filename = "";
        this.loading = false;
      }).catch(error => {
        error.response.data.error.map((e) => {
          this.errorMessage = e.errorMessage;
          this.showError = true;
        });
        this.loading = false;
      });
    },

    closeError() {
      this.errorMessage = "";
      this.showError = false;
    },

    closeSuccess() {
      this.successMessage = "";
      this.showSuccess = false;
    }
  }
}
</script>

// sarathi-ang-1.0/src/app/components/users/BHA/EQ/bhaaratha-shares-bulk-upload/bhaaratha-shares-bulk-upload.component.ts
import { HttpClient } from '@angular/common/http';
import { Component, OnInit, ViewChild } from '@angular/core';
import { Router } from '@angular/router';
import services from 'src/assets/services/services.json';

@Component({
  selector: 'app-bhaaratha-shares-bulk-upload',
  templateUrl: './bhaaratha-shares-bulk-upload.component.html',
  styleUrls: ['./bhaaratha-shares-bulk-upload.component.css']
})
export class BhaarathaSharesBulkUploadComponent implements OnInit {

  @ViewChild("bhaarathaSharesBulkUploadFileUpload") bhaarathaSharesBulkUploadFileUpload: any;

  loading: boolean = false;
  file: any = null;
  filename: string = ""
  showSuccess: boolean = false;
  successMessage: string = "";
  showError: boolean = false;
  errorMessage: string = "";

  constructor(
    private http: HttpClient,
    private router: Router
  ) { }

  ngOnInit(): void {
  }

  onHomeButtonClick() {
    this.router.navigate(["/users/BHA/EQ/home"]);
  }

  onBoughtButtonClick() {
    this.router.navigate(["/users/BHA/EQ/bought"]);
  }

  onSoldButtonClick() {
    this.router.navigate(["/users/BHA/EQ/sold"]);
  }

  onDownloadBulkUploadDocumentClick() {
    this.http.get(services.bhaarathaSharesDownloadBulkUploadDocument, { observe: "response",  responseType: 'blob' }).subscribe((response: any) => {

      let blob: Blob = response.body as Blob;
      let a = document.createElement("a");
      a.download = response.headers.get("fileName");
      a.href = window.URL.createObjectURL(blob);
      a.click();
    }, error => {
      error.error.error.map((e: any) => {
        this.errorMessage = e.errorMessage;
        this.showError = true;
      });
    });
  }

  uploadFileClick() {
    (document.getElementById("file-upload") as HTMLElement).click();
  }

  onInputFileUploadChange(event: any) {
    this.file = event.target.files[0];
    this.filename = this.file.name;
  }

  onBulkUploadClear() {
    this.file = null;
    this.filename = "";
    this.bhaarathaSharesBulkUploadFileUpload.nativeElement.value = "";
  }

  onBulkUploadSubmit() {
    this.loading = true;

    let formData = new FormData();
    formData.append("file", this.file);

    this.http.post(services.bhaarathaSharesBulkUploadDocument, formData).subscribe((response: any) => {
      this.successMessage = response.message;
      this.showSuccess = true;
      this.file = null;
      this.filename = "";
      this.loading = false;
    }, error => {
      error.error.error.map((e: any) => {
        this.errorMessage = e.errorMessage;
        this.showError = true;
      });
      this.loading = false;
    });
  }

  closeError() {
    this.errorMessage = "";
    this.showError = false;
  }

  closeSuccess() {
    this.successMessage = "";
    this.showSuccess = false;
  }
}

<div class="bhaaratha-shares-bulk-upload">
  <div class="services-bulk-upload">
    <div class="header">
      <span class="left-items">
        <app-money-manager-button
          [buttonTitle]="'Home'"
          [buttonClass]="'btn-primary btn-sm'"
          (onButtonClick)="onHomeButtonClick()"
        ></app-money-manager-button>
      </span>

      <span class="left-items">
        <app-money-manager-button
          [buttonTitle]="'Bought'"
          [buttonClass]="'btn-buy btn-sm btn-sm'"
          (onButtonClick)="onBoughtButtonClick()"
        ></app-money-manager-button>
      </span>

      <span class="left-items">
        <app-money-manager-button
          [buttonTitle]="'Sold'"
          [buttonClass]="'btn-sell btn-sm'"
          (onButtonClick)="onSoldButtonClick()"
        ></app-money-manager-button>
      </span>

      <div class="right">
        <span class="right-items">
          <app-money-manager-button
            [buttonClass]="'btn-secondary btn-sm'"
            (onButtonClick)="onDownloadBulkUploadDocumentClick()"
          >
            <span title>
              <i class="fa fa-download"></i>
            </span>
          </app-money-manager-button>
        </span>
      </div>
    </div>

    <div class="spinner" *ngIf="loading">
      <app-money-manager-loading></app-money-manager-loading>
    </div>
    <div *ngIf="!loading" class="services-bulk-upload-area">
      <div class="services-bulk-upload-input">
        <input type="file" id="file-upload" #bhaarathaSharesBulkUploadFileUpload class="input-file-upload" (change)="onInputFileUploadChange($event)">
        <app-money-manager-button
          [buttonClass]="'btn-secondary btn-sm'"
          (onButtonClick)="uploadFileClick()"
        >
          <span title>
            <i class="fa fa-upload"></i>
          </span>
        </app-money-manager-button>
        <span class="file-name">{{ filename }}</span>
      </div>
      <div class="services-bulk-upload-clear-submit">
        <span>
          <app-money-manager-button
            [buttonTitle]="'Clear'"
            [buttonDisabled]="file === null"
            [buttonClass]="file === null ? 'btn-sm' : 'btn-secondary btn-sm'"
            (onButtonClick)="onBulkUploadClear()"
          ></app-money-manager-button>
        </span>
        <div class="services-bulk-upload-submit">
          <app-money-manager-button
            [buttonTitle]="'Submit'"
            [buttonDisabled]="file === null"
            [buttonClass]="file === null ? 'btn-sm' : 'btn-primary btn-sm'"
            (onButtonClick)="onBulkUploadSubmit()"
          ></app-money-manager-button>
        </div>
      </div>
    </div>

    <app-success-modal
      *ngIf="showSuccess"
      (closeSuccess)="closeSuccess()"
    >
      <span body>
        <span [innerHtml]="successMessage"></span>
      </span>
    </app-success-modal>

    <app-error-modal
      *ngIf="showError"
      (closeError)="closeError()"
    >
      <span body>
        <span [innerHtml]="errorMessage"></span>
      </span>
    </app-error-modal>
  </div>
</div>
